//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Dom_Class_LineaFacVen.java
//  @ Date : 06/05/2010
//  @ Author : 
//
//



package Logica_Negocio.Dominio.Facturacion;


import Logica_Negocio.LogN_ClassAb_LineaFac;
import Logica_Negocio.LogN_ClassAb_Producto;
import Logica_Negocio.MiExepcion.InputException;
import Precentacion.LogN_Class_Accion;


/**
 * Linea de factura de venta 
**/
public class Dom_Class_LineaFacVen extends LogN_ClassAb_LineaFac{


    //Constructor_______________________________________________________________
    public Dom_Class_LineaFacVen(float mCan, float mDes, LogN_ClassAb_Producto mObjProducto) throws InputException {
        super(mCan, mDes, mObjProducto);
    }

    public Dom_Class_LineaFacVen(float mCan, float mDes, float mPrePro, LogN_ClassAb_Producto mObjProducto) throws InputException {
        super(mCan, mDes, mPrePro, mObjProducto);
    }



    @Override
    public void actualizarStok() throws InputException{
        
    }

    @Override
    public void setCan(float mCan) throws InputException {
        if (mCan > getmObjArt().getMProd_Stock())throw
                new InputException("La cantidad de la línea supera el stock del producto");   
        if(this.getmObjArt().Tipo_Stok == LogN_ClassAb_Producto.Stok_Unidad){
            int CanP = (int) mCan;
            if (CanP != mCan)throw  new InputException("La cantidad de la línea no coinside con el tipo de stok");
        } 
        super.mCan = mCan;
        
        Notificar(new LogN_Class_Accion<LogN_ClassAb_LineaFac> (LogN_Class_Accion.Modificar,this));
    }

}

