//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Dom_Class_IVA.java
//  @ Date : 06/05/2010
//  @ Author : 
//
//



package Logica_Negocio.Dominio;


import Logica_Negocio.MiExepcion.InputException;
import Utilidades.Util_Class_Utilitario;
import java.util.ArrayList;


public class Dom_Class_IVA {
    //Atributos_________________________________________________________________
    
    /**
     * Numero de IVA
     */
    private int mNum = -1;
    
    /**
     * Descripcion del IVA
     */
    private String mDes;
    /**
     * Porsentaje del IVA;
     */
    private float mVal;



    //Operaciones_______________________________________________________________
    
    public Dom_Class_IVA(String mDes, float mVal) {
        this.mDes = mDes;
        this.mVal = mVal;
    }

    public String getmDes() {
       return mDes;
    }

    public boolean setmDes(String mDes) {
        if (!Util_Class_Utilitario.ValidarString(mDes)) return false;
        this.mDes = mDes.trim(); return true;
    }

    public float getmVal() {
        return mVal;

    }

    /**
     * Remplaza el porcentaje del IVA
     * @param mVal Porcentaje del IVA por el cual se remplaza
     * @return  true si el valor pasado por parámetro es mayor a 0, false en caso contrario
     */
    public boolean setmVal(float mVal) {
        if (mVal < 0) return false;
        this.mVal = mVal; return true;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Dom_Class_IVA other = (Dom_Class_IVA) obj;
        if ((this.mDes == null) ? (other.mDes != null) : !this.mDes.equals(other.mDes)) {
            return false;
        }
        if (this.mVal != other.mVal) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + (this.mDes != null ? this.mDes.hashCode() : 0);
        hash = 67 * hash + Float.floatToIntBits(this.mVal);
        return hash;
    }

    public int getmNum() {
        return mNum;
    }

    public void setmNum(int mNum) {
        this.mNum = mNum;
    }
    

////    public float agretarIva(float precio) {
////
////    }
////
////    public float sacarIva(float precio) {
////
////    }
    
    public void validar ()throws InputException{
        String Error = "";
        if (!this.setmVal(mVal)) Error +="El porcentaje del IVA es menor a 0 \n";
        if (!this.setmDes(mDes)) Error += "Este IVA no posee una descripción.";
        
        if (!Error.equals("")) throw new InputException(Error);
    }

    public String[] getIgualInva (Dom_Class_IVA xObjIva){
        ArrayList <String> ColNomIgual = new ArrayList<String>();

        if (xObjIva.mDes.equals(mDes)) ColNomIgual.add("descripción");
        if (xObjIva.mVal == mVal) ColNomIgual.add("descuento");

        String [] ColRes = new String [ColNomIgual.size()];
        for (int i = 0; i < ColNomIgual.size(); i++){
            ColRes [i] = ColNomIgual.get(i);
        }
        return ColRes;
    }

    @Override
    public String toString() {
        return mDes + ": " +  mVal +"%";
    }






    
}
