/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pre_FrmDi_ConArt.java
 *
 * Created on 27/03/2010, 02:44:16 PM
 */

package Precentacion;



import Logica_Negocio.LogN_ClassAb_Factura;
import Logica_Negocio.LogN_ClassAb_Producto;
import Logica_Negocio.LogN_Class_ObsevadoAuxiliar;
import Logica_Negocio.MiExepcion.InputException;
import Precentacion.Model.jTabel.ModeljTabLinFac;
import Reportes.Rep_Class_IniciarReporte;
import Utilidades.Util_Class_Utilitario;
import java.beans.PropertyVetoException;
import java.security.Principal;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import net.sf.jasperreports.engine.JRException;


/**
 *
 * @author Ary
 */
public class FrmDi_ConLinFactura extends javax.swing.JDialog implements Observer{
    
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    private int returnStatus = RET_CANCEL;

    private NumberFormat nf = new DecimalFormat("#,##0.00");
    private LogN_ClassAb_Producto mObjProd;
    private FrmIn_ListarProducto mFrmList = new FrmIn_ListarProducto(this);
    
    private FrmIn_AgProducto mFrmAgrProd = new FrmIn_AgrProd(this);
    
    
    private LogN_ClassAb_Factura mObjFactura;
    private ModeljTabLinFac mObjModelLF;

    /** Creates new form Pre_FrmDi_ConArt */
    public FrmDi_ConLinFactura(java.awt.Window parent, LogN_ClassAb_Factura mObjFactrua  ) {

        super(parent,java.awt.Dialog.ModalityType.APPLICATION_MODAL); //Yama al contsructor de el dealog para bloquear los formularios ijos
        this. mObjFactura = mObjFactrua.duplicar();
        mObjModelLF = new ModeljTabLinFac(mObjFactrua.getmColLinF());

        initComponents();
        
        this.InisFor(mFrmAgrProd);
        
        this.InisFor(mFrmList);
        

        this.mObjFactura.addObserver(mObjModelLF);
        this.mObjFactura.addObserver(this);
        mFrmList.mObjObjAux.addObserver(this);
        mFrmAgrProd.mObjObservado.addObserver(this);
        
        cargarTotales();

    }

         private void InisFor (JInternalFrame Frm){

        Frm.setVisible(true);

        DexP_Prin.add(Frm);
        Frm.moveToFront(); // mueve acia delate el Formulario

        try {
            Frm.setMaximum(true);
        } catch (PropertyVetoException ex) {

            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        DexP_Prin = new javax.swing.JDesktopPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtF_Pre = new Utilidades.JFormattedText();
        TxtF_Des =  new Utilidades.JFormattedText();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        TxtF_CanPro = new Utilidades.JFormattedText();
        jLabel4 = new javax.swing.JLabel();
        TxtF_ValDes =  new Utilidades.JFormattedText();
        Btn_Aceptar = new javax.swing.JButton();
        Btn_Cancelar1 = new javax.swing.JButton();
        Lbl_Producto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tab_LF = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        Lbl_SubTotal = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        Lbl_IVA = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        Lbl_Total = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        Lbl_SubTotal2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        Lbl_IVA2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Btn_BuscarProd = new javax.swing.JToggleButton();
        Btn_AltaProd = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cantidad:");

        jLabel2.setText("Precio:");

        TxtF_Pre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        TxtF_Pre.setValue(0);
        TxtF_Pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtF_PreActionPerformed(evt);
            }
        });

        TxtF_Des.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        TxtF_Des.setValue(0);
        TxtF_Des.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtF_DesFocusGained(evt);
            }
        });

        jLabel3.setText("Descuento (%):");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Ab.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Ar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        TxtF_CanPro.setValue(new Float(0.0));
        TxtF_CanPro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtF_CanProFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_CanProFocusLost(evt);
            }
        });

        jLabel4.setText("Descuento:");

        TxtF_ValDes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        TxtF_ValDes.setValue(0);
        TxtF_ValDes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtF_ValDesFocusGained(evt);
            }
        });

        Btn_Aceptar.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Yes v3.png"))); // NOI18N
        Btn_Aceptar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.gray, null, java.awt.Color.gray));
        Btn_Aceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AceptarActionPerformed(evt);
            }
        });

        Btn_Cancelar1.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        Btn_Cancelar1.setForeground(new java.awt.Color(1, 1, 1));
        Btn_Cancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel_f2.png"))); // NOI18N
        Btn_Cancelar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.gray, null, java.awt.Color.gray));
        Btn_Cancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cancelar1ActionPerformed(evt);
            }
        });

        Lbl_Producto.setBackground(new java.awt.Color(255, 255, 204));
        Lbl_Producto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_Producto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lbl_Producto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Lbl_Producto.setMaximumSize(new java.awt.Dimension(72, 27));
        Lbl_Producto.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Producto:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(TxtF_CanPro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtF_Des, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtF_ValDes, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtF_Pre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Lbl_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Btn_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Cancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lbl_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtF_CanPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(TxtF_Des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtF_ValDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtF_Pre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Tab_LF.setModel(mObjModelLF);
        jScrollPane1.setViewportView(Tab_LF);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel14.setBackground(new java.awt.Color(1, 1, 1));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 1, true));

        Lbl_SubTotal.setBackground(new java.awt.Color(207, 228, 228));
        Lbl_SubTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_SubTotal.setText("00000");
        Lbl_SubTotal.setMaximumSize(new java.awt.Dimension(84, 27));
        Lbl_SubTotal.setOpaque(true);

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(" Sub Total:");
        jLabel21.setOpaque(true);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_SubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
            .addComponent(Lbl_SubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel17.setBackground(new java.awt.Color(1, 1, 1));
        jPanel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 1, true));

        Lbl_IVA.setBackground(new java.awt.Color(207, 228, 228));
        Lbl_IVA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_IVA.setText("00000");
        Lbl_IVA.setMaximumSize(new java.awt.Dimension(84, 27));
        Lbl_IVA.setOpaque(true);

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText(" IVA Tb.:");
        jLabel24.setOpaque(true);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
            .addComponent(Lbl_IVA, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 1, true));

        Lbl_Total.setBackground(new java.awt.Color(255, 102, 102));
        Lbl_Total.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Lbl_Total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Total.setText("00000");
        Lbl_Total.setMaximumSize(new java.awt.Dimension(84, 27));
        Lbl_Total.setOpaque(true);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(1, 1, 1));
        jLabel27.setText(" TOTAL:");
        jLabel27.setOpaque(true);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_Total, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
            .addComponent(Lbl_Total, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel16.setBackground(new java.awt.Color(1, 1, 1));
        jPanel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 1, true));

        Lbl_SubTotal2.setBackground(new java.awt.Color(207, 228, 228));
        Lbl_SubTotal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_SubTotal2.setText("00000");
        Lbl_SubTotal2.setMaximumSize(new java.awt.Dimension(84, 27));
        Lbl_SubTotal2.setOpaque(true);

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Des.:");
        jLabel23.setOpaque(true);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_SubTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addComponent(Lbl_SubTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(1, 1, 1));
        jPanel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 1, true));

        Lbl_IVA2.setBackground(new java.awt.Color(207, 228, 228));
        Lbl_IVA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_IVA2.setText("00000");
        Lbl_IVA2.setMaximumSize(new java.awt.Dimension(84, 27));
        Lbl_IVA2.setOpaque(true);

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText(" IVA Tm.:");
        jLabel26.setOpaque(true);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_IVA2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
            .addComponent(Lbl_IVA2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Print.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        buttonGroup1.add(Btn_BuscarProd);
        Btn_BuscarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Buscar P.png"))); // NOI18N
        Btn_BuscarProd.setSelected(true);
        Btn_BuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarProdActionPerformed(evt);
            }
        });

        buttonGroup1.add(Btn_AltaProd);
        Btn_AltaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Alta Producto.png"))); // NOI18N
        Btn_AltaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AltaProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DexP_Prin)
                        .addGap(2, 2, 2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_BuscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_AltaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Btn_BuscarProd, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_AltaProd, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(DexP_Prin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.altLF();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        bajaLF();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Btn_Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cancelar1ActionPerformed
        // TODO add your handling code here:
        this.doClose(FrmDi_ConLinFactura.RET_CANCEL);
}//GEN-LAST:event_Btn_Cancelar1ActionPerformed

    private void Btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AceptarActionPerformed
        doClose(FrmDi_ConLinFactura.RET_OK);
}//GEN-LAST:event_Btn_AceptarActionPerformed

    private void TxtF_DesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_DesFocusGained
        // TODO add your handling code here:
        Util_Class_Utilitario.SeleccionarTodoTexto(TxtF_Des);
    }//GEN-LAST:event_TxtF_DesFocusGained

    private void TxtF_PreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtF_PreActionPerformed
        // TODO add your handling code here:
        Util_Class_Utilitario.SeleccionarTodoTexto(TxtF_Pre);
    }//GEN-LAST:event_TxtF_PreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Rep_Class_IniciarReporte.imprimirPresupuesto(mObjFactura.getmColLinF());
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }

}//GEN-LAST:event_jButton1ActionPerformed

    private void TxtF_CanProFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_CanProFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_TxtF_CanProFocusGained

    private void TxtF_CanProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_CanProFocusLost
        TxtF_CanPro.setText(TxtF_CanPro.getText().replace(".", ","));
}//GEN-LAST:event_TxtF_CanProFocusLost

    private void TxtF_ValDesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_ValDesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_ValDesFocusGained

    private void Btn_BuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarProdActionPerformed
        // TODO add your handling code here:
        mFrmList.moveToFront();
    }//GEN-LAST:event_Btn_BuscarProdActionPerformed

    private void Btn_AltaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AltaProdActionPerformed
        // TODO add your handling code here:
        mFrmAgrProd.moveToFront();
    }//GEN-LAST:event_Btn_AltaProdActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Aceptar;
    private javax.swing.JToggleButton Btn_AltaProd;
    private javax.swing.JToggleButton Btn_BuscarProd;
    private javax.swing.JButton Btn_Cancelar1;
    private javax.swing.JDesktopPane DexP_Prin;
    private javax.swing.JLabel Lbl_IVA;
    private javax.swing.JLabel Lbl_IVA2;
    private javax.swing.JLabel Lbl_Producto;
    private javax.swing.JLabel Lbl_SubTotal;
    private javax.swing.JLabel Lbl_SubTotal2;
    private javax.swing.JLabel Lbl_Total;
    private javax.swing.JTable Tab_LF;
    protected javax.swing.JFormattedTextField TxtF_CanPro;
    private javax.swing.JFormattedTextField TxtF_Des;
    private javax.swing.JFormattedTextField TxtF_Pre;
    private javax.swing.JFormattedTextField TxtF_ValDes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof LogN_Class_ObsevadoAuxiliar){
            LogN_Class_ObsevadoAuxiliar ObjObsAux = (LogN_Class_ObsevadoAuxiliar)o;
            if (ObjObsAux.getmObjObservado() == mFrmList) setProductoSel(mFrmList.getSelectedProd());
            if (ObjObsAux.getmObjObservado() == mFrmAgrProd) 
                setProductoSel((LogN_ClassAb_Producto)arg);
        }else if (o == mObjFactura){
            this.cargarTotales();
        }
    }

    private void setProductoSel (LogN_ClassAb_Producto xobjPord){
        mObjProd = xobjPord;
        TxtF_Pre.setValue(new Float(mObjProd.getMProd_PrecVenta()));
        
        CargarCantidad(xobjPord);
        Lbl_Producto.setText(xobjPord.toString() + " Detalle: "  + 
                xobjPord.getmObjCat().getNom() + " " + xobjPord.getMProd_Nom());
        TxtF_Des.setValue(0);
        TxtF_ValDes.setValue(0);
    }
    // No tengo claro
    private void CargarCantidad (LogN_ClassAb_Producto xObjProd){
        String TextTMoel = "#,##0.000";
        float Cantidad = 0;
        if (xObjProd.Tipo_Stok == LogN_ClassAb_Producto.Stok_Unidad){
            TextTMoel = "#,##0";
            Cantidad = 1;
        }

        TxtF_CanPro.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new java.text.DecimalFormat(TextTMoel))));
        TxtF_CanPro.setValue(new Float(Cantidad));
    }

    private void altLF() {
        if (mObjProd == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto");
            return;
        }
        
        Number Can = (Number) TxtF_CanPro.getValue();
        

        Number PrePro = (Number) TxtF_Pre.getValue();
        Number Des = (Number) TxtF_Des.getValue();
        try {
            mObjFactura.altaLineaFact(mObjFactura.CrearLinFac(Can.floatValue(), Des.floatValue(), PrePro.floatValue(), mObjProd));
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }
    }

    private void bajaLF (){
        int Pos = Tab_LF.getSelectedRow();
        if (Pos == -1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una línea de factura a dar de baja");
            return;
        }
        
        mObjFactura.bajaLineaFach(mObjModelLF.getLinFac(Pos));

    }

    private void cargarTotales (){
        Lbl_IVA.setText("" + nf.format(mObjFactura.getResIva1()));
        Lbl_SubTotal.setText("" + nf.format(mObjFactura.getSubTot()));
        Lbl_Total.setText("" + nf.format(mObjFactura.getTotFin()));
    }
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    public int getStatus(){
         return returnStatus;
    }
    
    public LogN_ClassAb_Factura getFactura(){
         return mObjFactura;
     }
}
