/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmDi_Movimiento.java
 *
 * Created on 15/03/2011, 06:06:12 PM
 */

package Precentacion;

import Logica_Negocio.Dominio.Dom_Class_MovEntrada;
import Logica_Negocio.Dominio.Dom_Class_MovSalida;
import Logica_Negocio.Dominio.Dom_Class_ProductoComp;
import Logica_Negocio.LogN_ClassAb_Movimiento;
import Logica_Negocio.MiExepcion.InputException;
import Utilidades.Util_Class_Utilitario;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ary
 */
public class FrmDi_Movimiento extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    private static String mAutorisa , mAsunto, mDetalle;

    private LogN_ClassAb_Movimiento mObjMov;
    private Dom_Class_ProductoComp mObjPersonaCom;

    /** Creates new form FrmDi_Movimiento */
    private FrmDi_Movimiento(java.awt.Window parent) {
        super(parent, java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        initComponents();


    }
    public FrmDi_Movimiento(java.awt.Window parent, LogN_ClassAb_Movimiento mObjMov){
        this(parent);
        this.mObjMov = mObjMov;
        this.CargarMov(mObjMov);


    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Lbl_DesOr = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtA_Detalle = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        Pan_TipoMov = new javax.swing.JPanel();
        Rd_Salida = new javax.swing.JRadioButton();
        Rd_Entrada = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        Lbl_NumMov = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lbl_FechAc = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Lbl_Producto = new javax.swing.JLabel();
        TxtF_CanProd = new Utilidades.JFormattedText();
        Lbl_DesOr1 = new javax.swing.JLabel();
        Txt_Autoriso = new javax.swing.JTextField();
        Txt_DesOrigen = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(13, 151, 239));
        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Numero");
        jLabel1.setOpaque(true);

        Lbl_DesOr.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_DesOr.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Lbl_DesOr.setForeground(new java.awt.Color(254, 254, 254));
        Lbl_DesOr.setText("Destino/Origen");
        Lbl_DesOr.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(13, 151, 239));
        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Autorisado");
        jLabel3.setOpaque(true);

        TxtA_Detalle.setColumns(20);
        TxtA_Detalle.setRows(5);
        TxtA_Detalle.setTabSize(0);
        TxtA_Detalle.setText(mDetalle);
        TxtA_Detalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtA_DetalleKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TxtA_Detalle);

        jLabel4.setBackground(new java.awt.Color(13, 151, 239));
        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Detalle");
        jLabel4.setOpaque(true);

        Pan_TipoMov.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup1.add(Rd_Salida);
        Rd_Salida.setSelected(true);
        Rd_Salida.setText("Salida");

        buttonGroup1.add(Rd_Entrada);
        Rd_Entrada.setText("Entrada");
        Rd_Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rd_EntradaActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(13, 151, 239));
        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Tipo Movimiento");
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout Pan_TipoMovLayout = new javax.swing.GroupLayout(Pan_TipoMov);
        Pan_TipoMov.setLayout(Pan_TipoMovLayout);
        Pan_TipoMovLayout.setHorizontalGroup(
            Pan_TipoMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
            .addGroup(Pan_TipoMovLayout.createSequentialGroup()
                .addComponent(Rd_Entrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rd_Salida))
        );
        Pan_TipoMovLayout.setVerticalGroup(
            Pan_TipoMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_TipoMovLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pan_TipoMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rd_Salida)
                    .addComponent(Rd_Entrada)))
        );

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Yes v3.png"))); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel_f2.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        Lbl_NumMov.setBackground(new java.awt.Color(255, 255, 153));
        Lbl_NumMov.setForeground(new java.awt.Color(102, 102, 102));
        Lbl_NumMov.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Lbl_NumMov.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        Lbl_NumMov.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(13, 151, 239));
        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Fecha Hora");
        jLabel2.setOpaque(true);

        Lbl_FechAc.setBackground(new java.awt.Color(255, 255, 153));
        Lbl_FechAc.setForeground(new java.awt.Color(102, 102, 102));
        Lbl_FechAc.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Lbl_FechAc.setText(Util_Class_Utilitario.getFecha("dd/MM/yyyy HH:mm:ss", new Date()));
        Lbl_FechAc.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        Lbl_FechAc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Lbl_FechAc.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(13, 151, 239));
        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Producto");
        jLabel6.setOpaque(true);

        Lbl_Producto.setBackground(new java.awt.Color(255, 255, 153));
        Lbl_Producto.setForeground(new java.awt.Color(102, 102, 102));
        Lbl_Producto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Lbl_Producto.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        Lbl_Producto.setOpaque(true);

        TxtF_CanProd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.000"))));
        TxtF_CanProd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtF_CanProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtF_CanProdActionPerformed(evt);
            }
        });
        TxtF_CanProd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_CanProdFocusLost(evt);
            }
        });

        Lbl_DesOr1.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_DesOr1.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Lbl_DesOr1.setForeground(new java.awt.Color(254, 254, 254));
        Lbl_DesOr1.setText("Can. Articulo");
        Lbl_DesOr1.setOpaque(true);

        Txt_Autoriso.setText(mAutorisa);
        Txt_Autoriso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_AutorisoFocusLost(evt);
            }
        });

        Txt_DesOrigen.setText(mAsunto);
        Txt_DesOrigen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_DesOrigenFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_Autoriso, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_DesOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(Lbl_DesOr, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtF_CanProd, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(Lbl_DesOr1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(Pan_TipoMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbl_NumMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lbl_FechAc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lbl_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_NumMov, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_FechAc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lbl_DesOr)
                        .addComponent(Lbl_DesOr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtF_CanProd)
                        .addComponent(Txt_Autoriso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Txt_DesOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Pan_TipoMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void Rd_EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rd_EntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rd_EntradaActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
}//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
}//GEN-LAST:event_cancelButtonActionPerformed

    private void TxtF_CanProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtF_CanProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_CanProdActionPerformed

    private void TxtF_CanProdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_CanProdFocusLost
        // TODO add your handling code here:
        TxtF_CanProd.setText(TxtF_CanProd.getText().replace(".", ","));
    }//GEN-LAST:event_TxtF_CanProdFocusLost

    private void TxtA_DetalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtA_DetalleKeyPressed
        // TODO add your handling code here:
         if ( evt.getKeyChar() == java.awt.event.KeyEvent.VK_TAB)okButton.requestFocus();
    }//GEN-LAST:event_TxtA_DetalleKeyPressed

    private void Txt_AutorisoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_AutorisoFocusLost
        // TODO add your handling code here:
        Txt_Autoriso.selectAll();
    }//GEN-LAST:event_Txt_AutorisoFocusLost

    private void Txt_DesOrigenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_DesOrigenFocusLost
        // TODO add your handling code here:
        Txt_DesOrigen.selectAll();
    }//GEN-LAST:event_Txt_DesOrigenFocusLost



////    /**
////    * @param args the command line arguments
////    */
////    public static void main(String args[]) {
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                FrmDi_Movimiento dialog = new FrmDi_Movimiento(new javax.swing.JFrame(), true);
////                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
////                    public void windowClosing(java.awt.event.WindowEvent e) {
////                        System.exit(0);
////                    }
////                });
////                dialog.setVisible(true);
////            }
////        });
////    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_DesOr;
    private javax.swing.JLabel Lbl_DesOr1;
    private javax.swing.JLabel Lbl_FechAc;
    private javax.swing.JLabel Lbl_NumMov;
    private javax.swing.JLabel Lbl_Producto;
    private javax.swing.JPanel Pan_TipoMov;
    private javax.swing.JRadioButton Rd_Entrada;
    private javax.swing.JRadioButton Rd_Salida;
    private javax.swing.JTextArea TxtA_Detalle;
    private javax.swing.JFormattedTextField TxtF_CanProd;
    private javax.swing.JTextField Txt_Autoriso;
    private javax.swing.JTextField Txt_DesOrigen;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;



    private void CargarMov(LogN_ClassAb_Movimiento xObjMov) {
        setProductoCom(xObjMov.getPord());


        Lbl_NumMov.setText("" + xObjMov.getNumModificador());
        Lbl_Producto.setText(xObjMov.getPord().toString());
        try {
            xObjMov.validar();
            Txt_Autoriso.setText(xObjMov.getmAutoriso());
            Txt_DesOrigen.setText(xObjMov.getmDes_Origen());
            TxtA_Detalle.setText(xObjMov.getmDetalle());
        } catch (InputException ex) {
           
        }

        TxtF_CanProd.setValue(xObjMov.getCanProd());

        boolean Entrada = false;
        String Titulo = "Destino";
        String TitelF = "Movimiento Salida";

        if (xObjMov instanceof Dom_Class_MovEntrada){
            Entrada = true;
            Titulo = "Origen";
            TitelF = "Movimiento Entrada";
            Rd_Entrada.setSelected(true);
        }

        Lbl_DesOr.setText(Titulo);
        this.setTitle(TitelF);
        Pan_TipoMov.setVisible(false);
        
    }
    private void setProductoCom (Dom_Class_ProductoComp xObjProdCom){
        this.mObjPersonaCom = xObjProdCom;
        String TipStok = "";
        switch (mObjPersonaCom.Tipo_Stok) {
            case Dom_Class_ProductoComp.Stok_Decimo:
                TipStok = "#,##0.000";
            break;
            case (Dom_Class_ProductoComp.Stok_Unidad):
                TipStok = "#,##0";
            break;
        }

        TxtF_CanProd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(TipStok))));
    }

    private LogN_ClassAb_Movimiento CrearMov(){
        LogN_ClassAb_Movimiento ObjMov;
        String DesOr, Autoriso, Detalle;
        DesOr = Txt_DesOrigen.getText();
        Autoriso = Txt_Autoriso.getText();
        Detalle = TxtA_Detalle.getText();
        Number CanProd = (Number) TxtF_CanProd.getValue();
        int NumMov = Integer.parseInt(Lbl_NumMov.getText());

        if (Rd_Entrada.isSelected())ObjMov = new  Dom_Class_MovEntrada(mObjPersonaCom, DesOr, Autoriso, Detalle, CanProd.floatValue(), NumMov);
        else ObjMov = new  Dom_Class_MovSalida(mObjPersonaCom, DesOr, Autoriso, Detalle, CanProd.floatValue(), NumMov);

        return ObjMov;
    }
    
    private void doClose(int retStatus) {

        if (retStatus == FrmDi_Movimiento.RET_OK){
            
            
            mObjMov = CrearMov();
            try {
                mObjMov.validar();
                mAutorisa = Txt_Autoriso.getText();
                mAsunto = Txt_DesOrigen. getText();
                mDetalle = TxtA_Detalle.getText();
                
            } catch (InputException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                return;
            }
        }
        returnStatus = retStatus;
        setVisible(false);
        
        dispose();
    }

    public LogN_ClassAb_Movimiento getMov(){
        return mObjMov;
    }
}
