/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frm_IntAgregar.java
 *
 * Created on 10/11/2010, 09:53:40 AM
 */

package Precentacion;

import Precentacion.Model.jTabel.ModeljTabNotificacion;
import Logica_Negocio.Dominio.Dom_Class_Categoria;
import Logica_Negocio.Dominio.Dom_Class_IVA;
import Logica_Negocio.Dominio.Dom_Class_Notificacion;
import Logica_Negocio.Dominio.Dom_Class_ProductoComp;
import Logica_Negocio.LogN_ClassAb_Movimiento;
import Logica_Negocio.LogN_Class_Fachada;
import Logica_Negocio.LogN_Class_ObsevadoAuxiliar;
import Logica_Negocio.MiExepcion.InputException;
import java.awt.Color;
import java.awt.Window;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;


/**
 *
 * @author ary
 */
public abstract class FrmIn_AgProducto extends javax.swing.JInternalFrame {
    private Window mObjFrmCon;
    protected LogN_Class_Fachada mObjFachada = LogN_Class_Fachada.getInstancia();
    protected LogN_ClassAb_Movimiento mObjMov = null;

    protected LogN_Class_ObsevadoAuxiliar  mObjObservado =
            new LogN_Class_ObsevadoAuxiliar<FrmIn_AgProducto>(this);

 
    
    protected PersonalComboBoxMedel <Dom_Class_Categoria> mObjCat;

    protected ModeljTabNotificacion mObjMNottificacion;
    



    /** Creates new form Frm_IntAgregar */
    public FrmIn_AgProducto(Window mObjFrmCon, String Titulo) {
        try{
             mObjCat = new PersonalComboBoxMedel<Dom_Class_Categoria>(
                mObjFachada.listarCat(),PersonalComboBoxMedel.Alfabet_Acendente
                , null, null) {
                    @Override
                    public boolean ComClassIn(Object o) {
                        return (o instanceof Dom_Class_Categoria);
                    }
                };
        }catch (InputException ex){
            
        }
       
        initComponents();
        this.setTitle(Titulo);
        mObjFachada.addObservadorCategoria(mObjCat);
        this.limpiarProdCom();
        this.TipMed(0);
        this.ComB_ConIVA.setModel(new DefaultComboBoxModel(new Vector<Dom_Class_IVA>(mObjFachada.listarIVA())));
        this.mObjFrmCon = mObjFrmCon;
        

        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        TabP_Opciones = new javax.swing.JTabbedPane();
        Pan_Prod = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtA_Des1 = new javax.swing.JTextArea();
        ComBAu_Categoria = new com.jidesoft.swing.AutoCompletionComboBox(mObjCat);
        Lbl_Cod = new javax.swing.JLabel();
        Lbl_CodBar = new javax.swing.JLabel();
        TxtF_CodBarr = new Utilidades.JFormattedText();
        Lbl_CodIn = new javax.swing.JLabel();
        Txt_Nom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Lbl_Categoria = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Btn_Lim = new javax.swing.JButton();
        Btn_Aceptar = new javax.swing.JButton();
        Che_SubP = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        TxtF_PreCos = new Utilidades.JFormattedText();
        jLabel5 = new javax.swing.JLabel();
        TxtF_PreVen = new Utilidades.JFormattedText();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ComB_TipMed = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        Btn_AgStok = new javax.swing.JButton();
        TxtF_StokMin = new Utilidades.JFormattedText();
        jPanel3 = new javax.swing.JPanel();
        TxtF_Ganancia = new javax.swing.JFormattedTextField();
        Che_Ganancia = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        ComB_ConIVA = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        Pan_Not = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tab_Not = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        Lbl_Cod1 = new javax.swing.JLabel();
        Txt_NotNom = new javax.swing.JTextField();
        Lbl_Cod2 = new javax.swing.JLabel();
        Cal_NotFech = new com.toedter.calendar.JDateChooser(new Date());
        Lbl_Cod3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TxtA_NotDetalle = new javax.swing.JTextPane();
        Btn_NotBaja = new javax.swing.JButton();
        Btn_NotCancelar = new javax.swing.JButton();
        Btn_NotAgregar = new javax.swing.JButton();

        setTitle("HOla");

        TabP_Opciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Pan_Prod.setRequestFocusEnabled(false);
        Pan_Prod.setVerifyInputWhenFocusTarget(false);

        jLabel3.setBackground(new java.awt.Color(13, 151, 239));
        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Descripción");
        jLabel3.setOpaque(true);

        jScrollPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane1KeyPressed(evt);
            }
        });

        TxtA_Des1.setColumns(20);
        TxtA_Des1.setTabSize(0);
        TxtA_Des1.setWrapStyleWord(true);
        TxtA_Des1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtA_Des1FocusGained(evt);
            }
        });
        TxtA_Des1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtA_Des1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TxtA_Des1);

        ComBAu_Categoria.setStrict(false);
        ComBAu_Categoria.setVerifyInputWhenFocusTarget(false);
        ComBAu_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComBAu_CategoriaActionPerformed(evt);
            }
        });

        Lbl_Cod.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_Cod.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Lbl_Cod.setForeground(new java.awt.Color(254, 254, 254));
        Lbl_Cod.setText("Codigo");
        Lbl_Cod.setOpaque(true);

        Lbl_CodBar.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_CodBar.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Lbl_CodBar.setForeground(new java.awt.Color(254, 254, 254));
        Lbl_CodBar.setText("Codigo de Barra");
        Lbl_CodBar.setOpaque(true);

        TxtF_CodBarr.setFormatterFactory(null);
        TxtF_CodBarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtF_CodBarrActionPerformed(evt);
            }
        });
        TxtF_CodBarr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtF_CodBarrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_CodBarrFocusLost(evt);
            }
        });

        Lbl_CodIn.setBackground(new java.awt.Color(255, 206, 0));
        Lbl_CodIn.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Lbl_CodIn.setForeground(new java.awt.Color(254, 254, 254));
        Lbl_CodIn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Lbl_CodIn.setText("0");
        Lbl_CodIn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        Lbl_CodIn.setOpaque(true);

        Txt_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NomActionPerformed(evt);
            }
        });
        Txt_Nom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Txt_NomFocusGained(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(13, 151, 239));
        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Nombre");
        jLabel2.setOpaque(true);

        Lbl_Categoria.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_Categoria.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Lbl_Categoria.setForeground(new java.awt.Color(254, 254, 254));
        Lbl_Categoria.setText("Categoría");
        Lbl_Categoria.setOpaque(true);
        Lbl_Categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lbl_CategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lbl_CategoriaMouseExited(evt);
            }
        });

        Btn_Lim.setText("Limpiar");
        Btn_Lim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimActionPerformed(evt);
            }
        });

        Btn_Aceptar.setText("Ingresar");
        Btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AceptarActionPerformed(evt);
            }
        });

        Che_SubP.setBackground(new java.awt.Color(13, 151, 239));
        Che_SubP.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Che_SubP.setForeground(new java.awt.Color(254, 254, 254));
        Che_SubP.setText("Agregar Subproductos");
        Che_SubP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Che_SubPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Che_SubP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Btn_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Lim, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Lim, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(Btn_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Che_SubP)
                .addContainerGap())
        );

        TxtF_PreCos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        TxtF_PreCos.setValue(new Float(0.0));
        TxtF_PreCos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_PreCosFocusLost(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(13, 151, 239));
        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Insumo");
        jLabel5.setOpaque(true);

        TxtF_PreVen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        TxtF_PreVen.setValue(new Float(0.0));
        TxtF_PreVen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_PreVenFocusLost(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(13, 151, 239));
        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Pre. Venta");
        jLabel6.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(13, 151, 239));
        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Stock Min.");
        jLabel8.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(13, 151, 239));
        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Stock ");
        jLabel9.setOpaque(true);

        jPanel6.setBackground(new java.awt.Color(13, 151, 239));

        ComB_TipMed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Unidad", "Desimo", "Sin Stok" }));
        ComB_TipMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComB_TipMedActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(13, 151, 239));
        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Tip. Medida");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(ComB_TipMed, 0, 1, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ComB_TipMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Btn_AgStok.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        Btn_AgStok.setForeground(new java.awt.Color(255, 38, 0));
        Btn_AgStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_db_add.png"))); // NOI18N
        Btn_AgStok.setText("0");
        Btn_AgStok.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Btn_AgStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgStokActionPerformed(evt);
            }
        });

        TxtF_StokMin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.000"))));
        TxtF_StokMin.setValue(new Float(0.0));
        TxtF_StokMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtF_StokMinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_StokMinFocusLost(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(13, 151, 239));

        TxtF_Ganancia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        TxtF_Ganancia.setEnabled(false);
        TxtF_Ganancia.setFocusable(false);
        TxtF_Ganancia.setValue(new Float(0.0));
        TxtF_Ganancia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_GananciaFocusLost(evt);
            }
        });

        Che_Ganancia.setBackground(new java.awt.Color(13, 151, 239));
        Che_Ganancia.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Che_Ganancia.setForeground(new java.awt.Color(254, 254, 254));
        Che_Ganancia.setText(" % Ganancia:");
        Che_Ganancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Che_GananciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(Che_Ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtF_Ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(TxtF_Ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Che_Ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.setBackground(new java.awt.Color(13, 151, 239));

        ComB_ConIVA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        ComB_ConIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComB_ConIVAActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(13, 151, 239));
        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("Condición IVA:");
        jLabel12.setOpaque(true);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComB_ConIVA, 0, 143, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ComB_ConIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(TxtF_StokMin)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtF_PreCos, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_AgStok, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtF_PreVen)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtF_StokMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(7, 7, 7)
                        .addComponent(TxtF_PreCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_AgStok, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(TxtF_PreVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lbl_CodIn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComBAu_Categoria, 0, 0, Short.MAX_VALUE)
                            .addComponent(Lbl_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_CodBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtF_CodBarr)
                            .addComponent(Txt_Nom)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_CodBar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtF_CodBarr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_Cod)
                            .addComponent(Lbl_Categoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbl_CodIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComBAu_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Pan_ProdLayout = new javax.swing.GroupLayout(Pan_Prod);
        Pan_Prod.setLayout(Pan_ProdLayout);
        Pan_ProdLayout.setHorizontalGroup(
            Pan_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_ProdLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pan_ProdLayout.setVerticalGroup(
            Pan_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_ProdLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        TabP_Opciones.addTab("Datos", Pan_Prod);

        Tab_Not.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Detalle", "Fecha"
            }
        ));
        jScrollPane2.setViewportView(Tab_Not);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alta Notificacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        Lbl_Cod1.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_Cod1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Lbl_Cod1.setForeground(new java.awt.Color(254, 254, 254));
        Lbl_Cod1.setText("Nombre");
        Lbl_Cod1.setOpaque(true);

        Txt_NotNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NotNomActionPerformed(evt);
            }
        });

        Lbl_Cod2.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_Cod2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Lbl_Cod2.setForeground(new java.awt.Color(254, 254, 254));
        Lbl_Cod2.setText("Fecha");
        Lbl_Cod2.setOpaque(true);

        Lbl_Cod3.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_Cod3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Lbl_Cod3.setForeground(new java.awt.Color(254, 254, 254));
        Lbl_Cod3.setText("Detalle");
        Lbl_Cod3.setOpaque(true);

        TxtA_NotDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtA_NotDetalleKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(TxtA_NotDetalle);

        Btn_NotBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_db_remove.png"))); // NOI18N
        Btn_NotBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NotBajaActionPerformed(evt);
            }
        });

        Btn_NotCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_editdelete.png"))); // NOI18N
        Btn_NotCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NotCancelarActionPerformed(evt);
            }
        });

        Btn_NotAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_db_add.png"))); // NOI18N
        Btn_NotAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NotAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(Btn_NotBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_NotCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(Btn_NotAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Lbl_Cod1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(Txt_NotNom, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(Lbl_Cod2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(Cal_NotFech, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(Lbl_Cod3, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(Lbl_Cod1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_NotNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_Cod2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cal_NotFech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_Cod3)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_NotBaja)
                    .addComponent(Btn_NotAgregar)
                    .addComponent(Btn_NotCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Pan_NotLayout = new javax.swing.GroupLayout(Pan_Not);
        Pan_Not.setLayout(Pan_NotLayout);
        Pan_NotLayout.setHorizontalGroup(
            Pan_NotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pan_NotLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Pan_NotLayout.setVerticalGroup(
            Pan_NotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_NotLayout.createSequentialGroup()
                .addGroup(Pan_NotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, 0, 330, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        TabP_Opciones.addTab("Nota", Pan_Not);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabP_Opciones)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabP_Opciones, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NomActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NomActionPerformed

    private void Btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AceptarActionPerformed
        // TODO add your handling code here:
        aceptar();
    }//GEN-LAST:event_Btn_AceptarActionPerformed

    private void Lbl_CategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_CategoriaMouseEntered

        // TODO add your handling code here:
        // TODO add your handling code here:
        Lbl_Categoria.setText("Modificar");

        Lbl_Categoria.setBackground(new java.awt.Color(155, 197, 214));
        Lbl_Categoria.setForeground(Color.WHITE);
        Lbl_Categoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);// centra el testo

    }//GEN-LAST:event_Lbl_CategoriaMouseEntered

    private void Lbl_CategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_CategoriaMouseExited
        // TODO add your handling code here:
        Lbl_Categoria.setText("Categoria");
        Lbl_Categoria.setBackground(Lbl_Cod.getBackground());
        Lbl_Categoria.setForeground(Lbl_Cod.getForeground());
        Lbl_Categoria.setHorizontalAlignment(Lbl_Cod.getHorizontalAlignment());
    }//GEN-LAST:event_Lbl_CategoriaMouseExited

    private void ComBAu_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComBAu_CategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComBAu_CategoriaActionPerformed

    private void Btn_LimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimActionPerformed
        // TODO add your handling code here:
        limpiarProdCom();
    }//GEN-LAST:event_Btn_LimActionPerformed

    private void TxtA_Des1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtA_Des1KeyPressed
        // TODO add your handling code here:
        if ( evt.getKeyChar() == java.awt.event.KeyEvent.VK_TAB)TxtF_CodBarr.requestFocus();
    }//GEN-LAST:event_TxtA_Des1KeyPressed

    private void jScrollPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1KeyPressed

    private void Txt_NomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_NomFocusGained
        // TODO add your handling code here:
        Txt_Nom.selectAll();
    }//GEN-LAST:event_Txt_NomFocusGained

    private void TxtA_Des1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtA_Des1FocusGained
        // TODO add your handling code here:
        TxtA_Des1.selectAll();
    }//GEN-LAST:event_TxtA_Des1FocusGained

    private void TxtF_CodBarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtF_CodBarrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_CodBarrActionPerformed

    private void ComB_TipMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComB_TipMedActionPerformed
        // TODO add your handling code here:
        TipMed(ComB_TipMed.getSelectedIndex());

    }//GEN-LAST:event_ComB_TipMedActionPerformed

    private void Btn_AgStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgStokActionPerformed
        // TODO add your handling code here:
        this.AltaMov();
    }//GEN-LAST:event_Btn_AgStokActionPerformed

    private void TxtA_NotDetalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtA_NotDetalleKeyPressed
        // TODO add your handling code here:
        if ( evt.getKeyChar() == java.awt.event.KeyEvent.VK_TAB)Btn_NotAgregar.requestFocus();
}//GEN-LAST:event_TxtA_NotDetalleKeyPressed

    private void Txt_NotNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NotNomActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Txt_NotNomActionPerformed

    private void Btn_NotAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NotAgregarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Btn_NotAgregarActionPerformed

    private void Btn_NotBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NotBajaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Btn_NotBajaActionPerformed

    private void Btn_NotCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NotCancelarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Btn_NotCancelarActionPerformed

    private void TxtF_StokMinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_StokMinFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_StokMinFocusGained

    private void TxtF_StokMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_StokMinFocusLost
        TxtF_StokMin.setText(TxtF_StokMin.getText().replace(".", ","));
    }//GEN-LAST:event_TxtF_StokMinFocusLost

    private void TxtF_PreCosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_PreCosFocusLost
        // TODO add your handling code here:
        String Txt =  TxtF_PreCos.getText().replace(".", ",").trim();
        TxtF_PreCos.setText(Txt);
        Txt = Txt.replace(",", ".");
        float Insumo, PreVenta;
        
        try{
             Insumo = Float.parseFloat(Txt);
        }catch (NumberFormatException ex){
            return ;
        }
       
        PreVenta = ((Number) TxtF_PreVen.getValue()).floatValue();
        float ganancia = calProGan(Insumo, PreVenta);
        
        TxtF_Ganancia.setValue(new Float(ganancia));
    }//GEN-LAST:event_TxtF_PreCosFocusLost

    private void TxtF_PreVenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_PreVenFocusLost
        // TODO add your handling code here:
        String Txt =  TxtF_PreVen.getText().replace(".", ",").trim();
        TxtF_PreVen.setText(Txt);
        Txt = Txt.replace(",", ".");
        float Insumo, PreVenta;
        PreVenta = 0;
        try{
             PreVenta = Float.parseFloat(Txt);
        }catch (NumberFormatException ex){
            return ;
        }
        Insumo = ((Number) TxtF_PreCos.getValue()).floatValue();
        TxtF_Ganancia.setValue(new Float(calProGan(Insumo, PreVenta)));
    }//GEN-LAST:event_TxtF_PreVenFocusLost

    private void Che_SubPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Che_SubPActionPerformed
        // TODO add your handling code here:
        if (Che_SubP.isSelected()) Btn_Aceptar.requestFocus();
    }//GEN-LAST:event_Che_SubPActionPerformed

    private void TxtF_CodBarrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_CodBarrFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtF_CodBarrFocusGained

    private void TxtF_GananciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_GananciaFocusLost
                
        String Txt =  TxtF_Ganancia.getText().replace(".", ",").trim();
        TxtF_Ganancia.setText(Txt);
        Txt = Txt.replace(",", ".");
        float Insumo, PorGan;
        try{
             PorGan= Float.parseFloat(Txt);
        }catch (NumberFormatException ex){
            return ;
        }
        Insumo = ((Number) TxtF_PreCos.getValue()).floatValue();
        TxtF_PreVen.setValue(new Float(calPreVen(Insumo, PorGan)));
    }//GEN-LAST:event_TxtF_GananciaFocusLost

    private void Che_GananciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Che_GananciaActionPerformed
        // TODO add your handling code here:
        boolean Con = Che_Ganancia.isSelected();

            TxtF_Ganancia.setEnabled(Con);
            TxtF_Ganancia.setFocusable(Con);

    }//GEN-LAST:event_Che_GananciaActionPerformed

    private void ComB_ConIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComB_ConIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComB_ConIVAActionPerformed

    private void TxtF_CodBarrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_CodBarrFocusLost
        // TODO add your handling code here:
        int NumP = Integer.parseInt(Lbl_CodIn.getText());
        String CodBar = mObjFachada.existeCodBarProd(NumP, TxtF_CodBarr.getText());
        if (CodBar.equals(""))return;
        Lbl_CodBar.setText("Existe en Pro.: " + CodBar);
        Lbl_CodBar.setBackground(new java.awt.Color(255, 102, 102));
        
    }//GEN-LAST:event_TxtF_CodBarrFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Aceptar;
    protected javax.swing.JButton Btn_AgStok;
    public javax.swing.JButton Btn_Lim;
    private javax.swing.JButton Btn_NotAgregar;
    private javax.swing.JButton Btn_NotBaja;
    private javax.swing.JButton Btn_NotCancelar;
    private com.toedter.calendar.JDateChooser Cal_NotFech;
    protected javax.swing.JCheckBox Che_Ganancia;
    public javax.swing.JCheckBox Che_SubP;
    protected com.jidesoft.swing.AutoCompletionComboBox ComBAu_Categoria;
    protected javax.swing.JComboBox ComB_ConIVA;
    protected javax.swing.JComboBox ComB_TipMed;
    private javax.swing.JLabel Lbl_Categoria;
    private javax.swing.JLabel Lbl_Cod;
    private javax.swing.JLabel Lbl_Cod1;
    private javax.swing.JLabel Lbl_Cod2;
    private javax.swing.JLabel Lbl_Cod3;
    private javax.swing.JLabel Lbl_CodBar;
    protected javax.swing.JLabel Lbl_CodIn;
    private javax.swing.JPanel Pan_Not;
    private javax.swing.JPanel Pan_Prod;
    protected javax.swing.JTabbedPane TabP_Opciones;
    private javax.swing.JTable Tab_Not;
    protected javax.swing.JTextArea TxtA_Des1;
    private javax.swing.JTextPane TxtA_NotDetalle;
    protected javax.swing.JFormattedTextField TxtF_CodBarr;
    private javax.swing.JFormattedTextField TxtF_Ganancia;
    protected javax.swing.JFormattedTextField TxtF_PreCos;
    protected javax.swing.JFormattedTextField TxtF_PreVen;
    protected javax.swing.JFormattedTextField TxtF_StokMin;
    protected javax.swing.JTextField Txt_Nom;
    private javax.swing.JTextField Txt_NotNom;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    
    // Metodos ProdCom**********************************************************
    protected abstract boolean aceptar ();

    protected  void limpiarProdCom (){
        Lbl_CodBar.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_CodBar.setText("Codigo de Barra");
    }

    protected void eliminarMovimiento (){
        Btn_AgStok.setText("" + 0);
        mObjMov = null;
    }

    private void TipMed (int xVal){
        String TextTMoel = "#,##0.000";
        if (xVal == 0) TextTMoel = "#,##0";

        TxtF_StokMin.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new java.text.DecimalFormat(TextTMoel))));
        eliminarMovimiento();
    }
    //Metodo SubProducto********************************************************

    protected Dom_Class_ProductoComp SubProd (Dom_Class_ProductoComp xObjProd) throws InputException{

        if (!Che_SubP.isSelected()) return xObjProd;
        xObjProd.validar();

        Dom_Class_ProductoComp ObjProdC = new Dom_Class_ProductoComp(xObjProd);
        FrmDi_AgregarSubProd ObjFrmSub = new FrmDi_AgregarSubProd(mObjFrmCon, ObjProdC);
        ObjFrmSub.setVisible(true);

        if (ObjFrmSub.getReturnStatus() == FrmDi_AgregarSubProd.RET_OK) xObjProd = ObjFrmSub.getProducto();
        
        return xObjProd;

    }

    //Metodos Notificacion******************************************************

    private void limNot (){
        Txt_NotNom.setText("");
        TxtA_NotDetalle.setText("");
    }
    
    protected void cargarNotific (){
        mObjObservado.deleteObserver(mObjMNottificacion);
        mObjMNottificacion = new ModeljTabNotificacion(new ArrayList<Dom_Class_Notificacion>());
        mObjObservado.addObserver(mObjMNottificacion);
        Tab_Not.setModel(mObjMNottificacion);
    }
    
    private void agregarNot(){
        Dom_Class_Notificacion xObjNot = getNotifica();
        try {
            xObjNot.validar();
            mObjObservado.Notifiar(new LogN_Class_Accion<Dom_Class_Notificacion>(LogN_Class_Accion.Agreger,xObjNot));
            this.limNot();
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }

    }
    
    private void bajaNot (Dom_Class_Notificacion xObjNot){
        if (xObjNot == null) JOptionPane.showMessageDialog(this, "No selexiono ninguna Notificacion a dar de baja");
        mObjObservado.Notifiar(new LogN_Class_Accion<Dom_Class_Notificacion>(LogN_Class_Accion.Eliminar,xObjNot));
    }
    
    private Dom_Class_Notificacion getNotifica(){
        return new Dom_Class_Notificacion(Txt_NotNom.getText(), TxtA_NotDetalle.getText(), Cal_NotFech.getDate());
    }

    public Dom_Class_ProductoComp getProductoCom () throws InputException {
         Dom_Class_Categoria ObjCat = null;
         Dom_Class_IVA ObjIva = (Dom_Class_IVA) ComB_ConIVA.getSelectedItem();
         try {
             ObjCat = mObjFachada.RetornarOCrearCategoria(ComBAu_Categoria.getSelectedItem().toString());
        } catch (InputException ex) {
            throw  new InputException (ex.getLocalizedMessage());
        }catch (NullPointerException ex2){
            throw new InputException ("No se pudo crear la categoria");
        }

        int CodProd = Integer.parseInt(Lbl_CodIn.getText());


        Number PreCos = (Number) TxtF_PreCos.getValue();
        Number PreVen = (Number) TxtF_PreVen.getValue();
        Number StokMin = (Number) TxtF_StokMin.getValue();
        

        return new Dom_Class_ProductoComp(CodProd,Txt_Nom.getText(),TxtA_Des1.getText(),
                    TxtF_CodBarr.getText(), PreCos.floatValue(), PreVen.floatValue(),
                StokMin.floatValue(),ObjCat,ComB_TipMed.getSelectedIndex(),
                ObjIva);
    }
//Metodos Movimiento****************************************************************
    private void AltaMov() {
        try {
            Dom_Class_ProductoComp ObjProdC = this.getProductoCom();
            FrmDi_Movimiento ObjFrmMov = new FrmDi_Movimiento(mObjFrmCon, ObjProdC.generarMovimiento("", "", "", 0, true));
            ObjFrmMov.setVisible(true);
            if (ObjFrmMov.getReturnStatus() == FrmDi_Movimiento.RET_OK){
                mObjMov = ObjFrmMov.getMov();
                Btn_AgStok.setText("" + mObjMov.getCanProd());
            }
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }
    }
    
    public float calProGan (float xInsumo, float xPreVen){
        if (xInsumo == 0 || xPreVen == 0) return 0;
        return (xPreVen/xInsumo - 1)*100;
    }
    
    public float calPreVen (float xInsum, float xPrsGan){
        
        return xInsum*(xPrsGan/100+1);
    }
    
    







}
