/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frm_Prinsipal.java
 *
 * Created on 10/11/2010, 09:41:02 AM
 */

package Precentacion;

import Logica_Negocio.MiExepcion.InputException;
import Precentacion.Model.jList.PersonalListModelProd;
import Precentacion.Model.jList.PersonalListModel;
import Logica_Negocio.LogN_Class_Fachada;
import java.beans.PropertyVetoException;
import java.security.Principal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ary
 */
public class Frm_Producto extends javax.swing.JFrame {
    private FrmIn_AgProducto mObjFrmIn_Agregar = new FrmIn_AgrProd(this);
    private FrmIn_ListarProducto mObjFrmIn_Listar= new FrmIn_ListarProducto(this);
    private PersonalListModelProd xObjP;
    private LogN_Class_Fachada mObjFachada = LogN_Class_Fachada.getInstancia();

    /** Creates new form Frm_Prinsipal */
    public Frm_Producto() {
         

        initComponents();
        this.InisFor(mObjFrmIn_Listar);
        this.InisFor(mObjFrmIn_Agregar);
        
        try {
            xObjP = new PersonalListModelProd(mObjFachada.listarProStokMin(), PersonalListModel.Alfabet_Acendente, null);
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }

        mObjFachada.addObservadorProducto(xObjP);
        mObjFachada.addObservadorMovimiento(xObjP);
        Lis_ProdStokM.setModel(xObjP);
       

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        DexP_Prin = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lis_ProdStokM = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        Btn2P_Insertar = new javax.swing.JToggleButton();
        Btn2P_Listar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Productos");

        jLabel1.setBackground(new java.awt.Color(13, 151, 239));
        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Stock Minimo");
        jLabel1.setOpaque(true);

        jScrollPane1.setViewportView(Lis_ProdStokM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
        );

        buttonGroup1.add(Btn2P_Insertar);
        Btn2P_Insertar.setSelected(true);
        Btn2P_Insertar.setText("Ingresar");
        Btn2P_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2P_InsertarActionPerformed(evt);
            }
        });

        buttonGroup1.add(Btn2P_Listar);
        Btn2P_Listar.setText("Listar");
        Btn2P_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2P_ListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Btn2P_Listar, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
            .addComponent(Btn2P_Insertar, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Btn2P_Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(Btn2P_Listar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DexP_Prin, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(DexP_Prin, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn2P_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2P_ListarActionPerformed
        // TODO add your handling code here:
        mObjFrmIn_Listar.moveToFront();
    }//GEN-LAST:event_Btn2P_ListarActionPerformed

    private void Btn2P_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2P_InsertarActionPerformed
        // TODO add your handling code here:
        mObjFrmIn_Agregar.moveToFront();
    }//GEN-LAST:event_Btn2P_InsertarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Btn2P_Insertar;
    private javax.swing.JToggleButton Btn2P_Listar;
    private javax.swing.JDesktopPane DexP_Prin;
    private javax.swing.JList Lis_ProdStokM;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

     private void InisFor (JInternalFrame Frm){

        Frm.setVisible(true);

        DexP_Prin.add(Frm);
        Frm.moveToFront(); // mueve acia delate el Formulario

        try {
            Frm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
