/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmDi_AgregarSubProd.java
 *
 * Created on 20/03/2011, 05:14:44 PM
 */

package Precentacion;

import Logica_Negocio.Dominio.Dom_Class_ProductoComp;
import Logica_Negocio.Dominio.Dom_Class_SubProducto;
import Logica_Negocio.MiExepcion.InputException;
import Precentacion.Model.jTabel.ModeljTabSubProd;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author ary
 */
public class FrmDi_AgregarSubProd extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    private int returnStatus = RET_CANCEL;

    private Dom_Class_ProductoComp mObjProd;

    private ModeljTabSubProd mObjMSubProd;

    private Dom_Class_SubProducto mObjSubPSel;

    private boolean mModDetalle = false;

    /** Creates new form FrmDi_AgregarSubProd */
    public FrmDi_AgregarSubProd(java.awt.Window parent, Dom_Class_ProductoComp mObjPord) {
        super(parent, java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        mObjMSubProd = new ModeljTabSubProd(mObjPord.getmColSubProd(), ModeljTabSubProd.OrdenarPorCodAcen);
        this.mObjProd = mObjPord;
        initComponents();
        this.limSubP();
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        Pan_SubP = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tab_SubP = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TxtA_SubPMosDetalle = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        TxtF_SubCodBarr = new javax.swing.JFormattedTextField();
        Txt_SubPNom = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Lbl_Cod4 = new javax.swing.JLabel();
        Lbl_SubPCod = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtA_SubPDetalle = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        TxtF_SubPPreVen = new Utilidades.JFormattedText();
        Btn_SubPAgregar = new javax.swing.JButton();
        Btn_SubPCancelar = new javax.swing.JButton();
        Btn_SubPBaja = new javax.swing.JButton();
        Che_CodBarr = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        TxtF_Unidad = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Yes v3.png"))); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel_f2.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        Tab_SubP.setModel(mObjMSubProd);
        Tab_SubP.getSelectionModel().addListSelectionListener(
            new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    Tab_SubPValueChanged(event);
                }
            }
        );
        jScrollPane5.setViewportView(Tab_SubP);

        jLabel13.setBackground(new java.awt.Color(13, 151, 239));
        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(254, 254, 254));
        jLabel13.setText("Descripción");
        jLabel13.setOpaque(true);

        TxtA_SubPMosDetalle.setColumns(20);
        TxtA_SubPMosDetalle.setRows(5);
        TxtA_SubPMosDetalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtA_SubPMosDetalleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtA_SubPMosDetalleFocusLost(evt);
            }
        });
        TxtA_SubPMosDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtA_SubPMosDetalleKeyPressed(evt);
            }
        });
        TxtA_SubPMosDetalle.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                TxtA_SubPMosDetalleVetoableChange(evt);
            }
        });
        jScrollPane6.setViewportView(TxtA_SubPMosDetalle);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        TxtF_SubCodBarr.setEditable(false);
        TxtF_SubCodBarr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        TxtF_SubCodBarr.setFocusable(false);
        TxtF_SubCodBarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtF_SubCodBarrActionPerformed(evt);
            }
        });

        Txt_SubPNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_SubPNomActionPerformed(evt);
            }
        });
        Txt_SubPNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Txt_SubPNomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_SubPNomFocusLost(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(13, 151, 239));
        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("Nombre");
        jLabel12.setOpaque(true);

        Lbl_Cod4.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_Cod4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Lbl_Cod4.setForeground(new java.awt.Color(254, 254, 254));
        Lbl_Cod4.setText("Codigo");
        Lbl_Cod4.setOpaque(true);

        Lbl_SubPCod.setBackground(new java.awt.Color(255, 206, 0));
        Lbl_SubPCod.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Lbl_SubPCod.setForeground(new java.awt.Color(254, 254, 254));
        Lbl_SubPCod.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Lbl_SubPCod.setText("0");
        Lbl_SubPCod.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        Lbl_SubPCod.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(13, 151, 239));
        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Descripción");
        jLabel7.setOpaque(true);

        TxtA_SubPDetalle.setColumns(20);
        TxtA_SubPDetalle.setRows(5);
        TxtA_SubPDetalle.setTabSize(0);
        TxtA_SubPDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtA_SubPDetalleKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(TxtA_SubPDetalle);

        jLabel14.setBackground(new java.awt.Color(13, 151, 239));
        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setText("Pre. Venta");
        jLabel14.setOpaque(true);

        TxtF_SubPPreVen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.##"))));
        TxtF_SubPPreVen.setValue(new Float(0.0));
        TxtF_SubPPreVen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtF_SubPPreVenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_SubPPreVenFocusLost(evt);
            }
        });

        Btn_SubPAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_db_add.png"))); // NOI18N
        Btn_SubPAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SubPAgregarActionPerformed(evt);
            }
        });

        Btn_SubPCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_editdelete.png"))); // NOI18N
        Btn_SubPCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SubPCancelarActionPerformed(evt);
            }
        });

        Btn_SubPBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_db_remove.png"))); // NOI18N
        Btn_SubPBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SubPBajaActionPerformed(evt);
            }
        });

        Che_CodBarr.setBackground(new java.awt.Color(13, 151, 239));
        Che_CodBarr.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        Che_CodBarr.setForeground(new java.awt.Color(254, 254, 254));
        Che_CodBarr.setText("Codigo Barra");
        Che_CodBarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Che_CodBarrActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(13, 151, 239));
        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(254, 254, 254));
        jLabel15.setText("Unidad");
        jLabel15.setOpaque(true);

        TxtF_Unidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TxtF_Unidad.setToolTipText("");
        TxtF_Unidad.setValue(1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lbl_Cod4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Lbl_SubPCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Txt_SubPNom)
            .addComponent(TxtF_SubPPreVen)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TxtF_SubCodBarr)
            .addComponent(Che_CodBarr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Btn_SubPAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_SubPCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_SubPBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TxtF_Unidad)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(Lbl_Cod4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_SubPCod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_SubPNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtF_Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(Che_CodBarr, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtF_SubCodBarr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtF_SubPPreVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_SubPCancelar)
                    .addComponent(Btn_SubPAgregar)
                    .addComponent(Btn_SubPBaja)))
        );

        javax.swing.GroupLayout Pan_SubPLayout = new javax.swing.GroupLayout(Pan_SubP);
        Pan_SubP.setLayout(Pan_SubPLayout);
        Pan_SubPLayout.setHorizontalGroup(
            Pan_SubPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_SubPLayout.createSequentialGroup()
                .addGroup(Pan_SubPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pan_SubPLayout.setVerticalGroup(
            Pan_SubPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_SubPLayout.createSequentialGroup()
                .addGroup(Pan_SubPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pan_SubPLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pan_SubP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pan_SubP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okButton)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void TxtF_SubCodBarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtF_SubCodBarrActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TxtF_SubCodBarrActionPerformed

    private void Txt_SubPNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_SubPNomActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Txt_SubPNomActionPerformed

    private void Txt_SubPNomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_SubPNomFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_Txt_SubPNomFocusGained

    private void TxtF_SubPPreVenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_SubPPreVenFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_TxtF_SubPPreVenFocusGained

    private void Btn_SubPCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SubPCancelarActionPerformed
        // TODO add your handling code here:
        limSubP();
}//GEN-LAST:event_Btn_SubPCancelarActionPerformed

    private void Btn_SubPBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SubPBajaActionPerformed
        // TODO add your handling code here:
        bajaSubP();
}//GEN-LAST:event_Btn_SubPBajaActionPerformed

    private void Btn_SubPAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SubPAgregarActionPerformed
        // TODO add your handling code here:
        this.AltaSubProd();
}//GEN-LAST:event_Btn_SubPAgregarActionPerformed

    private void TxtA_SubPDetalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtA_SubPDetalleKeyPressed
        // TODO add your handling code here:
         if ( evt.getKeyChar() == java.awt.event.KeyEvent.VK_TAB)TxtF_SubPPreVen.requestFocus();
    }//GEN-LAST:event_TxtA_SubPDetalleKeyPressed

    private void Che_CodBarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Che_CodBarrActionPerformed
        // TODO add your handling code here
        boolean Con  = Che_CodBarr.isSelected();
        TxtF_SubCodBarr.setEditable(Con);
        TxtF_SubCodBarr.setFocusable(Con);
    }//GEN-LAST:event_Che_CodBarrActionPerformed

    private void TxtA_SubPMosDetalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtA_SubPMosDetalleFocusLost
        // TODO add your handling code here:
        this.modificarDetalle();

    }//GEN-LAST:event_TxtA_SubPMosDetalleFocusLost

    private void TxtA_SubPMosDetalleVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_TxtA_SubPMosDetalleVetoableChange
        // TODO add your handling code here:

    }//GEN-LAST:event_TxtA_SubPMosDetalleVetoableChange

    private void TxtA_SubPMosDetalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtA_SubPMosDetalleKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_TxtA_SubPMosDetalleKeyPressed

    private void TxtA_SubPMosDetalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtA_SubPMosDetalleFocusGained
        // TODO add your handling code here:
        this.mModDetalle = true;
    }//GEN-LAST:event_TxtA_SubPMosDetalleFocusGained

    private void Txt_SubPNomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_SubPNomFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_SubPNomFocusLost

    private void TxtF_SubPPreVenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_SubPPreVenFocusLost
        // TODO add your handling code here:
        TxtF_SubPPreVen.setText(TxtF_SubPPreVen.getText().replace(".", ","));
    }//GEN-LAST:event_TxtF_SubPPreVenFocusLost

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

//    /**
//    * @param args the command line arguments
//    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FrmDi_AgregarSubProd dialog = new FrmDi_AgregarSubProd(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_SubPAgregar;
    private javax.swing.JButton Btn_SubPBaja;
    private javax.swing.JButton Btn_SubPCancelar;
    private javax.swing.JCheckBox Che_CodBarr;
    private javax.swing.JLabel Lbl_Cod4;
    private javax.swing.JLabel Lbl_SubPCod;
    private javax.swing.JPanel Pan_SubP;
    private javax.swing.JTable Tab_SubP;
    private javax.swing.JTextArea TxtA_SubPDetalle;
    private javax.swing.JTextArea TxtA_SubPMosDetalle;
    private javax.swing.JFormattedTextField TxtF_SubCodBarr;
    private javax.swing.JFormattedTextField TxtF_SubPPreVen;
    private javax.swing.JFormattedTextField TxtF_Unidad;
    private javax.swing.JTextField Txt_SubPNom;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    

    private void modificarDetalle(){
        if (mModDetalle == false) return;

        String NuDet = TxtA_SubPMosDetalle.getText();
        if (mObjSubPSel == null ||
                (mObjSubPSel.getMProd_Desc().equals(NuDet)))
            return;

        mObjSubPSel.setMProd_Desc(NuDet);
        mModDetalle = false;
    }


     private void Tab_SubPValueChanged(ListSelectionEvent evt){
         try{
             modificarDetalle();
             mObjSubPSel = mObjMSubProd.getValue(Tab_SubP.getSelectedRow());
             TxtA_SubPMosDetalle.setText(mObjSubPSel.getMProd_Desc());
         } catch (NullPointerException nE){

         }

     }

     private void limSubP(){
        Lbl_SubPCod.setText("" + mObjProd.getNumSubProd());
        Txt_SubPNom.setText("");
        TxtF_SubCodBarr.setValue(0);
        TxtA_SubPDetalle.setText("");
        TxtF_SubPPreVen.setValue((float)0);

    }

    public Dom_Class_SubProducto getSubProd (){


        Float PreVen = ((Number)TxtF_SubPPreVen.getValue()).floatValue();
        String CodBarr = "";
        if (Che_CodBarr.isSelected()) CodBarr = TxtF_SubCodBarr.getText();
        Number Unidad = (Number) TxtF_Unidad.getValue();
        
        return new Dom_Class_SubProducto( mObjProd.getNumSubProd(), Txt_SubPNom.getText(),
                TxtA_SubPDetalle.getText(), CodBarr, PreVen, mObjProd , Unidad.floatValue());
        

    }





    public void AltaSubProd () {
        try {
            Dom_Class_SubProducto ObjSubProd = this.getSubProd();
            mObjProd.altaSubProd(ObjSubProd);
            mObjMSubProd.addRow(ObjSubProd);
            this.limSubP();
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }
    }

    private void bajaSubP(){
        if(!mObjProd.bajaSubProd(mObjSubPSel))JOptionPane.showMessageDialog(this, "No se puede dar de baja este articulo");
        mObjMSubProd.deleteRow(mObjSubPSel);
        mObjSubPSel = null;
        Lbl_SubPCod.setText("" + mObjProd.getNumSubProd());
    }

    public Dom_Class_ProductoComp getProducto(){
        return mObjProd;
    }
}
