/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pre_FrmDi_ForPago.java
 *
 * Created on 27/03/2010, 03:54:32 PM
 */

package Precentacion;

import Logica_Negocio.Dominio.Dom_Class_Saldo;
import Logica_Negocio.Dominio.FormaPago.Dom_Class_Contado;
import Logica_Negocio.Dominio.FormaPago.Dom_Class_Credito;
import Logica_Negocio.LogN_ClassAb_Factura;
import Logica_Negocio.LogN_ClassAb_Persona;
import Logica_Negocio.LogN_Inter_FormaPag;
import Logica_Negocio.MiExepcion.InputException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author Jhon
 */
public class FrmDi_ForPago extends javax.swing.JDialog {
	/**
	 * <b>Forma de pago cr�dito</b> que se va a  asignar a la factura (mObjFactura)
	 * siempre y cuando el
	 * usuario lo desee
	 */
    private Dom_Class_Credito mObjCred;
	/**
	 * Factura a la cual se la va a asignar la forma de pago deseada 
	 */
    private LogN_ClassAb_Factura mObjFac;
	/**
	 * Forma de pago contado que se va a  asignar a la factura (mObjFactura) siempre y
	 * cuando el
	 * usuario lo desee
	 */
    private Dom_Class_Contado mObjCont;
    
	/**
	 * <b>Especifica la forma que se van a mostrar los numero</b> Es decir 2 cero
	 * despu�s de la compa y con separador de miles
	 */
    private NumberFormat mNf = new DecimalFormat("#,##0.00");
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    /**
     * Monoto de la factura qeur resta pagar (que no se le a asignado forma de pago)
     */
    private float mMontoAPagar;
    
    private final float mMontoFactura;

    private static boolean mPres = false;

    private int returnStatus = RET_CANCEL;
    private float mCambioCli;





    /** Creates new form Pre_FrmDi_ForPago */
    public FrmDi_ForPago(java.awt.Window parent, LogN_ClassAb_Factura mObjFac ) {

        super(parent,java.awt.Dialog.ModalityType.APPLICATION_MODAL); //Yama al contsructor de el dealog para bloquear los formularios ijos        initComponents();
        initComponents();
        this.mObjFac = mObjFac;
        //Formato de fecha a mostrar en forma de pago
        SimpleDateFormat ObjFrD = new SimpleDateFormat("dd/MM/yyyy");
        this.Lbl_Fecha.setText(ObjFrD.format(mObjFac.getFech()));
        this.Dat_FechCre.setDate(mObjFac.getFech());
        
        this.mMontoAPagar = mObjFac.getTotFin();
        this.mMontoFactura = mMontoAPagar;
        //Inicialisa el contado con el monto a pagar
        float MotnoAPagar = mObjFac.getTotFin();
        mObjCont = new Dom_Class_Contado(MotnoAPagar);
        
        setMontoAPagar(mObjCont, Dom_Class_Contado.TIPO);
        Che_Pres.setSelected(mPres);
        
        this.carSaldo(mObjFac);
        super.setVisible(true);
    }

    public boolean getPresupuesto () {
        return mPres;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Btn_Cancelar1 = new javax.swing.JButton();
        Btn_Aceptar = new javax.swing.JButton();
        Che_Pres = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtF_Contado = new Utilidades.JFormattedText();
        jLabel4 = new javax.swing.JLabel();
        Lbl_Cambio = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Pan_Credito = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lis_Credito = new javax.swing.JList();
        Che_Credito = new javax.swing.JCheckBox();
        Btn_Credito = new javax.swing.JButton();
        Lbl_Saldo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Lbl_Cuota = new javax.swing.JLabel();
        TxtF_Credito = new Utilidades.JFormattedText();
        Dat_FechCre = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        Lbl_ValorAPagar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lbl_Fecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma de pago del cliente");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("FORMA DE PAGO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Btn_Cancelar1.setFont(new java.awt.Font("Arial Black", 1, 13));
        Btn_Cancelar1.setForeground(new java.awt.Color(1, 1, 1));
        Btn_Cancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel_f2.png"))); // NOI18N
        Btn_Cancelar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.gray, null, java.awt.Color.gray));
        Btn_Cancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cancelar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Cancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 64, -1));

        Btn_Aceptar.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Yes v3.png"))); // NOI18N
        Btn_Aceptar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.gray, null, java.awt.Color.gray));
        Btn_Aceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AceptarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 63, -1));

        Che_Pres.setBackground(new java.awt.Color(153, 153, 153));
        Che_Pres.setText("Presupuesto");
        Che_Pres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Che_PresActionPerformed(evt);
            }
        });
        jPanel1.add(Che_Pres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 123, 27));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Entrega Cliente:");

        TxtF_Contado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        TxtF_Contado.setValue(0);
        TxtF_Contado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtF_ContadoActionPerformed(evt);
            }
        });
        TxtF_Contado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_ContadoFocusLost(evt);
            }
        });
        TxtF_Contado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtF_ContadoKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Vuelto Cliente:");

        Lbl_Cambio.setBackground(new java.awt.Color(255, 153, 51));
        Lbl_Cambio.setFont(new java.awt.Font("Tahoma", 1, 14));
        Lbl_Cambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Cambio.setText("00");
        Lbl_Cambio.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(153, 153, 153));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/coins.png"))); // NOI18N
        jLabel14.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Lbl_Cambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtF_Contado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(TxtF_Contado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Lbl_Cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contado", jPanel3);

        Pan_Credito.setBackground(new java.awt.Color(153, 153, 153));

        Lis_Credito.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Sin Cuota" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Lis_Credito);

        Che_Credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Che_CreditoActionPerformed(evt);
            }
        });

        Btn_Credito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_Credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CreditoActionPerformed(evt);
            }
        });

        Lbl_Saldo.setBackground(new java.awt.Color(255, 153, 51));
        Lbl_Saldo.setFont(new java.awt.Font("Tahoma", 0, 12));
        Lbl_Saldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Saldo.setText("0,0");
        Lbl_Saldo.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Saldo:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Cuotas:");

        Lbl_Cuota.setBackground(new java.awt.Color(255, 153, 51));
        Lbl_Cuota.setFont(new java.awt.Font("Tahoma", 0, 12));
        Lbl_Cuota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Cuota.setText("0,0");
        Lbl_Cuota.setOpaque(true);

        TxtF_Credito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        TxtF_Credito.setValue(0);
        TxtF_Credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtF_CreditoActionPerformed(evt);
            }
        });
        TxtF_Credito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_CreditoFocusLost(evt);
            }
        });
        TxtF_Credito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtF_CreditoKeyPressed(evt);
            }
        });

        Dat_FechCre.setToolTipText("Fecha Inicial");
        Dat_FechCre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Dat_FechCre.setOpaque(false);

        javax.swing.GroupLayout Pan_CreditoLayout = new javax.swing.GroupLayout(Pan_Credito);
        Pan_Credito.setLayout(Pan_CreditoLayout);
        Pan_CreditoLayout.setHorizontalGroup(
            Pan_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_CreditoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pan_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pan_CreditoLayout.createSequentialGroup()
                        .addComponent(Che_Credito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtF_Credito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Dat_FechCre, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pan_CreditoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Cuota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Pan_CreditoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Credito, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Pan_CreditoLayout.setVerticalGroup(
            Pan_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_CreditoLayout.createSequentialGroup()
                .addGroup(Pan_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pan_CreditoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Dat_FechCre, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                    .addGroup(Pan_CreditoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TxtF_Credito, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                    .addGroup(Pan_CreditoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Che_Credito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pan_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Credito, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pan_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Lbl_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Cuota, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Credito", Pan_Credito);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 231, 181));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        Lbl_ValorAPagar.setBackground(new java.awt.Color(204, 204, 255));
        Lbl_ValorAPagar.setFont(new java.awt.Font("Tahoma", 0, 14));
        Lbl_ValorAPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_ValorAPagar.setText("0,00");
        Lbl_ValorAPagar.setToolTipText("Valor a Pagar");
        Lbl_ValorAPagar.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("V. Pagar:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_ValorAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(Lbl_ValorAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        Lbl_Fecha.setBackground(new java.awt.Color(244, 241, 241));
        Lbl_Fecha.setFont(new java.awt.Font("Tahoma", 0, 12));
        Lbl_Fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Fecha.setText("0,0");
        Lbl_Fecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lbl_Fecha.setOpaque(true);
        jPanel1.add(Lbl_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 119, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AceptarActionPerformed
        doClose(FrmDi_ConLinFactura.RET_OK);
}//GEN-LAST:event_Btn_AceptarActionPerformed

    private void Btn_Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cancelar1ActionPerformed
        // TODO add your handling code here:

        if (!Pagar()) return;
        
        this.doClose(FrmDi_ConLinFactura.RET_CANCEL);
}//GEN-LAST:event_Btn_Cancelar1ActionPerformed

    private void Che_PresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Che_PresActionPerformed
        // TODO add your handling code here:
        mPres = Che_Pres.isSelected();
    }//GEN-LAST:event_Che_PresActionPerformed

    private void Che_CreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Che_CreditoActionPerformed
// TODO add your handling code here:
        if (Che_Credito.isSelected()){ //Determina si el 
            try {
                setEnableCredito(true, true);
                Number ObjN = (Number) TxtF_Credito.getValue();
                
                mObjCred = new Dom_Class_Credito(ObjN.floatValue(), mObjFac.getMoneda(), 0,mMontoAPagar);
                setMontoAPagar(mObjCred, Dom_Class_Credito.TIPO);
            } catch (InputException ex) {
                JOptionPane.showMessageDialog(Pan_Credito, ex.getLocalizedMessage());
            }
            
        }else{
            TxtF_Credito.setValue(0.0);
            mObjCred = null;
            setMontoAPagar(mObjCred, Dom_Class_Credito.TIPO);
            setEnableCredito(false, false);
        }
}//GEN-LAST:event_Che_CreditoActionPerformed

    private void Btn_CreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CreditoActionPerformed

        // TODO add your handling code here:}//GEN-LAST:event_Btn_CreditoActionPerformed
    }
    private void TxtF_CreditoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtF_CreditoKeyPressed
        // TODO add your handling code here:
            if ( evt.getKeyCode() == 10){
                setValCredito();
            }
    }//GEN-LAST:event_TxtF_CreditoKeyPressed

    private void TxtF_CreditoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_CreditoFocusLost
        // TODO add your handling code here:

        setValCredito();
    }//GEN-LAST:event_TxtF_CreditoFocusLost

    private void TxtF_ContadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_ContadoFocusLost
        // TODO add your handling code here:
        setContado(TxtF_Contado.getText());    
    }//GEN-LAST:event_TxtF_ContadoFocusLost

    private void TxtF_ContadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtF_ContadoKeyPressed
        // TODO add your handling code here:
         if ( evt.getKeyCode() == 10)
             setContado(TxtF_Contado.getText());
            
    }//GEN-LAST:event_TxtF_ContadoKeyPressed

    private void TxtF_ContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtF_ContadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_ContadoActionPerformed

    private void TxtF_CreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtF_CreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_CreditoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Aceptar;
    private javax.swing.JButton Btn_Cancelar1;
    private javax.swing.JButton Btn_Credito;
    private javax.swing.JCheckBox Che_Credito;
    private javax.swing.JCheckBox Che_Pres;
    private com.toedter.calendar.JDateChooser Dat_FechCre;
    private javax.swing.JLabel Lbl_Cambio;
    private javax.swing.JLabel Lbl_Cuota;
    private javax.swing.JLabel Lbl_Fecha;
    private javax.swing.JLabel Lbl_Saldo;
    private javax.swing.JLabel Lbl_ValorAPagar;
    private javax.swing.JList Lis_Credito;
    private javax.swing.JPanel Pan_Credito;
    private javax.swing.JFormattedTextField TxtF_Contado;
    private javax.swing.JFormattedTextField TxtF_Credito;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public int getStatus(){
        return returnStatus;
    }
    
    private void doClose(int retStatus) {
        try {
            

            if(retStatus == RET_OK){
                if (mMontoAPagar != 0){
                    JOptionPane.showMessageDialog(this, "Asegúrese que el valor a pagar sea 0");
                    return;
                }
                // Si la forma de pago contado no es nulla y su monto es mayor a 0
                if (mObjCont != null && mObjCont.getMonto() > 0) 
                    mObjFac.altaForDePago(mObjCont);//Da de lata la forma de pago contado
                if(mObjCred != null && mObjCred.getMonto() > 0){
                    // Si la forma de pago credito no es null
                    mObjCred.setmFechPago(Dat_FechCre.getDate());
                    mObjFac.altaForDePago(mObjCred);// Da de alta la forma de pago credito
                }
                
            }
            

            returnStatus = retStatus;
            setVisible(false);
            dispose();
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }
    }
    
	/**
	 * Modifica el monto a pagar de la factura (mMontoAPagar). Es decir que si el
	 * valor de la forma de pago contado aumenta el valor a pagar disminuye y si el
	 * valor de contado disminuye el resto a pagar aumenta
	 * 
	 * @param xObjForPag    Tiene que ser una de las fomra de pago de este objeto
	 * �	mObjCon = Contado
	 * �	mObjCre= Credito
	 * 
	 */
    private void setMontoAPagar (LogN_Inter_FormaPag xObjForPag, String xTipFp ){
       

        
        float MontoPago = 0 ;
        if (mObjCont != null) MontoPago += mObjCont.getMonto();
        if (mObjCred != null) MontoPago += mObjCred.getMonto();
        
        try {
            this.setMontoAPagar(mMontoFactura - MontoPago);
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
            return;
        }
       
        try {
            if(xObjForPag == null || xObjForPag.getMonto() == 0) return;
            // Modifico el monto a pagar ya que el valor pagado es diferente
            if( (!xTipFp.equals(Dom_Class_Contado.TIPO))  && mObjCont != null) 
                mObjCont.setMonoAPatar(mMontoAPagar);
            else if((!xTipFp.equals(Dom_Class_Credito.TIPO))  && mObjCred != null && mMontoAPagar != 0) 
                mObjCred.setMonoAPatar(mMontoAPagar);
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this,ex.getLocalizedMessage());
        }
        
    }

    private boolean Pagar() {
        if (mObjCont.getMonto() < mObjFac.getTotFin()){
            JOptionPane.showMessageDialog(this, "El monto pagado no abarca la totalidad de la factura");
            return false;
        }
        try {
            mObjFac.altaForDePago(mObjCont);
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
            return false;
        }
        return true;
    }
    
    
    /**
     * 
     * @param xObjFac 
     */
    private void carSaldo (LogN_ClassAb_Factura xObjFac){
        //Verifica que la factura posea una person
        if (xObjFac.getPersona() == null)this.setEnableCredito(false, true);
        else{
            LogN_ClassAb_Persona ObjPer = xObjFac.getPersona(); //Optiene la persona de la factura
            Dom_Class_Saldo ObjSaldo = ObjPer.getSaldo(xObjFac.getMoneda()); // Busca el saldo que coinsida con la moneda de la factura
            if (ObjSaldo == null) Lbl_Saldo.setText("0,0");
            else Lbl_Saldo.setText(mNf.format(ObjSaldo.getMonto()));
        }
        
        this.setEnableCredito(false, false);
    }
    /**
     * Habilita o deshabilita la los controles relacionados con la forma de pago crédito
     * 
     * @param xEstado Determina si el habilita o deshabilita según el valor true o false respectivamente
     * @param full Determina si la habilitación o desafiliación afecta al control Che_Credito 
     */
    private void setEnableCredito (boolean xEstado, boolean full){
        
        if (full)Che_Credito.setEnabled(xEstado);
        Dat_FechCre.setEnabled(xEstado);
        Btn_Credito.setEnabled(xEstado);
        TxtF_Credito.setEnabled(xEstado);
        Lis_Credito.setEnabled(xEstado);
        Lbl_Cuota.setEnabled(xEstado);
        Lbl_Saldo.setEnabled(xEstado);
    }
    
    
    private Float CambarFloat (String xVal) throws InputException{
        Float xRespuesta = new Float(0);
        xVal = xVal.replace(" ", "");
        if (xVal.equals(""))return null;
        xVal = xVal.replace(",", ".");
        try{
            xRespuesta = new Float(xVal);
        }catch (NumberFormatException ex){
            throw new InputException("El Valor ingresado no es un dato numérico");
        }
        return xRespuesta;

    }
    public void AsignarCredito (boolean xActivar) {
        
        if (xActivar == false){
            this.mObjCred = null;
        }else{
            
            
        }
        
    }
    private void setMontoAPagar(float mMontoAPagar) throws InputException{
        String MonAPag = mNf.format(mMontoAPagar);
        this.mMontoAPagar = Float.parseFloat(MonAPag.replace(".", "").replace(",", "."));
        
        Lbl_ValorAPagar.setText(MonAPag);
    }
    
    private  void setValCredito (){
       
        if (mObjCred == null) return ;
        try {
            // TODO add your handling code here:
            Float Monto = this.CambarFloat(TxtF_Credito.getText());
            
            if (Monto == null) return;
            if (Monto == mObjCred.getMonto()) return;
            
            mObjCred.setMonto(Monto.floatValue());
            
            this.setMontoAPagar(mObjCred, Dom_Class_Credito.TIPO);
            
            TxtF_Credito.setValue(Monto);
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
            TxtF_Credito.requestFocus();
            float ValCred = 0;
            if (mObjCred != null) ValCred = mObjCred.getMonto();
            TxtF_Credito.setValue(ValCred);
            TxtF_Credito.selectAll();
            
        }
    }
    
    private void setContado (String xMonto){

        xMonto = xMonto.replace(" ", "");
        if (xMonto.equals(""))return;
        xMonto = xMonto.replace(",", ".");

        try{
            float Num = Float.parseFloat(xMonto);
            if ((Num - this.mCambioCli) == mObjCont.getMonto()) return;
            
            this.mCambioCli = mObjCont.setMonto(Num);
            Lbl_Cambio.setText(this.mNf.format(mCambioCli));
            this.setMontoAPagar(mObjCont, Dom_Class_Contado.TIPO);
            return; // Si no se produce nunguna exepcion sale
        }catch(NumberFormatException Ex){
            
        }catch(InputException Ex1){
            
        }
        TxtF_Contado.setText(mNf.format(mObjCont.getMonto()));
    } // Fin setContado
}
