/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmDi_ConModProd.java
 *
 * Created on 03-may-2011, 9:41:00
 */

package Precentacion;

import Logica_Negocio.Dominio.Dom_Class_ProductoComp;
import java.beans.PropertyVetoException;
import java.security.Principal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Ary
 */
public class FrmDi_ConModProd extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    private Dom_Class_ProductoComp mObjPro;
    private FrmIn_ModProd mObjFrmInModProd;
    
    
    
    /** Creates new form FrmDi_ConModProd */
    public FrmDi_ConModProd(java.awt.Window parent, Dom_Class_ProductoComp mObjProd) {
        super(parent,java.awt.Dialog.ModalityType.APPLICATION_MODAL); //Yama al contsructor de el dealog para bloquear los formularios ijos
        initComponents();
        this.mObjPro = mObjProd;
        this.inicialisarFrmImModif();
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        Btn_Aceptar = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();
        DexP_Prin = new javax.swing.JDesktopPane();
        Btn_Limpiar = new javax.swing.JButton();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        Btn_Aceptar.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Btn_Aceptar.setForeground(java.awt.Color.white);
        Btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Yes v3.png"))); // NOI18N
        Btn_Aceptar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.gray, null, java.awt.Color.gray));
        Btn_Aceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AceptarActionPerformed(evt);
            }
        });

        Btn_Cancelar.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        Btn_Cancelar.setForeground(java.awt.Color.white);
        Btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel_f2.png"))); // NOI18N
        Btn_Cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.gray, null, java.awt.Color.gray));
        Btn_Cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });

        Btn_Limpiar.setBackground(new java.awt.Color(102, 102, 102));
        Btn_Limpiar.setFont(new java.awt.Font("Arial Black", 1, 18));
        Btn_Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cargar.png"))); // NOI18N
        Btn_Limpiar.setText("Limpiar");
        Btn_Limpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.gray, null, java.awt.Color.gray));
        Btn_Limpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(Btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(DexP_Prin, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(DexP_Prin, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Cancelar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Btn_Aceptar, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                        .addComponent(Btn_Limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void Btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AceptarActionPerformed
        this.aceptar();
}//GEN-LAST:event_Btn_AceptarActionPerformed

    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
        // TODO add your handling code here:
        this.doClose(FrmDi_ConLinFactura.RET_CANCEL);
}//GEN-LAST:event_Btn_CancelarActionPerformed

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();

    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton Btn_Aceptar;
    protected javax.swing.JButton Btn_Cancelar;
    protected javax.swing.JButton Btn_Limpiar;
    private javax.swing.JDesktopPane DexP_Prin;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
    
     private void InisFor (JInternalFrame Frm){

        Frm.setVisible(true);

        DexP_Prin.add(Frm);
        Frm.moveToFront(); // mueve acia delate el Formulario

        try {
            Frm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void inicialisarFrmImModif() {
        mObjFrmInModProd = new FrmIn_ModProd(this, mObjPro);
        
        mObjFrmInModProd.Btn_Aceptar.setVisible(false);
        mObjFrmInModProd.Btn_Lim.setVisible(false);
        mObjFrmInModProd.Che_SubP.setNextFocusableComponent(Btn_Aceptar);
        Btn_Cancelar.setNextFocusableComponent(mObjFrmInModProd.TabP_Opciones);
        InisFor(mObjFrmInModProd);
        mObjFrmInModProd.ComBAu_Categoria.requestFocus();
    }

    private void aceptar() {
        if(mObjFrmInModProd.aceptar())doClose(FrmDi_ConModProd.RET_OK);
    }

    private void limpiar (){
        mObjFrmInModProd.limpiarProdCom();
    }
}
