    /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmDi_Moneda.java
 *
 * Created on 10/05/2011, 06:52:08 PM
 */
package Precentacion;

import Logica_Negocio.Dominio.CPorNom.LogN_ClassAb_CrePorNom;
import Logica_Negocio.Dominio.Dom_Class_Cotisacion;
import Logica_Negocio.Dominio.Dom_Class_Moneda;
import Logica_Negocio.Dominio.Dom_Class_Pais;
import Logica_Negocio.LogN_Class_Fachada;
import Logica_Negocio.MiExepcion.InputException;
import Precentacion.Model.jTabel.ModeljTabMoneda;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;



/**
 *
 * @author ary
 */
public class FrmDi_Moneda extends javax.swing.JDialog implements Observer{

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    private LogN_Class_Fachada mObjFachada = LogN_Class_Fachada.getInstancia();
    private java.awt.Window mFrmCon;
    private PersonalComboBoxMedel <Dom_Class_Pais> mObjModComB_Pais;
    private Dom_Class_Pais mObjPaisSel;
    private Dom_Class_Moneda mObjMonSel, 
            mObjMonLoc, // Se utilisa pra la moneda local actual 
            mObjMonLocalSis; // Se utilisa para la moneda local del sistema
    
    private ModeljTabMoneda mObjModMon;
    
    private ArrayList <Dom_Class_Moneda> mColMoneda = new ArrayList<Dom_Class_Moneda> ();
    private ArrayList <LogN_Class_Accion> mColAcciones = new ArrayList<LogN_Class_Accion> ();
    
    
    
    /** Creates new form FrmDi_Moneda */
    public FrmDi_Moneda(java.awt.Window parent) {
        super(parent,java.awt.Dialog.ModalityType.APPLICATION_MODAL); //Yama al contsructor de el dealog para bloquear los formularios ijos
        mFrmCon = parent;
        
        mObjModMon = new ModeljTabMoneda(mObjFachada.listarMondeda());// Lista las monedas 
        mObjModMon.addObserver(this);
        
        mObjMonLocalSis = mObjFachada.getMonedaLoc();
        
        mObjMonLoc = mObjMonLocalSis;
        
        mColMoneda = mObjFachada.listarMondeda();
        
        mObjFachada.addObservadorMoneda(mObjModMon);
        
        initComponents();
        cargarPais();
        this.cargarMonedaLocal(mObjMonLoc);

        
        
//         Close the dialog when Esc is pressed
//        String cancelName = "cancel";
//        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
//        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
//        ActionMap actionMap = getRootPane().getActionMap();
//        actionMap.put(cancelName, new AbstractAction() {
//
//            public void actionPerformed(ActionEvent e) {
//                doClose(RET_CANCEL);
//            }
//        });
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        Txt_Nom = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Lbl_Cod4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxtF_CotCom = new Utilidades.JFormattedText();
        Btn_Agregar = new javax.swing.JButton();
        Btn_Limpiar = new javax.swing.JButton();
        Btn_Baja = new javax.swing.JButton();
        ComB_Pais = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Txt_Sig = new javax.swing.JTextField();
        TxtF_CotVen = new Utilidades.JFormattedText();
        Btn_ModPais = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tab_Moneda = new javax.swing.JTable();
        Btn_Cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Btn_MonLocal = new javax.swing.JButton();
        Lbl_Cod5 = new javax.swing.JLabel();
        Lbl_MonLocal = new javax.swing.JLabel();
        Btn_Aceptar = new javax.swing.JButton();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        Txt_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NomActionPerformed(evt);
            }
        });
        Txt_Nom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Txt_NomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_NomFocusLost(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(13, 151, 239));
        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("Nombre");
        jLabel12.setOpaque(true);

        Lbl_Cod4.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_Cod4.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Lbl_Cod4.setForeground(new java.awt.Color(254, 254, 254));
        Lbl_Cod4.setText("Pais");
        Lbl_Cod4.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(13, 151, 239));
        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setText("Cot. Com. / Vent.");
        jLabel14.setOpaque(true);

        TxtF_CotCom.setValue(new Float(0.0));
        TxtF_CotCom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtF_CotComFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_CotComFocusLost(evt);
            }
        });

        Btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_db_add.png"))); // NOI18N
        Btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgregarActionPerformed(evt);
            }
        });

        Btn_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_editdelete.png"))); // NOI18N
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });

        Btn_Baja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_db_remove.png"))); // NOI18N
        Btn_Baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BajaActionPerformed(evt);
            }
        });

        ComB_Pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComB_PaisActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(13, 151, 239));

        jLabel13.setBackground(new java.awt.Color(13, 151, 239));
        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel13.setForeground(new java.awt.Color(254, 254, 254));
        jLabel13.setText("Simbolo");
        jLabel13.setOpaque(true);

        Txt_Sig.setText("$");
        Txt_Sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_SigActionPerformed(evt);
            }
        });
        Txt_Sig.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Txt_SigFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_SigFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_Sig, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Txt_Sig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TxtF_CotVen.setValue(new Float(0.0));
        TxtF_CotVen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtF_CotVenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_CotVenFocusLost(evt);
            }
        });

        Btn_ModPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_ModPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Txt_Nom, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                    .addComponent(TxtF_CotCom, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(TxtF_CotVen))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                    .addComponent(Btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Btn_Baja, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(Lbl_Cod4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                    .addComponent(ComB_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Btn_ModPais, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(Lbl_Cod4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComB_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_ModPais, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtF_CotCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtF_CotVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Limpiar)
                    .addComponent(Btn_Agregar)
                    .addComponent(Btn_Baja))
                .addContainerGap())
        );

        Tab_Moneda.setModel(mObjModMon);
        Tab_Moneda.getSelectionModel().addListSelectionListener(
            new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    Tab_MonedaValueChanged(event);
                }
            }
        );
        jScrollPane1.setViewportView(Tab_Moneda);

        Btn_Cancelar.setFont(new java.awt.Font("Arial Black", 1, 13));
        Btn_Cancelar.setForeground(java.awt.Color.white);
        Btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel_f2.png"))); // NOI18N
        Btn_Cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.gray, null, java.awt.Color.gray));
        Btn_Cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));

        Btn_MonLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Ab.png"))); // NOI18N
        Btn_MonLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MonLocalActionPerformed(evt);
            }
        });

        Lbl_Cod5.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_Cod5.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Lbl_Cod5.setForeground(new java.awt.Color(254, 254, 254));
        Lbl_Cod5.setText("Monea Local");
        Lbl_Cod5.setOpaque(true);

        Lbl_MonLocal.setBackground(new java.awt.Color(255, 255, 153));
        Lbl_MonLocal.setForeground(new java.awt.Color(102, 102, 102));
        Lbl_MonLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_MonLocal.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        Lbl_MonLocal.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_MonLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Lbl_Cod5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(Btn_MonLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Lbl_MonLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Lbl_Cod5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Btn_MonLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Btn_Aceptar.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Btn_Aceptar.setForeground(java.awt.Color.white);
        Btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Yes v3.png"))); // NOI18N
        Btn_Aceptar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.gray, null, java.awt.Color.gray));
        Btn_Aceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(Btn_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Btn_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_Cancelar))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void Txt_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NomActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Txt_NomActionPerformed

    private void Txt_NomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_NomFocusGained
        // TODO add your handling code here:
        Txt_Nom.selectAll();
}//GEN-LAST:event_Txt_NomFocusGained

    private void Txt_NomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_NomFocusLost
        // TODO add your handling code here:
}//GEN-LAST:event_Txt_NomFocusLost

    private void TxtF_CotComFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_CotComFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_TxtF_CotComFocusGained

    private void TxtF_CotComFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_CotComFocusLost
        // TODO add your handling code here:
        TxtF_CotCom.setText(TxtF_CotCom.getText().replace(".", ","));
}//GEN-LAST:event_TxtF_CotComFocusLost

    private void Btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgregarActionPerformed
        // TODO add your handling code here:
        altaMoneda();

}//GEN-LAST:event_Btn_AgregarActionPerformed

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
        // TODO add your handling code here:

}//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void Btn_BajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BajaActionPerformed
        // TODO add your handling code here:
        this.bajaMondea();

}//GEN-LAST:event_Btn_BajaActionPerformed

    private void TxtF_CotVenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_CotVenFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_CotVenFocusGained

    private void TxtF_CotVenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_CotVenFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_CotVenFocusLost

    private void Txt_SigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_SigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_SigActionPerformed

    private void Txt_SigFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_SigFocusGained
        // TODO add your handling code here:
        Txt_Sig.selectAll();
    }//GEN-LAST:event_Txt_SigFocusGained

    private void Txt_SigFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_SigFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_SigFocusLost

    private void Btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AceptarActionPerformed
        doClose(FrmDi_ConLinFactura.RET_OK);
}//GEN-LAST:event_Btn_AceptarActionPerformed

    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
        // TODO add your handling code here:
        this.doClose(FrmDi_ConLinFactura.RET_CANCEL);
}//GEN-LAST:event_Btn_CancelarActionPerformed

    private void ComB_PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComB_PaisActionPerformed
        // TODO add your handling code here:
        mObjPaisSel = (Dom_Class_Pais) ComB_Pais.getSelectedItem();
    }//GEN-LAST:event_ComB_PaisActionPerformed

    private void Btn_MonLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MonLocalActionPerformed
        // TODO add your handling code here:
        
        setMonLocal(mObjMonSel);
        
}//GEN-LAST:event_Btn_MonLocalActionPerformed

    private void Btn_ModPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModPaisActionPerformed
        // TODO add your handling code here:
        ModifPais();
    }//GEN-LAST:event_Btn_ModPaisActionPerformed
    
    private void doClose(int retStatus) {
        if (retStatus == RET_OK)this.actualizar();
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton Btn_Aceptar;
    private javax.swing.JButton Btn_Agregar;
    private javax.swing.JButton Btn_Baja;
    protected javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JButton Btn_ModPais;
    private javax.swing.JButton Btn_MonLocal;
    private javax.swing.JComboBox ComB_Pais;
    private javax.swing.JLabel Lbl_Cod4;
    private javax.swing.JLabel Lbl_Cod5;
    private javax.swing.JLabel Lbl_MonLocal;
    private javax.swing.JTable Tab_Moneda;
    private javax.swing.JFormattedTextField TxtF_CotCom;
    private javax.swing.JFormattedTextField TxtF_CotVen;
    private javax.swing.JTextField Txt_Nom;
    private javax.swing.JTextField Txt_Sig;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
    
    // <editor-fold defaultstate="collapsed" desc="Metodos Pais">
    private void ModifPais (){
         // TODO add your handling code here:
        ArrayList ColPais = mObjFachada.listarPais();

       FrmDi_CreaPorNom FrmCreXNom = new FrmDi_CreaPorNom(mFrmCon, "Pais", ColPais) {

            @Override
            protected LogN_ClassAb_CrePorNom crearCrePorNom() throws InputException {
                Dom_Class_Pais mObjP = new Dom_Class_Pais (super.TxtF_Modificar.getText());
                mObjP.validar();
                return mObjP;
            }
        };
        FrmCreXNom.setVisible(true);

        if(FrmDi_CreaPorNom.RET_OK == FrmCreXNom.getReturnStatus()){
            for (LogN_Class_Accion<Dom_Class_Pais> ObjAcc  : FrmCreXNom.getAccion()){
                Dom_Class_Pais ObjAccPais = ObjAcc.getmAccionar();
                switch (ObjAcc.mAccionActual) {
                    case LogN_Class_Accion.Agreger:
                        try {
                            mObjFachada.altaPais(ObjAccPais);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }
                    break;
                    case LogN_Class_Accion.Modificar:

                        
                        Dom_Class_Pais ObjPaisAn = (Dom_Class_Pais)mObjModComB_Pais.getElementAt(ObjAcc.getmAccionar());
                        
                        try {
                            mObjFachada.modifPais(ObjPaisAn, ObjAccPais);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex);
                        }
                    break;
                    case LogN_Class_Accion.Eliminar:
                        try {
                            mObjFachada.bajaPais(ObjAccPais);
                        } catch (InputException ex) {
                           JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }

                    break;
                }// Fin switch
            }//Fin for

            cargarPais();
            
        } // Fin if
    }
    
    private void cargarPais (){
        ArrayList<Dom_Class_Pais> ColPais = mObjFachada.listarPais();
        
        mObjModComB_Pais = new PersonalComboBoxMedel<Dom_Class_Pais>
                    (ColPais, PersonalComboBoxMedel.Alfabet_Acendente, null);
        mObjPaisSel = null;
        ComB_Pais.setModel(mObjModComB_Pais);
        if(ColPais.size() > 0 ){
            ComB_Pais.setSelectedIndex(0);
        }
    }
    
    // </editor-fold>  
    
    private void Tab_MonedaValueChanged(ListSelectionEvent evt){
       mObjMonSel = mObjModMon.getMondeda(Tab_Moneda.getSelectedRow());
       
    }
    
    public void altaMoneda (){
         Dom_Class_Moneda ObjMoneda = this.crearMoneda();


        if (mColMoneda.contains(ObjMoneda)) {
            JOptionPane.showMessageDialog(this, "La moneda a ingresar ya existe compruebe el país");
            ComB_Pais.requestFocus();
        } else {
            
            LogN_Class_Accion ObjAccion = new LogN_Class_Accion<Dom_Class_Moneda> 
                    (LogN_Class_Accion.Agreger, ObjMoneda);
            
            int Pos = this.posAccion(ObjAccion);
            
            if (Pos != -1){
                ObjMoneda = (Dom_Class_Moneda) mColAcciones.get(Pos).getmAccionar();
            } else {
                mColAcciones.add(ObjAccion);
            }

            mColMoneda.add(ObjMoneda);
            mObjModMon.addRow(ObjMoneda);
           
            ComB_Pais.requestFocus();
            
        }
        
        
        
//        Dom_Class_Moneda ObjMondeda = this.crearMoneda();
//        try {
//            mObjFachada.altaMoneda(ObjMondeda);
//        } catch (InputException ex) {
//            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
//            return;
//        }
//        mObjModMon.addRow(ObjMondeda);
        
    }
    
    private  Dom_Class_Moneda crearMoneda (){
        String Nom = Txt_Nom.getText();
        String Sig = Txt_Sig.getText();
        Number CotCom = (Number) TxtF_CotCom.getValue();
        Number CotVen = (Number) TxtF_CotVen.getValue();
        
        return new  Dom_Class_Moneda(Nom, Sig, mObjPaisSel, new Dom_Class_Cotisacion(CotVen.floatValue(), CotCom.floatValue()));
    }

    private void limpiar (){
        Txt_Nom.setText("");
        Txt_Sig.setText("");

        TxtF_CotCom.setValue(new Float(0.0));
        TxtF_CotVen.setValue(new Float(0.0));

    }
    

    
    private void setMonLocal (Dom_Class_Moneda xObjMoneda){
        mObjMonLoc = xObjMoneda;
        cargarMonedaLocal(mObjMonLoc);
    
    }
    
    private  int posAccion (Object xObjAccion){

        int Size = mColAcciones.size();
        if (Size == -1) return -1;
        
        for (int i = 0 ; Size  > i ; ++i){
            if(mColAcciones.get(i).equals(xObjAccion)) return i;
            
        }
        return -1;

    }

    private void bajaMondea() {
        Dom_Class_Moneda ObjMoneda = mObjMonSel;
        if(ObjMoneda == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una moneda para dar de baja ");
            return;
        }
        LogN_Class_Accion <Dom_Class_Moneda> ObjAccion = new 
                LogN_Class_Accion<Dom_Class_Moneda> (LogN_Class_Accion.Eliminar, mObjMonSel);
        
        int Pos = this.posAccion(ObjAccion);

        mColMoneda.remove(ObjMoneda);
        
        mObjModMon.bajaRow(ObjMoneda);
        
        if(Pos != -1) mColAcciones.remove(Pos);

        mColAcciones.add(ObjAccion);
    }
    
    private void modificarMoneda (Dom_Class_Moneda xObjMoneda){
        int Pos = this.posAccion(xObjMoneda);

        if (Pos == -1 ) {

            mColAcciones.add(
                    new LogN_Class_Accion<Dom_Class_Moneda>
                    (LogN_Class_Accion.Modificar,xObjMoneda));
        }
    }

    @Override
    public void update(Observable o, Object arg) {
        
        LogN_Class_Accion <Dom_Class_Moneda> mObjAccion = (LogN_Class_Accion <Dom_Class_Moneda>) arg;
        
        if(LogN_Class_Accion.Modificar == mObjAccion.mAccionActual){
            this.modificarMoneda( mObjAccion.getmAccionar());

        }
        
    }

    private void actualizar() {
        
         for (LogN_Class_Accion<Dom_Class_Moneda> ObjAcc  : mColAcciones){
                Dom_Class_Moneda ObjMoneda = ObjAcc.getmAccionar();
                
                switch (ObjAcc.mAccionActual) {
                    case LogN_Class_Accion.Agreger:
                        try {

                            mObjFachada.altaMoneda(ObjMoneda, false);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }
                    break;
                    case LogN_Class_Accion.Modificar:

                        
                        Dom_Class_Moneda ObjMonAn = mObjFachada.getMoneda(ObjMoneda.getNum());
                        
                        try {
                                mObjFachada.modiMoneda(ObjMonAn, ObjMoneda);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex);
                        }
                    break;
                    case LogN_Class_Accion.Eliminar:
                        try {
                            mObjFachada.bajaMoneda(ObjMoneda);
                        } catch (InputException ex) {
                           JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }

                    break;
                }// Fin switch
            }//Fin for
         
         if (mObjMonLoc != mObjMonLocalSis)
             try {
            this.mObjFachada.setMonedaLocal(mObjMonLoc);
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }
    }

    /**
     * Carga los datos de moneda pasada por parámetro, al Lbl_MonLocal
     * @param mObjMonLoc 
     */
    private void cargarMonedaLocal(Dom_Class_Moneda mObjMonLoc) {
        String DetMoneda = ""; // Detalle moneda
        
        if (mObjMonLoc != null) DetMoneda = mObjMonLoc.toString();
        Lbl_MonLocal.setText(DetMoneda);
    }
}
