    /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmIn_Listar.java
 *
 * Created on 10/11/2010, 10:35:38 AM
 */

package Precentacion;


import Precentacion.Model.jList.PersonalListModelNoti;
import Logica_Negocio.Manejadora.jTabModel.LogN_ClassAb_ModeljTabProd;
import Logica_Negocio.Dominio.Dom_Class_Categoria;
import Logica_Negocio.Dominio.Dom_Class_ProductoComp;
import Logica_Negocio.Dominio.Dom_Class_SubProducto;
import Logica_Negocio.Filtros.Producto.LogN_ClassAb_FiltrarStringProducto;
import Logica_Negocio.Filtros.Producto.LogN_Class_FiltProdCod;
import Logica_Negocio.Filtros.Producto.LogN_Class_FiltProdNom;
import Logica_Negocio.Filtros.Producto.LogN_Class_FiltProdStokMin;
import Logica_Negocio.Filtros.Producto.LogN_Class_FiltProCat;
import Logica_Negocio.Filtros.LogN_Inter_Filtrar;
import Logica_Negocio.Filtros.Producto.LogN_Class_FiltProdCodBarr;
import Logica_Negocio.Filtros.Producto.LogN_Class_FiltProdTipo;
import Logica_Negocio.Filtros.Producto.LogN_Inter_FlitPorducto;
import Logica_Negocio.LogN_ClassAb_Producto;
import Logica_Negocio.LogN_Class_Fachada;
import Logica_Negocio.LogN_Class_ObsevadoAuxiliar;
import Logica_Negocio.MiExepcion.InputException;
import Precentacion.FrmDi_ConModProd;
import Precentacion.FrmDi_Movimiento;
import Precentacion.PersonalComboBoxMedel;
import Reportes.Rep_Class_IniciarReporte;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import net.sf.jasperreports.engine.JRException;



/**
 *
 * @author ary
 */
public class FrmIn_ListarProducto extends javax.swing.JInternalFrame {
    
    //Atributos_________________________________________________________________

    private LogN_Class_Fachada mObjFach = LogN_Class_Fachada.getInstancia();

    private LogN_ClassAb_ModeljTabProd mObjMJProd;
    
    private LogN_ClassAb_Producto mObjPord;

    public final LogN_Class_ObsevadoAuxiliar <FrmIn_ListarProducto> mObjObjAux =
            new LogN_Class_ObsevadoAuxiliar<FrmIn_ListarProducto>(this);
    
    private LogN_Inter_FlitPorducto mObjFilSelect;

    private final AbstractListModel mLisModFString = new AbstractListModel() {
                private String [] mDatos = {"No completo", "Completo", "Al principio", "Al final"};
                public int getSize() {
                    return mDatos.length;
                }

                public Object getElementAt(int index) {
                    return mDatos[index];
                }
    };
    
    private final AbstractListModel mLisModFCodB = new AbstractListModel() {
                private String [] mDatos = {"Completo", "Al principio", "Al final"};
                public int getSize() {
                    return mDatos.length;
                }

                public Object getElementAt(int index) {
                    return mDatos[index];
                }
    };
    
        private final AbstractListModel mLisModStokM = new AbstractListModel() {
                private String [] mDatos = {"Stock Minimo", "Stock Mayor"};
                public int getSize() {
                    return mDatos.length;
                }

                public Object getElementAt(int index) {
                    return mDatos[index];
                }


        };

     private PersonalComboBoxMedel <Dom_Class_Categoria> mObjCat =
            new PersonalComboBoxMedel<Dom_Class_Categoria>(
            mObjFach.listarCat(),PersonalComboBoxMedel.Alfabet_Acendente
            , null);

     private final Window mObjFrmCon;

     //Constructor_______________________________________________________________

    /** Creates new form FrmIn_Listar */
    public FrmIn_ListarProducto(Window  ObjFrmCon) {
        mObjMJProd = mObjFach.listarDetalleProducto(mObjFilSelect);
        initComponents();
        
        mObjFach.addObservadorCategoria(mObjCat);

        this.caragarLista();
        mObjFilSelect = (LogN_Inter_FlitPorducto) Lis_BuscarPor.getSelectedValue();
        cargarFiltrador(mObjFilSelect);
        this.mObjFrmCon = ObjFrmCon;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tab_Prod = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lis_BuscarPor = new javax.swing.JList();
        TxtF_Buscar = new javax.swing.JFormattedTextField();
        Btn_IniciarBusqueda = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Btn_CancelarBusqueda = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Lis_Pos = new javax.swing.JList();
        ComB_TipProd = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TxtA_Des1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        Btn_ModDes = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Lis_Notificacion = new javax.swing.JList();
        Btn_BorarNot = new javax.swing.JButton();
        Btn_AgrNot = new javax.swing.JButton();
        Btn_ModNot = new javax.swing.JButton();
        BarM_Menu = new javax.swing.JMenuBar();
        Men_Tar = new javax.swing.JMenu();
        Men_Modificar = new javax.swing.JMenuItem();
        Men_Eliminar = new javax.swing.JMenuItem();
        MenDes_Mov = new javax.swing.JMenu();
        Men_MovEn = new javax.swing.JMenuItem();
        Men_MovSal = new javax.swing.JMenuItem();
        Men_Imprimir = new javax.swing.JMenu();
        MenIn_Istorial = new javax.swing.JMenuItem();

        setTitle("Listar Producto");

        Tab_Prod.setModel(mObjMJProd);
        Tab_Prod.getSelectionModel().addListSelectionListener(
            new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    Tab_ProdValueChanged(event);
                }
            }
        );
        jScrollPane1.setViewportView(Tab_Prod);

        jPanel1.setBackground(new java.awt.Color(207, 228, 228));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(19, 152, 206)));

        Lis_BuscarPor.setModel(lista_Fitro());
        Lis_BuscarPor.setSelectedIndex(0);
        Lis_BuscarPor.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                Lis_BuscarPorValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(Lis_BuscarPor);

        TxtF_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtF_BuscarActionPerformed(evt);
            }
        });
        TxtF_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtF_BuscarKeyPressed(evt);
            }
        });

        Btn_IniciarBusqueda.setText("Iniciar");
        Btn_IniciarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IniciarBusquedaActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(13, 151, 239));
        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Búsqueda");
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(13, 151, 239));
        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Filtrar Por");
        jLabel8.setOpaque(true);

        Btn_CancelarBusqueda.setText("Cancelar");
        Btn_CancelarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarBusquedaActionPerformed(evt);
            }
        });

        Lis_Pos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                Lis_PosValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(Lis_Pos);

        ComB_TipProd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Producto", "Producto Compuesto", "Sub Producto" }));
        ComB_TipProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComB_TipProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtF_Buscar)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Btn_IniciarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btn_CancelarBusqueda)))
                    .addComponent(ComB_TipProd, 0, 158, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane5, 0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtF_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btn_IniciarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_CancelarBusqueda))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(ComB_TipProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(207, 228, 228));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TxtA_Des1.setColumns(20);
        TxtA_Des1.setRows(5);
        jScrollPane4.setViewportView(TxtA_Des1);

        jLabel3.setBackground(new java.awt.Color(13, 151, 239));
        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Descripción ");
        jLabel3.setOpaque(true);

        Btn_ModDes.setBackground(new java.awt.Color(2, 229, 167));
        Btn_ModDes.setText("Modificar");
        Btn_ModDes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Btn_ModDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModDesActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(13, 151, 239));
        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Notiicacion");
        jLabel4.setOpaque(true);

        jScrollPane3.setViewportView(Lis_Notificacion);

        Btn_BorarNot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_db_remove.png"))); // NOI18N
        Btn_BorarNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BorarNotActionPerformed(evt);
            }
        });

        Btn_AgrNot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_db_add.png"))); // NOI18N
        Btn_AgrNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgrNotActionPerformed(evt);
            }
        });

        Btn_ModNot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_ModNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModNotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(Btn_ModDes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Btn_BorarNot, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_ModNot, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_AgrNot, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_ModDes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_BorarNot, javax.swing.GroupLayout.PREFERRED_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(Btn_ModNot, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_AgrNot, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Men_Tar.setText("Tarea");

        Men_Modificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        Men_Modificar.setText("Modificar");
        Men_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Men_ModificarActionPerformed(evt);
            }
        });
        Men_Tar.add(Men_Modificar);

        Men_Eliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        Men_Eliminar.setText("Eliminar");
        Men_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Men_EliminarActionPerformed(evt);
            }
        });
        Men_Tar.add(Men_Eliminar);

        MenDes_Mov.setText("Movimiento");

        Men_MovEn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        Men_MovEn.setText("Entrada");
        Men_MovEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Men_MovEnActionPerformed(evt);
            }
        });
        MenDes_Mov.add(Men_MovEn);

        Men_MovSal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Men_MovSal.setText("Salida");
        Men_MovSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Men_MovSalActionPerformed(evt);
            }
        });
        MenDes_Mov.add(Men_MovSal);

        Men_Tar.add(MenDes_Mov);

        BarM_Menu.add(Men_Tar);

        Men_Imprimir.setText("Imprimir");

        MenIn_Istorial.setText("Listado Actual");
        MenIn_Istorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenIn_IstorialActionPerformed(evt);
            }
        });
        Men_Imprimir.add(MenIn_Istorial);

        BarM_Menu.add(Men_Imprimir);

        setJMenuBar(BarM_Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_IniciarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IniciarBusquedaActionPerformed
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_Btn_IniciarBusquedaActionPerformed

    private void Lis_BuscarPorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_Lis_BuscarPorValueChanged
        // TODO add your handling code here:
        mObjFilSelect = (LogN_Inter_FlitPorducto) Lis_BuscarPor.getSelectedValue();

        this.cargarFiltrador(mObjFilSelect);
    }//GEN-LAST:event_Lis_BuscarPorValueChanged

    private void Btn_ModDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModDesActionPerformed
        // TODO add your handling code here:
        this.modifiarDes();
    }//GEN-LAST:event_Btn_ModDesActionPerformed

    private void Lis_PosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_Lis_PosValueChanged
        // TODO add your handling code here:
        this.selecPosFil((short) Lis_Pos.getSelectedIndex());
    }//GEN-LAST:event_Lis_PosValueChanged

    private void Btn_CancelarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarBusquedaActionPerformed
        // TODO add your handling code here:
       CanFil();
    }//GEN-LAST:event_Btn_CancelarBusquedaActionPerformed

    private void TxtF_BuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtF_BuscarKeyPressed
        // TODO add your handling code here:

        if (KeyEvent.VK_ENTER == evt.getKeyCode()){
            filtrar();
            TxtF_Buscar.selectAll();
        }
    }//GEN-LAST:event_TxtF_BuscarKeyPressed

    private void Btn_BorarNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BorarNotActionPerformed
        // TODO add your handling code here:
        
}//GEN-LAST:event_Btn_BorarNotActionPerformed

    private void Btn_AgrNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgrNotActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Btn_AgrNotActionPerformed

    private void Btn_ModNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModNotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ModNotActionPerformed

    private void Men_MovEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Men_MovEnActionPerformed
        // TODO add your handling code here:
        this.AlataMov(true);


    }//GEN-LAST:event_Men_MovEnActionPerformed

    private void Men_MovSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Men_MovSalActionPerformed
        // TODO add your handling code here:
        this.AlataMov(false);
    }//GEN-LAST:event_Men_MovSalActionPerformed

    private void ComB_TipProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComB_TipProdActionPerformed
        // TODO add your handling code here
        try{
           mObjFilSelect.setTipProd((short) ComB_TipProd.getSelectedIndex());
           
        }catch (InputException ex){
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
        }

    }//GEN-LAST:event_ComB_TipProdActionPerformed

    private void TxtF_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtF_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_BuscarActionPerformed

    private void Men_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Men_EliminarActionPerformed
        this.eleminarProd();
        
    }//GEN-LAST:event_Men_EliminarActionPerformed

    private void Men_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Men_ModificarActionPerformed
        // TODO add your handling code here:
        this.modificarPord();
    }//GEN-LAST:event_Men_ModificarActionPerformed

    private void MenIn_IstorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenIn_IstorialActionPerformed
        try {
            // TODO add your handling code here:
            Rep_Class_IniciarReporte.imprimirLisProd(mObjMJProd.listarProducto(), false);
        } catch (JRException ex) {
            Logger.getLogger(FrmIn_ListarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }




    }//GEN-LAST:event_MenIn_IstorialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarM_Menu;
    private javax.swing.JButton Btn_AgrNot;
    private javax.swing.JButton Btn_BorarNot;
    private javax.swing.JButton Btn_CancelarBusqueda;
    private javax.swing.JButton Btn_IniciarBusqueda;
    private javax.swing.JButton Btn_ModDes;
    private javax.swing.JButton Btn_ModNot;
    private javax.swing.JComboBox ComB_TipProd;
    private javax.swing.JList Lis_BuscarPor;
    private javax.swing.JList Lis_Notificacion;
    private javax.swing.JList Lis_Pos;
    private javax.swing.JMenu MenDes_Mov;
    private javax.swing.JMenuItem MenIn_Istorial;
    private javax.swing.JMenuItem Men_Eliminar;
    private javax.swing.JMenu Men_Imprimir;
    private javax.swing.JMenuItem Men_Modificar;
    private javax.swing.JMenuItem Men_MovEn;
    private javax.swing.JMenuItem Men_MovSal;
    private javax.swing.JMenu Men_Tar;
    private javax.swing.JTable Tab_Prod;
    private javax.swing.JTextArea TxtA_Des1;
    private javax.swing.JFormattedTextField TxtF_Buscar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables



     private void Tab_ProdValueChanged(ListSelectionEvent evt){
         try{
             
             mObjPord= mObjMJProd.getPord(Tab_Prod.getSelectedRow());

             mObjObjAux.Notifiar(mObjPord);

         String Des = mObjPord.getMProd_Desc();
         if (Des == null) Des = "";
         TxtA_Des1.setText(Des);
         if (mObjPord instanceof Dom_Class_SubProducto) return;

         Dom_Class_ProductoComp objProductoCom = (Dom_Class_ProductoComp) mObjPord;
         Lis_Notificacion.setModel(new PersonalListModelNoti(objProductoCom.getmColNoti(), PersonalListModelNoti.Fecha_Acendente, null));
     
         } catch (NullPointerException nE){

         }

     }

    private void caragarLista() {
        com.jidesoft.swing.AutoCompletionComboBox xComBCat = new com.jidesoft.swing.AutoCompletionComboBox(mObjCat);

        Tab_Prod.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(xComBCat));

        

    }

    private void modifiarDes() {
//        if (mObjPord == null) {
//            JOptionPane.showMessageDialog(Btn_ModDes, "No ha seleccionado nungun producto");
//            return;
//        }
//
//        if(mObjPord.getMProd_Desc().equals(TxtA_Des1.getText())){
//            JOptionPane.showMessageDialog(Btn_ModDes, "No se han echo cambios en las descripciones");
//            return;
//        }
//        LogN_ClassAb_Producto ObjProd = mObjPord.duplicarProd();
//
//        ObjProd.setMProd_Desc(TxtA_Des1.getText());
//        
//        try {
//            mObjFach.modificarPored(null, null);
//        } catch (InputException ex) {
//            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
//        }
    }
    
    
    private void modificarPord() {
        if(mObjPord == null)JOptionPane.showMessageDialog(this, "Debe seleccionar un producto para Modificar");
        else if (!(mObjPord instanceof Dom_Class_ProductoComp)) 
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto y no un sub producto para Modificar");
        else {
            FrmDi_ConModProd ObjFrmDi_ConModProd = new FrmDi_ConModProd(mObjFrmCon, (Dom_Class_ProductoComp)mObjPord);
            ObjFrmDi_ConModProd.setVisible(true);
        }
    }
    
    private void eleminarProd() {
        
        if(mObjPord == null)JOptionPane.showMessageDialog(this, "Debe seleccionar un producto para Eliminar");
        else if (JOptionPane.showConfirmDialog(null,"Seguro que desea eliminar \"" + mObjPord.getMProd_Nom() +  "\" ", "Eliminar", JOptionPane.YES_OPTION) == 0){
            try {
                
                // TODO add your handling code here:
                mObjFach.bajaProducto(mObjPord);
                mObjPord  = null;
            
        } catch (InputException ex) {
            Logger.getLogger(FrmIn_ListarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }
    //Filtro *******************************************************************

    private AbstractListModel lista_Fitro () {
        AbstractListModel ObjMList = null;

       try {
        ObjMList = new AbstractListModel(){

                private LogN_Inter_Filtrar[] mDato = {
                    new LogN_Class_FiltProdCodBarr(LogN_Class_FiltProdCodBarr.Producto, LogN_Class_FiltProdCodBarr.Completa, ""),
                    new LogN_Class_FiltProdCod(LogN_Class_FiltProdCod.Producto,LogN_Class_FiltProdCod.IGUAL_QUE,"0"),
                    new LogN_Class_FiltProdNom("", LogN_Class_FiltProdNom.No_Completa, LogN_Class_FiltProdNom.Producto),
                    new LogN_Class_FiltProCat("", LogN_Class_FiltProCat.No_Completa, LogN_Class_FiltProCat.Producto),
                    new LogN_Class_FiltProdStokMin(LogN_Class_FiltProdStokMin.EN_STOK_MIN,LogN_Class_FiltProdStokMin.Producto),
                    new LogN_Class_FiltProdTipo(LogN_Class_FiltProdTipo.Producto)
                };

                public int getSize() {
                    return mDato.length;
                }
                public Object getElementAt(int index) {
                    return mDato[index];
                }
        };
       } catch (InputException ex) {
                Logger.getLogger(FrmIn_ListarProducto.class.getName()).log(Level.SEVERE, null, ex);
       }
        return ObjMList;
    }

    private void cargarFiltrador (LogN_Inter_FlitPorducto xObjFil){

        if (xObjFil instanceof LogN_ClassAb_FiltrarStringProducto){
            LogN_ClassAb_FiltrarStringProducto ObjFilString = (LogN_ClassAb_FiltrarStringProducto)xObjFil;
            
           
            TxtF_Buscar.setVisible(true);
            short Indice = ObjFilString.getmPocicion();
            Lis_Pos.setModel(mLisModFString);
            Lis_Pos.setSelectedIndex(Indice);
            Indice = ObjFilString.getTipProd();

        } else if (xObjFil instanceof LogN_Class_FiltProdStokMin){

            
            TxtF_Buscar.setVisible(false);
            short Indice = xObjFil.getmPocicion();
            Lis_Pos.setModel(mLisModStokM);
            Lis_Pos.setSelectedIndex(Indice);
        }else if (xObjFil instanceof LogN_Class_FiltProdCodBarr){
            LogN_Class_FiltProdCodBarr ObjFilCodB = (LogN_Class_FiltProdCodBarr) xObjFil;
            
            TxtF_Buscar.setVisible(true);
            short Indice =  (short) (ObjFilCodB.getmPocicion() - 3);
            
            Lis_Pos.setModel(mLisModFCodB);
            Lis_Pos.setSelectedIndex(Indice);
            Indice = ObjFilCodB.getTipProd();
        }else{
            TxtF_Buscar.setVisible(true);
            Lis_Pos.setModel(new DefaultListModel());

        }
        ComB_TipProd.setSelectedIndex(xObjFil.getTipProd());
    }

    private void selecPosFil(short s) {
        try {
            mObjFilSelect.setmPocicion(s);
        } catch (InputException ex) {
           
        }
    }

    private void FiltrarProducto (Object Comparador){
        try {
            
            if (Comparador == null ){
                mObjMJProd.setFlitro(null);
                return;
            }
            
            mObjFilSelect.setmCondicion(Comparador);
            mObjMJProd.setFlitro(mObjFilSelect);
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }

    }

    //Metodos publicos ----------------------------------------------------------


    public LogN_ClassAb_Producto getSelectedProd (){

        return mObjPord;
    }

    public void filtrar (){
        if (TxtF_Buscar.getText().trim().equals("") && !(Lis_BuscarPor.getSelectedValue() instanceof LogN_Class_FiltProdStokMin)) return;
        this.FiltrarProducto(TxtF_Buscar.getText());
        
        try{
           this.Tab_Prod.setRowSelectionInterval(0, 0); 
        } catch (java.lang.IllegalArgumentException ex){
            
        }
        
                
    }

    public void CanFil(){
        this.FiltrarProducto(null);
    }

    //Movimeiento **************************************************************


    private void AlataMov(boolean Entrdada){
        
        if ( mObjPord == null){
            JOptionPane.showMessageDialog(null, "No a seleccionad ningún producto para generar movimiento");
            return;
        }
        

        try {


            FrmDi_Movimiento ObjFrmMov = new FrmDi_Movimiento(this.mObjFrmCon, mObjPord.generarMovimiento("", "", "", 0, Entrdada));

            ObjFrmMov.setVisible(true);
            if (ObjFrmMov.getReturnStatus() == FrmDi_Movimiento.RET_OK){
                 mObjFach.altaMovimiento(ObjFrmMov.getMov());
                
            }
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }
    }








}
