/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frm_Persona.java
 *
 * Created on 13/03/2011, 03:29:05 PM
 */

package Precentacion.Persona;

import java.beans.PropertyVetoException;
import java.security.Principal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Willi@m
 */
public class Frm_Persona extends javax.swing.JFrame {
    private FrmIn_AgrPer mFrmAgCliente = new FrmIn_AgrCom(this);
    private FrmIn_ListarPersona mFrmLisCliente = new FrmIn_ListarCliente(this);

    private FrmIn_AgrPer mFrmAgProveedor = new FrmIn_AgrCom(this);
    private FrmIn_ListarPersona mFrmLisProvvedor = new FrmIn_ListarCliente(this); //Areglar !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    /** Creates new form Frm_Persona */
    public Frm_Persona() {
        initComponents();

        this.InisFor(mFrmAgProveedor);
        this.InisFor(mFrmLisProvvedor);

        this.InisFor(mFrmLisCliente);
        this.InisFor(mFrmAgCliente);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        DexP_Prin = new javax.swing.JDesktopPane();
        jPanel5 = new javax.swing.JPanel();
        Btn_AgCli = new javax.swing.JToggleButton();
        Btn_LisCli = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        Btn_AbProv = new javax.swing.JToggleButton();
        Btn_LisPro = new javax.swing.JToggleButton();

        setTitle("Persona");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        buttonGroup1.add(Btn_AgCli);
        Btn_AgCli.setFont(new java.awt.Font("Tahoma", 1, 12));
        Btn_AgCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addusers.png"))); // NOI18N
        Btn_AgCli.setSelected(true);
        Btn_AgCli.setText("Agregar");
        Btn_AgCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgCliActionPerformed(evt);
            }
        });

        buttonGroup1.add(Btn_LisCli);
        Btn_LisCli.setFont(new java.awt.Font("Tahoma", 1, 12));
        Btn_LisCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/bucar+.png"))); // NOI18N
        Btn_LisCli.setText("Listar");
        Btn_LisCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LisCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Btn_AgCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_LisCli, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Btn_AgCli)
                .addComponent(Btn_LisCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proovedores", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        buttonGroup1.add(Btn_AbProv);
        Btn_AbProv.setFont(new java.awt.Font("Tahoma", 1, 12));
        Btn_AbProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addusers.png"))); // NOI18N
        Btn_AbProv.setText("Agregar");
        Btn_AbProv.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Btn_AbProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AbProvActionPerformed(evt);
            }
        });

        buttonGroup1.add(Btn_LisPro);
        Btn_LisPro.setFont(new java.awt.Font("Tahoma", 1, 12));
        Btn_LisPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/bucar+.png"))); // NOI18N
        Btn_LisPro.setText("Listar");
        Btn_LisPro.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Btn_LisPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LisProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_AbProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_LisPro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(Btn_LisPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_AbProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(477, 477, 477)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(DexP_Prin, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(DexP_Prin, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AgCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgCliActionPerformed

        mFrmAgCliente.moveToFront(); // mueve acia delate el Formulario
    }//GEN-LAST:event_Btn_AgCliActionPerformed

    private void Btn_LisCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LisCliActionPerformed
        // TODO add your handling code here:
        mFrmLisCliente.moveToFront();
    }//GEN-LAST:event_Btn_LisCliActionPerformed

    private void Btn_AbProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AbProvActionPerformed
        // TODO add your handling code here:
        mFrmAgProveedor.moveToFront();
    }//GEN-LAST:event_Btn_AbProvActionPerformed

    private void Btn_LisProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LisProActionPerformed
        // TODO add your handling code here:
        mFrmLisProvvedor.moveToFront();
    }//GEN-LAST:event_Btn_LisProActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Frm_Persona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Btn_AbProv;
    private javax.swing.JToggleButton Btn_AgCli;
    private javax.swing.JToggleButton Btn_LisCli;
    private javax.swing.JToggleButton Btn_LisPro;
    private javax.swing.JDesktopPane DexP_Prin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    
    private void InisFor (JInternalFrame Frm){

        Frm.setVisible(true);

        DexP_Prin.add(Frm);
        Frm.moveToFront(); // mueve acia delate el Formulario

        try {
            Frm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
