/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmDi_ConPer.java
 *
 * Created on 26-jul-2011, 10:46:21
 */
package Precentacion.Persona;

import Logica_Negocio.LogN_ClassAb_Persona;
import Logica_Negocio.LogN_Class_ObsevadoAuxiliar;
import Precentacion.FrmDi_ConLinFactura;
import java.beans.PropertyVetoException;
import java.security.Principal;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;


/**
 *
 * @author Ary
 */
public class FrmDi_ConPer extends javax.swing.JDialog implements Observer {

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    private int returnStatus = RET_CANCEL;
    
    private FrmIn_ListarPersona mObjFrmIn_LisPer;
    private FrmIn_AgrPer mObjFrmIn_AgrPer;
    
    private LogN_ClassAb_Persona mObjPerSel;
    

    /** Creates new form FrmDi_ConPer */
    public FrmDi_ConPer(java.awt.Window parent, 
            FrmIn_AgrPer xObjFrmIn_AgrPer, 
            FrmIn_ListarPersona xObjFrmIn_ListarPersona) {
        
        super(parent,java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        
        initComponents();
        
        //Formulario agregar Persona
        mObjFrmIn_AgrPer = xObjFrmIn_AgrPer;
        mObjFrmIn_AgrPer.setWinCon(this);
        mObjFrmIn_AgrPer.addObserver(this);
        InisFor(mObjFrmIn_AgrPer);
        
        //Formulario listar persona
        mObjFrmIn_LisPer = xObjFrmIn_ListarPersona;
        mObjFrmIn_LisPer.setWinCon(this);
        mObjFrmIn_LisPer.addObserver(this);
        InisFor(mObjFrmIn_LisPer);
        


        
        
        
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Btn_Cancelar1 = new javax.swing.JButton();
        Btn_Aceptar = new javax.swing.JButton();
        DexP_Prin = new javax.swing.JDesktopPane();
        jPanel5 = new javax.swing.JPanel();
        Btn_AgCli = new javax.swing.JToggleButton();
        Btn_LisCli = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        Lbl_DatCli = new javax.swing.JLabel();
        Lbl_PerSelec = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        Btn_Cancelar1.setFont(new java.awt.Font("Arial Black", 1, 13));
        Btn_Cancelar1.setForeground(new java.awt.Color(1, 1, 1));
        Btn_Cancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel_f2.png"))); // NOI18N
        Btn_Cancelar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.gray, null, java.awt.Color.gray));
        Btn_Cancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cancelar1ActionPerformed(evt);
            }
        });

        Btn_Aceptar.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Yes v3.png"))); // NOI18N
        Btn_Aceptar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.gray, null, java.awt.Color.gray));
        Btn_Aceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AceptarActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        buttonGroup1.add(Btn_AgCli);
        Btn_AgCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addusers.png"))); // NOI18N
        Btn_AgCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgCliActionPerformed(evt);
            }
        });

        buttonGroup1.add(Btn_LisCli);
        Btn_LisCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/bucar+.png"))); // NOI18N
        Btn_LisCli.setSelected(true);
        Btn_LisCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LisCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(Btn_LisCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_AgCli)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Btn_LisCli, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
            .addComponent(Btn_AgCli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Lbl_DatCli.setBackground(new java.awt.Color(255, 255, 204));
        Lbl_DatCli.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lbl_DatCli.setText("  Ary Gimenez");
        Lbl_DatCli.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lbl_DatCli.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Lbl_DatCli.setMaximumSize(new java.awt.Dimension(72, 27));
        Lbl_DatCli.setOpaque(true);

        Lbl_PerSelec.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_PerSelec.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Lbl_PerSelec.setForeground(java.awt.Color.white);
        Lbl_PerSelec.setText("Cliente Seleccionado");
        Lbl_PerSelec.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lbl_DatCli, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
            .addComponent(Lbl_PerSelec, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Lbl_PerSelec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_DatCli, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Cancelar1)
                .addContainerGap())
            .addComponent(DexP_Prin, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(DexP_Prin, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_Cancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, 0, 52, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void Btn_Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cancelar1ActionPerformed
        // TODO add your handling code here:
        this.doClose(FrmDi_ConLinFactura.RET_CANCEL);
}//GEN-LAST:event_Btn_Cancelar1ActionPerformed

    private void Btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AceptarActionPerformed
        doClose(FrmDi_ConLinFactura.RET_OK);
}//GEN-LAST:event_Btn_AceptarActionPerformed

    private void Btn_AgCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgCliActionPerformed
       mObjFrmIn_AgrPer.moveToFront();
}//GEN-LAST:event_Btn_AgCliActionPerformed

    private void Btn_LisCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LisCliActionPerformed
        // TODO add your handling code here:
        mObjFrmIn_LisPer.moveToFront();

}//GEN-LAST:event_Btn_LisCliActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        mObjFrmIn_LisPer.removObservador();
        setVisible(false);
        dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Aceptar;
    private javax.swing.JToggleButton Btn_AgCli;
    private javax.swing.JButton Btn_Cancelar1;
    private javax.swing.JToggleButton Btn_LisCli;
    private javax.swing.JDesktopPane DexP_Prin;
    private javax.swing.JLabel Lbl_DatCli;
    protected javax.swing.JLabel Lbl_PerSelec;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    private void InisFor (JInternalFrame Frm){

        Frm.setVisible(true);

        DexP_Prin.add(Frm);
        Frm.moveToFront(); // mueve acia delate el Formulario

        try {
            Frm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    @Override
    public void update(Observable o, Object arg) {
        if (! (o instanceof LogN_Class_ObsevadoAuxiliar))return;
        LogN_Class_ObsevadoAuxiliar ObjObAux = (LogN_Class_ObsevadoAuxiliar) o;
        if (ObjObAux.getmObjObservado() == mObjFrmIn_AgrPer || ObjObAux.getmObjObservado() == mObjFrmIn_LisPer){
            this.setPerSel((LogN_ClassAb_Persona)arg);
        }
    }
    
    public void setPerSel (LogN_ClassAb_Persona mObjPerSel){
        this.mObjPerSel = mObjPerSel;
        this.cargarPerSel(this.mObjPerSel);
    }

    private void cargarPerSel(LogN_ClassAb_Persona mObjPerSel) {
        String DatM = " →" + mObjPerSel.getmNum() + "←   " + mObjPerSel.getmRasSos();
        Lbl_DatCli.setText(DatM);
    }
    
    public LogN_ClassAb_Persona getPerSel (){
        return mObjPerSel;
    }
}
