/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmIn_ListarPersona.java
 *
 * Created on 13/03/2011, 05:35:52 PM
 */

package Precentacion.Persona;

import Logica_Negocio.Dominio.CPorNom.LogN_ClassAb_Contacto;
import Logica_Negocio.Dominio.Contacto.Dom_Class_Cel;
import Logica_Negocio.Dominio.Contacto.Dom_Class_Fax;
import Logica_Negocio.Dominio.Contacto.Dom_Class_Mail;
import Logica_Negocio.Dominio.Contacto.Dom_Class_Tel;
import Logica_Negocio.Dominio.Dom_Class_Saldo;
import Logica_Negocio.Filtros.Persona.LogN_Inter_FiltPersona;
import Logica_Negocio.LogN_ClassAb_PerExterna;
import Logica_Negocio.LogN_ClassAb_Persona;
import Logica_Negocio.LogN_Class_Fachada;
import Logica_Negocio.LogN_Class_ObsevadoAuxiliar;
import Logica_Negocio.Manejadora.jTabModel.LogN_ClassAb_ModeljTabPer;
import Logica_Negocio.MiExepcion.InputException;
import Precentacion.*;
import Precentacion.Model.jList.PersonalListModel;
import java.awt.Window;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Observer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author horacio
 */
public abstract  class FrmIn_ListarPersona extends javax.swing.JInternalFrame {
    protected LogN_Class_Fachada mObjFachada = LogN_Class_Fachada.getInstancia();
    protected LogN_ClassAb_ModeljTabPer mObjMTabPer;
    protected LogN_ClassAb_Persona mObjPerSel;
    protected Window mFrmCon;
    private Dom_Class_Saldo mObjSalSel;
    
    private LogN_Class_ObsevadoAuxiliar <FrmIn_ListarPersona> mObjObAux = 
            new LogN_Class_ObsevadoAuxiliar<FrmIn_ListarPersona>(this);
    /** Creates new form FrmIn_ListarPersona */
    public FrmIn_ListarPersona(Window mFrmCon) {
        this.mFrmCon = mFrmCon;
        mObjMTabPer = crearModjTabPer(null);
        mObjFachada.addObservadorPersona(mObjMTabPer);
        initComponents();
        
        Pan_Datos.setEnabled(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tab_Persona = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lis_BuscarPor = new javax.swing.JList();
        TxtF_Buscar = new javax.swing.JFormattedTextField();
        Btn_IniciarBusqueda = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Btn_CancelarBusqueda = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Lis_Pos = new javax.swing.JList();
        Pan_Datos = new javax.swing.JPanel();
        TxtA_Observacion = new javax.swing.JScrollPane();
        TxtA_Dir = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Lis_Contacto = new javax.swing.JList();
        Btn_ModContacto = new javax.swing.JButton();
        ComB_TipContacto = new javax.swing.JComboBox();
        PanSaldo = new javax.swing.JPanel();
        ComB_Saldo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        Lbl_CanSal = new javax.swing.JLabel();
        PanSaldo1 = new javax.swing.JPanel();
        TxtF_LimAcre = new javax.swing.JFormattedTextField();
        TxtF_LimDeu = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Btn_ModLimSaldo = new javax.swing.JButton();
        Btn_ModNot1 = new javax.swing.JButton();
        Btn_ModContacto1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenItm_Recibo = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        Tab_Persona.setModel(mObjMTabPer);
        Tab_Persona.getSelectionModel().addListSelectionListener(
            new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    Tab_PersonaValueChanged(event);
                }
            }
        );
        jScrollPane1.setViewportView(Tab_Persona);

        jPanel1.setBackground(new java.awt.Color(207, 228, 228));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Lis_BuscarPor.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Rason Social", "Cel", "Tel", "Direcion", "Rut" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Lis_BuscarPor.setSelectedIndex(0);
        Lis_BuscarPor.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                Lis_BuscarPorValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(Lis_BuscarPor);

        TxtF_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtF_BuscarKeyPressed(evt);
            }
        });

        Btn_IniciarBusqueda.setText("Iniciar");
        Btn_IniciarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IniciarBusquedaActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(13, 151, 239));
        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Búsqueda");
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(13, 151, 239));
        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Filtrar Por");
        jLabel8.setOpaque(true);

        Btn_CancelarBusqueda.setText("Cancelar");
        Btn_CancelarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarBusquedaActionPerformed(evt);
            }
        });

        Lis_Pos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Completo", "Al Principio", "Al Final", "No Comp" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Lis_Pos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                Lis_PosValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(Lis_Pos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(TxtF_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_IniciarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_CancelarBusqueda)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtF_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Btn_CancelarBusqueda, 0, 0, Short.MAX_VALUE)
                                    .addComponent(Btn_IniciarBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                .addContainerGap())
        );

        Pan_Datos.setBackground(new java.awt.Color(207, 228, 228));
        Pan_Datos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TxtA_Dir.setColumns(20);
        TxtA_Dir.setRows(5);
        TxtA_Observacion.setViewportView(TxtA_Dir);

        jLabel3.setBackground(new java.awt.Color(13, 151, 239));
        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Direccion");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(13, 151, 239));
        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Contacto");
        jLabel4.setOpaque(true);

        jScrollPane3.setViewportView(Lis_Contacto);

        Btn_ModContacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_ModContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModContactoActionPerformed(evt);
            }
        });

        ComB_TipContacto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Telefono", "Celular", "Fax", "Email" }));
        ComB_TipContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComB_TipContactoActionPerformed(evt);
            }
        });

        PanSaldo.setBackground(new java.awt.Color(13, 151, 239));

        ComB_Saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComB_SaldoActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(13, 151, 239));
        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Saldo:");
        jLabel5.setOpaque(true);

        Lbl_CanSal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Lbl_CanSal.setForeground(new java.awt.Color(255, 204, 204));
        Lbl_CanSal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_CanSal.setText("1");

        javax.swing.GroupLayout PanSaldoLayout = new javax.swing.GroupLayout(PanSaldo);
        PanSaldo.setLayout(PanSaldoLayout);
        PanSaldoLayout.setHorizontalGroup(
            PanSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComB_Saldo, 0, 151, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_CanSal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanSaldoLayout.setVerticalGroup(
            PanSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ComB_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5)
                .addComponent(Lbl_CanSal))
        );

        PanSaldo1.setBackground(new java.awt.Color(13, 151, 239));

        TxtF_LimAcre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtF_LimAcreActionPerformed(evt);
            }
        });
        TxtF_LimAcre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_LimAcreFocusLost(evt);
            }
        });
        TxtF_LimAcre.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                TxtF_LimAcreHierarchyChanged(evt);
            }
        });
        TxtF_LimAcre.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TxtF_LimAcrePropertyChange(evt);
            }
        });
        TxtF_LimAcre.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                TxtF_LimAcreVetoableChange(evt);
            }
        });

        TxtF_LimDeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtF_LimDeuActionPerformed(evt);
            }
        });
        TxtF_LimDeu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtF_LimDeuFocusLost(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(13, 151, 239));
        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("L.Acree");
        jLabel6.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(13, 151, 239));
        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("L.Deu");
        jLabel9.setOpaque(true);

        Btn_ModLimSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_ModLimSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModLimSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanSaldo1Layout = new javax.swing.GroupLayout(PanSaldo1);
        PanSaldo1.setLayout(PanSaldo1Layout);
        PanSaldo1Layout.setHorizontalGroup(
            PanSaldo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSaldo1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtF_LimAcre, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtF_LimDeu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_ModLimSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanSaldo1Layout.setVerticalGroup(
            PanSaldo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSaldo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(TxtF_LimAcre)
                .addComponent(jLabel6)
                .addComponent(TxtF_LimDeu)
                .addComponent(jLabel9))
            .addComponent(Btn_ModLimSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        Btn_ModNot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_ModNot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModNot1ActionPerformed(evt);
            }
        });

        Btn_ModContacto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_ModContacto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModContacto1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pan_DatosLayout = new javax.swing.GroupLayout(Pan_Datos);
        Pan_Datos.setLayout(Pan_DatosLayout);
        Pan_DatosLayout.setHorizontalGroup(
            Pan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pan_DatosLayout.createSequentialGroup()
                        .addGroup(Pan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pan_DatosLayout.createSequentialGroup()
                                .addGroup(Pan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtA_Observacion)
                                    .addComponent(PanSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Pan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn_ModContacto, 0, 0, Short.MAX_VALUE)
                                    .addComponent(Btn_ModNot1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(Pan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                    .addGroup(Pan_DatosLayout.createSequentialGroup()
                        .addComponent(PanSaldo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComB_TipContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_ModContacto1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Pan_DatosLayout.setVerticalGroup(
            Pan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pan_DatosLayout.createSequentialGroup()
                .addGroup(Pan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pan_DatosLayout.createSequentialGroup()
                        .addGroup(Pan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_ModNot1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtA_Observacion, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(Pan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PanSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_ModContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanSaldo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_ModContacto1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComB_TipContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jMenu1.setText("Acciones");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Modificar");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Eliminar");
        jMenu1.add(jMenuItem5);

        jMenu2.setText("Emitir");

        jMenuItem2.setText("Estado Cuenta");
        jMenu2.add(jMenuItem2);

        MenItm_Recibo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        MenItm_Recibo.setText("Recibo");
        MenItm_Recibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenItm_ReciboActionPerformed(evt);
            }
        });
        jMenu2.add(MenItm_Recibo);

        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Pan_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pan_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lis_BuscarPorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_Lis_BuscarPorValueChanged
//         TODO add your handling code here:
//        mObjFilSelect = (LogN_Inter_Filtrar) Lis_BuscarPor.getSelectedValue();
//
//        this.cargarFiltrador(mObjFilSelect);
}//GEN-LAST:event_Lis_BuscarPorValueChanged

    private void TxtF_BuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtF_BuscarKeyPressed
        // TODO add your handling code here:

//        if (KeyEvent.VK_ENTER == evt.getKeyCode())filtrar();
}//GEN-LAST:event_TxtF_BuscarKeyPressed

    private void Btn_IniciarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IniciarBusquedaActionPerformed
        // TODO add your handling code here:
//        filtrar();
}//GEN-LAST:event_Btn_IniciarBusquedaActionPerformed

    private void Btn_CancelarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarBusquedaActionPerformed
//        // TODO add your handling code here:
//        CanFil();
}//GEN-LAST:event_Btn_CancelarBusquedaActionPerformed

    private void Lis_PosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_Lis_PosValueChanged
        // TODO add your handling code here:
//        this.selecPosFil((short) Lis_Pos.getSelectedIndex());
}//GEN-LAST:event_Lis_PosValueChanged

    private void Btn_ModNot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModNot1ActionPerformed
        // TODO add your handling code here:
        //this.ModificarDir();
        
    }//GEN-LAST:event_Btn_ModNot1ActionPerformed

    private void TxtF_LimDeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtF_LimDeuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_LimDeuActionPerformed

    private void ComB_TipContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComB_TipContactoActionPerformed
        // TODO add your handling code here:
        cargarContacto(mObjPerSel, ComB_TipContacto.getSelectedIndex());
    }//GEN-LAST:event_ComB_TipContactoActionPerformed

    private void Btn_ModContacto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModContacto1ActionPerformed
        // TODO add your handling code here:
        modificarContacto(mObjPerSel, ComB_TipContacto.getSelectedIndex());
    }//GEN-LAST:event_Btn_ModContacto1ActionPerformed

    private void TxtF_LimAcreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtF_LimAcreActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TxtF_LimAcreActionPerformed

    private void Btn_ModContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModContactoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Btn_ModContactoActionPerformed

    private void ComB_SaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComB_SaldoActionPerformed
        // TODO add your handling code here:
        cargarSaldo((Dom_Class_Saldo)ComB_Saldo.getSelectedItem());
    }//GEN-LAST:event_ComB_SaldoActionPerformed

    private void TxtF_LimAcreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_LimAcreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_LimAcreFocusLost

    private void TxtF_LimDeuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtF_LimDeuFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtF_LimDeuFocusLost

    private void TxtF_LimAcreVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_TxtF_LimAcreVetoableChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtF_LimAcreVetoableChange

    private void TxtF_LimAcrePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TxtF_LimAcrePropertyChange
        // TODO add your handling code here:

       
    }//GEN-LAST:event_TxtF_LimAcrePropertyChange

    private void TxtF_LimAcreHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_TxtF_LimAcreHierarchyChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_TxtF_LimAcreHierarchyChanged

    private void Btn_ModLimSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModLimSaldoActionPerformed
        // TODO add your handling code here:
        float LimAcree = ((Number) TxtF_LimAcre.getValue()).floatValue(), 
                LimDeud = ((Number) TxtF_LimDeu.getValue()).floatValue();
        
        if (mObjSalSel.getmLimAceedor() != LimAcree){
            try {
                modificarSaldo(true, LimAcree);
            } catch (InputException ex) {
                JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                TxtF_LimAcre.setValue(mObjSalSel.getmLimAceedor());
            }
        } else if (mObjSalSel.getmLimDeudor() != LimDeud){
            try {
                modificarSaldo(false, LimDeud);
            } catch (InputException ex) {
                JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                TxtF_LimDeu.setValue(mObjSalSel.getmLimDeudor());
            }
        }else{
            JOptionPane.showMessageDialog(this, "No a modificado los limites del saldo");
        }
        
    }//GEN-LAST:event_Btn_ModLimSaldoActionPerformed

    private void MenItm_ReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenItm_ReciboActionPerformed
        // TODO add your handling code here:
        if (mObjPerSel == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente para emitir el recibo");
            return;
        }
        FrmDi_Resibo FrmRes = new FrmDi_Resibo(this.mFrmCon, mObjPerSel);
        FrmRes.setVisible(true);
         
        
    }//GEN-LAST:event_MenItm_ReciboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_CancelarBusqueda;
    private javax.swing.JButton Btn_IniciarBusqueda;
    private javax.swing.JButton Btn_ModContacto;
    private javax.swing.JButton Btn_ModContacto1;
    private javax.swing.JButton Btn_ModLimSaldo;
    private javax.swing.JButton Btn_ModNot1;
    private javax.swing.JComboBox ComB_Saldo;
    private javax.swing.JComboBox ComB_TipContacto;
    private javax.swing.JLabel Lbl_CanSal;
    private javax.swing.JList Lis_BuscarPor;
    private javax.swing.JList Lis_Contacto;
    private javax.swing.JList Lis_Pos;
    private javax.swing.JMenuItem MenItm_Recibo;
    private javax.swing.JPanel PanSaldo;
    private javax.swing.JPanel PanSaldo1;
    private javax.swing.JPanel Pan_Datos;
    private javax.swing.JTable Tab_Persona;
    private javax.swing.JTextArea TxtA_Dir;
    private javax.swing.JScrollPane TxtA_Observacion;
    private javax.swing.JFormattedTextField TxtF_Buscar;
    private javax.swing.JFormattedTextField TxtF_LimAcre;
    private javax.swing.JFormattedTextField TxtF_LimDeu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables

    protected abstract LogN_ClassAb_ModeljTabPer crearModjTabPer (LogN_Inter_FiltPersona xObFil);

    
    private void Tab_PersonaValueChanged(ListSelectionEvent evt){
        LogN_ClassAb_Persona xObjPer = mObjMTabPer.getPer(Tab_Persona.getSelectedRow());
        if (xObjPer == null) return;
        mObjPerSel =  xObjPer;
        cargarPersona(xObjPer);
        Notifiar(xObjPer);
        
        
    }
    // <editor-fold defaultstate="collapsed" desc="Metodos Persona">    
    
        private void cargarPersona (LogN_ClassAb_Persona xObjPersona){
            
            mObjPerSel = xObjPersona;
            TxtA_Dir.setText(xObjPersona.getmDir());
            listarSaldo(xObjPersona);
            cargarContacto(xObjPersona, 0);
        }

        private void ModificarDir(LogN_ClassAb_Persona xObjPer) {

             if ( xObjPer == null) {
                 JOptionPane.showMessageDialog(this, "Debe Seleccionar alguna persona para modificar su direccion");
                 return;
             }
             String Dir = TxtA_Dir.getText();
             if (xObjPer.getmDir().equals(Dir)){
                 JOptionPane.showMessageDialog(this, "No a modificado la direccion");
                 return;
             }

             LogN_ClassAb_Persona ObjPerNu = xObjPer.duplicar();

             try {
                mObjFachada.ModPersonaEx((LogN_ClassAb_PerExterna)xObjPer,(LogN_ClassAb_PerExterna) ObjPerNu);
            } catch (InputException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Metodos Saldo">
        private void listarSaldo (LogN_ClassAb_Persona xObjPersona){
            ArrayList <Dom_Class_Saldo> ColSaldo = xObjPersona.getmColSaldo();
            int CanSal = ColSaldo.size();
            ComB_Saldo.setModel(new DefaultComboBoxModel(ColSaldo.toArray()));

            Lbl_CanSal.setText("" + CanSal);
            if(CanSal > 0) ComB_Saldo.setSelectedIndex(0);
            if(ColSaldo.size() > 0) cargarSaldo(ColSaldo.get(0));
            
        }
        private void cargarSaldo (Dom_Class_Saldo xObjSaldo){
          mObjSalSel = xObjSaldo;
          TxtF_LimAcre.setValue(xObjSaldo.getmLimAceedor());
          TxtF_LimDeu.setValue(xObjSaldo.getmLimDeudor());
        }
        
        private void modificarSaldo (boolean xAcreedor, float xValLim) throws InputException{
            Dom_Class_Saldo ObjSaldo = mObjSalSel.duplicar();
            if (xAcreedor){
                if (xValLim == ObjSaldo.getmLimAceedor()) return;
                ObjSaldo.setmLimAceedor(xValLim);
            } else {
                if (xValLim == ObjSaldo.getmLimDeudor()) return;
                ObjSaldo.setmLimDeudor(xValLim);
            }

            mObjFachada.modifSaldo(mObjPerSel, ObjSaldo);
 

        }
    // </editor-fold>
        
    // <editor-fold defaultstate="collapsed" desc="Metodos Contacto">
        
        private void cargarContacto (LogN_ClassAb_Persona xObjPersona, int TipCon){
        ArrayList ColContacto = null;
        
        switch (TipCon){
            case 0: ColContacto = xObjPersona.getmColTel(); break;
            case 1: ColContacto = xObjPersona.getmColCel(); break;
            case 2: ColContacto = xObjPersona.getmColFax(); break;
            case 3: ColContacto = xObjPersona.getmColMail(); break;
            default: return;
        }
        Lis_Contacto.setModel(new PersonalListModel(ColContacto, PersonalComboBoxMedel.Sin_Orden, null));
        }
        
        private void modificarContacto (LogN_ClassAb_Persona xObjPersona ,int xTipCon){
             if (xObjPersona == null) {
                 JOptionPane.showMessageDialog(this, "Debe Seleccionar alguna persona para modificar sus contacto");
                 return;
             }
             FrmDi_Contacto FrmCreXNom;
             HashMap <Integer, LogN_ClassAb_Contacto> MapContacto = new HashMap<Integer, LogN_ClassAb_Contacto>();
             ArrayList ColCon = new ArrayList();

             switch (xTipCon){
                case 0: //Opcion Telefono
                    ColCon = xObjPersona.getmColTel();
                    FrmCreXNom = new FrmDi_Contacto(mFrmCon,"Telefono",ColCon ) {
                        @Override
                        protected LogN_ClassAb_Contacto cargarContacto() throws InputException {
                            Dom_Class_Tel ObjTel = new Dom_Class_Tel
                            (TxtF_Modificar.getText(), TxtA_Detalle.getText());
                            ObjTel.validar();
                            return ObjTel;
                        }
                    } ;

                break;
                case 1: //Celular
                    ColCon = xObjPersona.getmColCel();
                    FrmCreXNom = new FrmDi_Contacto(mFrmCon, "Celular", ColCon) {
                        @Override
                        protected LogN_ClassAb_Contacto cargarContacto() throws InputException {
                            Dom_Class_Cel ObjCel = new Dom_Class_Cel
                            (TxtF_Modificar.getText(), TxtA_Detalle.getText());
                            ObjCel.validar();
                            return ObjCel;
                        }
                    } ;
                break;
                case 2: 
                    ColCon = xObjPersona.getmColFax();
                    FrmCreXNom = new FrmDi_Contacto(mFrmCon, "Fax", ColCon) {
                        @Override
                        protected LogN_ClassAb_Contacto cargarContacto() throws InputException {
                            Dom_Class_Fax ObjFax = new Dom_Class_Fax
                            (TxtF_Modificar.getText(), TxtA_Detalle.getText());
                            ObjFax.validar();
                            return ObjFax;
                        }
                    } ;
                break;
                case 3: 
                    ColCon = xObjPersona.getmColMail();
                    FrmCreXNom = new FrmDi_Contacto(mFrmCon, "Mail", ColCon) {
                        @Override
                        protected LogN_ClassAb_Contacto cargarContacto() throws InputException {
                            Dom_Class_Mail ObjMail = new Dom_Class_Mail
                            (TxtF_Modificar.getText(), TxtA_Detalle.getText());
                            ObjMail.validar();
                            return ObjMail;
                        }
                    } ;
                break;
                default: return;
             }
            FrmCreXNom.setVisible(true);

            for (Object o : ColCon){
                LogN_ClassAb_Contacto ObjContacto = (LogN_ClassAb_Contacto) o;
                MapContacto.put(xObjPersona.getmNum(), ObjContacto);  // Creo que esta mal

            }

            if(FrmDi_CreaPorNom.RET_OK != FrmCreXNom.getReturnStatus()) return;// Pregunto si confirmo los cambios

            for (LogN_Class_Accion<LogN_ClassAb_Contacto> ObjAcc  : FrmCreXNom.getAccion()){
                LogN_ClassAb_Contacto ObjCon = ObjAcc.getmAccionar();
                switch (ObjAcc.mAccionActual) {
                    case LogN_Class_Accion.Agreger:
                        try {
                            mObjFachada.altaContacto((LogN_ClassAb_PerExterna)xObjPersona, ObjCon);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }
                    break;
                    case LogN_Class_Accion.Modificar:

                        LogN_ClassAb_Contacto ObjConAn = MapContacto.get(ObjCon.getNum());


                        try {
                            mObjFachada.modifContacto(ObjConAn, ObjCon);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }

                    break;
                    case LogN_Class_Accion.Eliminar:
                        try {
                            mObjFachada.bajaContacto((LogN_ClassAb_PerExterna)xObjPersona, ObjCon);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }


                    break;
                }// Fin switch
            } //Fin for

            this.cargarContacto(xObjPersona, xTipCon);
        
        } // Fin modificarContacto
    
    // </editor-fold>
        
    // <editor-fold defaultstate="collapsed" desc="Metodo Observador Auliliar">
        public synchronized void deleteObserver(Observer o) {
            mObjObAux.deleteObserver(o);
        }

        public synchronized int countObservers() {
            return mObjObAux.countObservers();
        }

        public synchronized void addObserver(Observer o) {
            mObjObAux.addObserver(o);
        }

        public FrmIn_ListarPersona getmObjObservado() {
            return mObjObAux.getmObjObservado();
        }

        public LogN_Class_Accion getmObjAccion() {
            return mObjObAux.getmObjAccion();
        }

        public void Notifiar(Object arg) {
            mObjObAux.Notifiar(arg);
        }
    // </editor-fold>

    public void setWinCon(Window mFrmCon) {
        this.mFrmCon = mFrmCon;
    }

    public void removObservador() {
        mObjFachada.removObservadorPersona(mObjMTabPer);
    }
    
    
    


    
}
