/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJInternalFrame.java
 *
 * Created on 13/03/2011, 03:22:00 PM
 */

package Precentacion.Persona;

import Logica_Negocio.Dominio.CPorNom.LogN_ClassAb_Contacto;
import Logica_Negocio.Dominio.CPorNom.LogN_ClassAb_CrePorNom;
import Logica_Negocio.Dominio.Contacto.Dom_Class_Cel;
import Logica_Negocio.Dominio.Contacto.Dom_Class_Fax;
import Logica_Negocio.Dominio.Contacto.Dom_Class_Mail;
import Logica_Negocio.Dominio.Dom_Class_Pais;
import Logica_Negocio.Dominio.Dom_Class_ProvinDepar;
import Logica_Negocio.Dominio.Contacto.Dom_Class_Tel;
import Logica_Negocio.Dominio.Dom_Class_Moneda;
import Logica_Negocio.Dominio.Dom_Class_Saldo;
import Logica_Negocio.Dominio.FechPago.Dom_Class_FechPAño;
import Logica_Negocio.Dominio.FechPago.Dom_Class_FechPDiario;
import Logica_Negocio.Dominio.FechPago.Dom_Class_FechPMensual;
import Logica_Negocio.LogN_ClassAb_FechPag;
import Logica_Negocio.LogN_ClassAb_PerExterna;
import Logica_Negocio.LogN_ClassAb_Persona;
import Logica_Negocio.LogN_Class_Fachada;
import Logica_Negocio.LogN_Class_ObsevadoAuxiliar;
import Logica_Negocio.MiExepcion.InputException;
import Precentacion.FrmDi_Contacto;
import Precentacion.FrmDi_CreaPorNom;
import Precentacion.FrmDi_Moneda;
import Precentacion.LogN_Class_Accion;
import Precentacion.Model.jTabel.MedeljTabSaldo;
import Precentacion.PersonalComboBoxMedel;
import java.awt.Window;
import java.util.ArrayList;
import java.util.Date;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author Willi@m
 */
public abstract class FrmIn_AgrPer extends javax.swing.JInternalFrame {
    private LogN_Class_Fachada mObjFachada = LogN_Class_Fachada.getInstancia();

    protected ArrayList <Dom_Class_Tel> mColTel;
    private int mNumTel = 0;
    protected ArrayList <Dom_Class_Cel> mColCel;
    private int mNumCel = 0;
    protected ArrayList <Dom_Class_Fax> mColFax;
    private int mNumFax = 0;
    protected ArrayList <Dom_Class_Mail> mColMail;
    private int mNumMail = 0;


    private ArrayList <Dom_Class_Saldo> mColSaldo;
    private MedeljTabSaldo mObjModelJTSaldo; //Ta mal el nombre
    private Dom_Class_Saldo mObjSaldo;

    private PersonalComboBoxMedel <Dom_Class_Pais> mObjModComB_Pais;
    private PersonalComboBoxMedel <Dom_Class_ProvinDepar> mObjModComB_ProvDep;
    private PersonalComboBoxMedel <Dom_Class_Tel> mObjModComB_Tel;    
    private PersonalComboBoxMedel <Dom_Class_Cel> mObjModComB_Cel;
    private PersonalComboBoxMedel <Dom_Class_Fax> mObjModComB_Fax;
    private PersonalComboBoxMedel <Dom_Class_Mail> mObjModComB_Mail;

    private PersonalComboBoxMedel <Dom_Class_Moneda> mObjModComB_Moneda;


    private Window mFrmCon;
    
    protected Dom_Class_Pais mObjPaisSel;
    protected Dom_Class_ProvinDepar mObjProvDepSel;
    
    private LogN_Class_ObsevadoAuxiliar <FrmIn_AgrPer> mObjObAux = new LogN_Class_ObsevadoAuxiliar<FrmIn_AgrPer>(this);

    private Dom_Class_Moneda mObjMonedaSelec;

    /** Creates new form NewJInternalFrame */
    public FrmIn_AgrPer(Window mFrmCon) {
        this.mFrmCon = mFrmCon;
        initComponents();

        this.cargarPais();
        this.CargarMoneda();
        this.CargarSaldo();
        limpiarMenSaldo();
        Limpiar();
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GruRd_Saldo = new javax.swing.ButtonGroup();
        Pan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Txt_RazonSocial = new javax.swing.JTextField();
        Txt_Localidad = new javax.swing.JTextField();
        Txt_Dirreccion = new javax.swing.JTextField();
        TxtF_Rut = new Utilidades.JFormattedText();
        ComB_CondIva = new javax.swing.JComboBox();
        TxtF_NumDocumento = new Utilidades.JFormattedText();
        ComB_TipoDocumento = new javax.swing.JComboBox();
        ComB_Pais = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Lbl_Numero = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Btn_ModPais = new javax.swing.JButton();
        ComB_ProvDep = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        Btn_ModCel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ComB_Celular = new javax.swing.JComboBox();
        Btn_ModDep = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        ComB_Tel = new javax.swing.JComboBox();
        Btn_ModTel = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ComB_Fax = new javax.swing.JComboBox();
        Btn_ModFax = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        ComB_Email = new javax.swing.JComboBox();
        Btn_ModMail = new javax.swing.JButton();
        Btn_Aceptar = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();
        Pan_Slado = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tab_Saldo = new javax.swing.JTable();
        Btn_AgreSaldo = new javax.swing.JButton();
        Btn_BajaSaldo = new javax.swing.JButton();
        ComB_Moneda = new javax.swing.JComboBox();
        TxtF_SaldoMonto = new Utilidades.JFormattedText();
        Or_Deudor = new javax.swing.JRadioButton();
        Or_Acreedor = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        TxtF_LimDeud = new Utilidades.JFormattedText();
        TxtF_LimAcree = new Utilidades.JFormattedText();
        Btn_ModMon = new javax.swing.JButton();
        Pan_Slado2 = new javax.swing.JPanel();
        Lbl_Dia = new javax.swing.JLabel();
        Lbl_TipFechPag = new javax.swing.JLabel();
        Lbl_Intervalo = new javax.swing.JLabel();
        ComB_TipFechPab = new javax.swing.JComboBox();
        Spi_Intervalo = new javax.swing.JSpinner();
        Che_FechPago = new javax.swing.JCheckBox();
        Lbl_Mes = new javax.swing.JLabel();
        ComB_Dia = new javax.swing.JComboBox();
        ComB_Mes = new javax.swing.JComboBox();
        Lbl_Aviso = new javax.swing.JLabel();
        Spi_Aviso = new javax.swing.JSpinner();
        Lbl_Intervalo1 = new javax.swing.JLabel();
        Dat_FechIniPago = new com.toedter.calendar.JDateChooser();

        Pan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(13, 151, 239));
        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tip. Documento");
        jLabel4.setOpaque(true);

        Txt_RazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_RazonSocialActionPerformed(evt);
            }
        });
        Txt_RazonSocial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Txt_RazonSocialFocusGained(evt);
            }
        });

        Txt_Localidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_LocalidadActionPerformed(evt);
            }
        });
        Txt_Localidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Txt_LocalidadFocusGained(evt);
            }
        });

        Txt_Dirreccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DirreccionActionPerformed(evt);
            }
        });
        Txt_Dirreccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Txt_DirreccionFocusGained(evt);
            }
        });

        ComB_CondIva.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Responsable inscripto", "Consumidor final" }));

        ComB_TipoDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CI", "Pasaporte", "DNI" }));
        ComB_TipoDocumento.setNextFocusableComponent(ComB_Pais);
        ComB_TipoDocumento.setOpaque(false);
        ComB_TipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComB_TipoDocumentoActionPerformed(evt);
            }
        });
        ComB_TipoDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ComB_TipoDocumentoFocusLost(evt);
            }
        });

        ComB_Pais.setNextFocusableComponent(Btn_ModPais);
        ComB_Pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComB_PaisActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(13, 151, 239));
        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RAZON SOCIAL");
        jLabel3.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numero");
        jLabel1.setOpaque(true);

        Lbl_Numero.setBackground(new java.awt.Color(255, 255, 153));
        Lbl_Numero.setForeground(new java.awt.Color(102, 102, 102));
        Lbl_Numero.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Lbl_Numero.setText("1");
        Lbl_Numero.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        Lbl_Numero.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(13, 151, 239));
        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NUM. Documento");
        jLabel5.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(13, 151, 239));
        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Direccion:");
        jLabel6.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(13, 151, 239));
        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Localidad:");
        jLabel11.setOpaque(true);

        jLabel19.setBackground(new java.awt.Color(13, 151, 239));
        jLabel19.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Condicion IVA");
        jLabel19.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(13, 151, 239));
        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rut");
        jLabel7.setOpaque(true);

        jLabel13.setBackground(new java.awt.Color(13, 151, 239));
        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Pais");
        jLabel13.setOpaque(true);

        Btn_ModPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_ModPais.setNextFocusableComponent(ComB_ProvDep);
        Btn_ModPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModPaisActionPerformed(evt);
            }
        });

        ComB_ProvDep.setNextFocusableComponent(Btn_ModDep);
        ComB_ProvDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComB_ProvDepActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(13, 151, 239));
        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Dep. / Provincia");
        jLabel14.setOpaque(true);

        Btn_ModCel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_ModCel.setNextFocusableComponent(ComB_Tel);
        Btn_ModCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModCelActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(13, 151, 239));
        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Celular");
        jLabel10.setOpaque(true);

        ComB_Celular.setNextFocusableComponent(Btn_ModCel);

        Btn_ModDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_ModDep.setNextFocusableComponent(ComB_Celular);
        Btn_ModDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModDepActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(13, 151, 239));
        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Telefono");
        jLabel15.setOpaque(true);

        ComB_Tel.setNextFocusableComponent(Btn_ModTel);

        Btn_ModTel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_ModTel.setNextFocusableComponent(ComB_Fax);
        Btn_ModTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModTelActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(13, 151, 239));
        jLabel16.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("FAX");
        jLabel16.setOpaque(true);

        ComB_Fax.setNextFocusableComponent(Btn_ModFax);
        ComB_Fax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComB_FaxActionPerformed(evt);
            }
        });

        Btn_ModFax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_ModFax.setNextFocusableComponent(ComB_Email);
        Btn_ModFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModFaxActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(13, 151, 239));
        jLabel17.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Email");
        jLabel17.setOpaque(true);

        ComB_Email.setNextFocusableComponent(Btn_ModMail);

        Btn_ModMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_ModMail.setAlignmentX(Btn_ModDep.getAlignmentX());
        Btn_ModMail.setAlignmentY(Btn_ModDep.getAlignmentY());
        Btn_ModMail.setNextFocusableComponent(ComB_Moneda);
        Btn_ModMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModMailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanLayout = new javax.swing.GroupLayout(Pan);
        Pan.setLayout(PanLayout);
        PanLayout.setHorizontalGroup(
            PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(TxtF_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ComB_CondIva, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(TxtF_NumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ComB_TipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                    .addComponent(Txt_Dirreccion, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                    .addGroup(PanLayout.createSequentialGroup()
                        .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Txt_RazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(Txt_Localidad, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanLayout.createSequentialGroup()
                                .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ComB_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_ModTel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComB_Fax, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_ModFax, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComB_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanLayout.createSequentialGroup()
                                .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComB_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(Btn_ModPais, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComB_ProvDep, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(Btn_ModDep, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(ComB_Celular, 0, 162, Short.MAX_VALUE))))
                        .addGap(12, 12, 12)
                        .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_ModCel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(Btn_ModMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, Short.MAX_VALUE))))
                .addContainerGap())
        );
        PanLayout.setVerticalGroup(
            PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanLayout.createSequentialGroup()
                .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Lbl_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Txt_RazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addComponent(Txt_Dirreccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel19)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtF_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComB_CondIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtF_NumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComB_TipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(3, 3, 3)
                        .addComponent(ComB_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(3, 3, 3)
                        .addComponent(ComB_ProvDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(3, 3, 3)
                        .addComponent(ComB_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Btn_ModDep)
                    .addComponent(Btn_ModPais, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_ModCel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_ModMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComB_Fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Btn_ModTel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ComB_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(ComB_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Btn_ModFax, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel10.getAccessibleContext().setAccessibleDescription("");

        Btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addusers.png"))); // NOI18N
        Btn_Aceptar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Btn_Aceptar.setNextFocusableComponent(Btn_Cancelar);
        Btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AceptarActionPerformed(evt);
            }
        });

        Btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel_f2.png"))); // NOI18N
        Btn_Cancelar.setNextFocusableComponent(Txt_RazonSocial);
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });

        Pan_Slado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saldo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        jScrollPane3.setBackground(new java.awt.Color(13, 151, 239));

        Tab_Saldo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hcree.", "Monto", "L. Acree", "L. Deud"
            }
        ));
        Tab_Saldo.getSelectionModel().addListSelectionListener(
            new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    Tab_SaldoValueChanged(event);
                }
            }
        );

        Tab_Saldo.setAutoResizeMode(Tab_Saldo.AUTO_RESIZE_OFF);
        Tab_Saldo.doLayout();
        jScrollPane3.setViewportView(Tab_Saldo);

        Btn_AgreSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_db_add.png"))); // NOI18N
        Btn_AgreSaldo.setNextFocusableComponent(Btn_BajaSaldo);
        Btn_AgreSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgreSaldoActionPerformed(evt);
            }
        });

        Btn_BajaSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Crystal_Clear_action_db_remove.png"))); // NOI18N
        Btn_BajaSaldo.setNextFocusableComponent(Btn_Aceptar);
        Btn_BajaSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BajaSaldoActionPerformed(evt);
            }
        });

        ComB_Moneda.setNextFocusableComponent(Btn_ModMon);
        ComB_Moneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComB_MonedaActionPerformed(evt);
            }
        });

        TxtF_SaldoMonto.setNextFocusableComponent(TxtF_LimDeud);

        Or_Deudor.setBackground(new java.awt.Color(13, 151, 239));
        GruRd_Saldo.add(Or_Deudor);
        Or_Deudor.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Or_Deudor.setForeground(new java.awt.Color(255, 255, 255));
        Or_Deudor.setSelected(true);
        Or_Deudor.setText("Deudor");

        Or_Acreedor.setBackground(new java.awt.Color(13, 151, 239));
        GruRd_Saldo.add(Or_Acreedor);
        Or_Acreedor.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Or_Acreedor.setForeground(new java.awt.Color(255, 255, 255));
        Or_Acreedor.setText("Acreedor");
        Or_Acreedor.setNextFocusableComponent(Btn_AgreSaldo);

        jLabel23.setBackground(new java.awt.Color(13, 151, 239));
        jLabel23.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Moneda");
        jLabel23.setOpaque(true);

        jLabel24.setBackground(new java.awt.Color(13, 151, 239));
        jLabel24.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Monto");
        jLabel24.setOpaque(true);

        jLabel25.setBackground(new java.awt.Color(13, 151, 239));
        jLabel25.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Limites");
        jLabel25.setOpaque(true);

        Btn_ModMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addedit.png"))); // NOI18N
        Btn_ModMon.setNextFocusableComponent(TxtF_SaldoMonto);
        Btn_ModMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModMonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pan_SladoLayout = new javax.swing.GroupLayout(Pan_Slado);
        Pan_Slado.setLayout(Pan_SladoLayout);
        Pan_SladoLayout.setHorizontalGroup(
            Pan_SladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_SladoLayout.createSequentialGroup()
                .addGroup(Pan_SladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Btn_BajaSaldo, 0, 0, Short.MAX_VALUE)
                    .addComponent(Btn_AgreSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pan_SladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pan_SladoLayout.createSequentialGroup()
                        .addGroup(Pan_SladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComB_Moneda, 0, 138, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_ModMon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pan_SladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtF_SaldoMonto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pan_SladoLayout.createSequentialGroup()
                            .addGroup(Pan_SladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtF_LimDeud)
                                .addComponent(Or_Deudor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(Pan_SladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtF_LimAcree)
                                .addComponent(Or_Acreedor, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        Pan_SladoLayout.setVerticalGroup(
            Pan_SladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pan_SladoLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(Pan_SladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pan_SladoLayout.createSequentialGroup()
                        .addGroup(Pan_SladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pan_SladoLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComB_Moneda, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Btn_ModMon, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtF_SaldoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel25)
                        .addGap(3, 3, 3)
                        .addGroup(Pan_SladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtF_LimDeud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtF_LimAcree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Pan_SladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Or_Deudor)
                            .addComponent(Or_Acreedor)))
                    .addGroup(Pan_SladoLayout.createSequentialGroup()
                        .addComponent(Btn_AgreSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_BajaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Pan_Slado2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        Lbl_Dia.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_Dia.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Lbl_Dia.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Dia.setText("Dia");
        Lbl_Dia.setOpaque(true);

        Lbl_TipFechPag.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_TipFechPag.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Lbl_TipFechPag.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_TipFechPag.setText("Periodo");
        Lbl_TipFechPag.setOpaque(true);

        Lbl_Intervalo.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_Intervalo.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Lbl_Intervalo.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Intervalo.setText("Intervalo");
        Lbl_Intervalo.setOpaque(true);

        ComB_TipFechPab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diario", "Mensual", "Anual" }));
        ComB_TipFechPab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComB_TipFechPabActionPerformed(evt);
            }
        });

        Spi_Intervalo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        Che_FechPago.setBackground(new java.awt.Color(13, 151, 239));
        Che_FechPago.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Che_FechPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Che_FechPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Che_FechPagoActionPerformed(evt);
            }
        });

        Lbl_Mes.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_Mes.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Lbl_Mes.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Mes.setText("Mes");
        Lbl_Mes.setOpaque(true);

        ComB_Dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        ComB_Dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComB_DiaActionPerformed(evt);
            }
        });

        ComB_Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        Lbl_Aviso.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_Aviso.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Lbl_Aviso.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Aviso.setText("Aviso");
        Lbl_Aviso.setOpaque(true);

        Spi_Aviso.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        Lbl_Intervalo1.setBackground(new java.awt.Color(13, 151, 239));
        Lbl_Intervalo1.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Lbl_Intervalo1.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Intervalo1.setText("Inicio");
        Lbl_Intervalo1.setOpaque(true);

        javax.swing.GroupLayout Pan_Slado2Layout = new javax.swing.GroupLayout(Pan_Slado2);
        Pan_Slado2.setLayout(Pan_Slado2Layout);
        Pan_Slado2Layout.setHorizontalGroup(
            Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_Slado2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Che_FechPago, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComB_TipFechPab, 0, 92, Short.MAX_VALUE)
                    .addComponent(Lbl_TipFechPag, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lbl_Intervalo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dat_FechIniPago, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Spi_Intervalo)
                    .addComponent(Lbl_Intervalo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lbl_Mes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComB_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComB_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Spi_Aviso)
                    .addComponent(Lbl_Aviso))
                .addContainerGap())
        );
        Pan_Slado2Layout.setVerticalGroup(
            Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_Slado2Layout.createSequentialGroup()
                .addGroup(Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Pan_Slado2Layout.createSequentialGroup()
                            .addComponent(Lbl_Aviso)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Spi_Aviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Pan_Slado2Layout.createSequentialGroup()
                                .addComponent(Lbl_Dia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComB_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Pan_Slado2Layout.createSequentialGroup()
                                .addGroup(Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_Intervalo)
                                    .addComponent(Lbl_Mes))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Spi_Intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComB_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pan_Slado2Layout.createSequentialGroup()
                        .addGroup(Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_TipFechPag)
                            .addComponent(Lbl_Intervalo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pan_Slado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dat_FechIniPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComB_TipFechPab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Che_FechPago, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_Cancelar, 0, 0, Short.MAX_VALUE)
                            .addComponent(Btn_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pan_Slado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pan_Slado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Pan_Slado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Aceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Cancelar))
                            .addComponent(Pan_Slado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AceptarActionPerformed

        this.altaPer();
    }//GEN-LAST:event_Btn_AceptarActionPerformed

    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
        // TODO add your handling code here:
        this.Limpiar();
}//GEN-LAST:event_Btn_CancelarActionPerformed

    private void Btn_ModMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModMailActionPerformed
        // TODO add your handling code here:
        ModifMail();
}//GEN-LAST:event_Btn_ModMailActionPerformed

    private void Btn_ModFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModFaxActionPerformed
        // TODO add your handling code here:
        ModifFax();
}//GEN-LAST:event_Btn_ModFaxActionPerformed

    private void Btn_ModTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModTelActionPerformed
        // TODO add your handling code here:
        ModifTelefono();
}//GEN-LAST:event_Btn_ModTelActionPerformed

    private void Btn_ModDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModDepActionPerformed
        // TODO add your handling code here:
        ModifProvDep();
}//GEN-LAST:event_Btn_ModDepActionPerformed

    private void Btn_ModCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModCelActionPerformed
        // TODO add your handling code here:
        ModifCelular();
}//GEN-LAST:event_Btn_ModCelActionPerformed

    private void ComB_ProvDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComB_ProvDepActionPerformed
        // TODO add your handling code here:
        mObjProvDepSel = (Dom_Class_ProvinDepar) ComB_ProvDep.getSelectedItem();
}//GEN-LAST:event_ComB_ProvDepActionPerformed

    private void Btn_ModPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModPaisActionPerformed
        // TODO add your handling code here:
        this.ModifPais();
}//GEN-LAST:event_Btn_ModPaisActionPerformed

    private void ComB_PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComB_PaisActionPerformed
        // TODO add your handling code here:
        CargarProvDep();
}//GEN-LAST:event_ComB_PaisActionPerformed

    private void ComB_TipoDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComB_TipoDocumentoFocusLost
        // TODO add your handling code here:
}//GEN-LAST:event_ComB_TipoDocumentoFocusLost

    private void ComB_TipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComB_TipoDocumentoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ComB_TipoDocumentoActionPerformed

    private void Txt_DirreccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_DirreccionFocusGained
        // TODO add your handling code here:
        Txt_Dirreccion.selectAll();
    }//GEN-LAST:event_Txt_DirreccionFocusGained

    private void Txt_DirreccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DirreccionActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Txt_DirreccionActionPerformed

    private void Txt_LocalidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_LocalidadFocusGained
        // TODO add your handling code here:
        Txt_Localidad.selectAll();
}//GEN-LAST:event_Txt_LocalidadFocusGained

    private void Txt_LocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_LocalidadActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Txt_LocalidadActionPerformed

    private void Txt_RazonSocialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_RazonSocialFocusGained
        // TODO add your handling code here:
        Txt_RazonSocial.selectAll();
}//GEN-LAST:event_Txt_RazonSocialFocusGained

    private void Txt_RazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_RazonSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_RazonSocialActionPerformed

    private void Btn_AgreSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgreSaldoActionPerformed
        // TODO add your handling code here:
        altaSaldo();
        
}//GEN-LAST:event_Btn_AgreSaldoActionPerformed

    private void Btn_BajaSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BajaSaldoActionPerformed
        // TODO add your handling code here:
        bajaSaldo();
}//GEN-LAST:event_Btn_BajaSaldoActionPerformed

    private void ComB_MonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComB_MonedaActionPerformed
        // TODO add your handling code here:
        mObjMonedaSelec = (Dom_Class_Moneda) ComB_Moneda.getSelectedItem();
    
}//GEN-LAST:event_ComB_MonedaActionPerformed

    private void Btn_ModMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModMonActionPerformed
        // TODO add your handling code here:}
        ModifMoneda();
}//GEN-LAST:event_Btn_ModMonActionPerformed

    private void Che_FechPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Che_FechPagoActionPerformed
        // TODO add your handling code here:
       if (Che_FechPago.isSelected()) this.setEnableFechPago('T');
       else this.setEnableFechPago('t');
    }//GEN-LAST:event_Che_FechPagoActionPerformed

    private void ComB_FaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComB_FaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComB_FaxActionPerformed

    private void ComB_DiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComB_DiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComB_DiaActionPerformed

    private void ComB_TipFechPabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComB_TipFechPabActionPerformed
        // TODO add your handling code here:
        switch (ComB_TipFechPab.getSelectedIndex()){
            case 0: 
                this.setEnableFechPago('D');
            break;
            case 1: 
                this.setEnableFechPago('M');
            break;
            case 2:
                this.setEnableFechPago('A');
            break;
        }// Fin switch
    }//GEN-LAST:event_ComB_TipFechPabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Aceptar;
    private javax.swing.JButton Btn_AgreSaldo;
    private javax.swing.JButton Btn_BajaSaldo;
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_ModCel;
    private javax.swing.JButton Btn_ModDep;
    private javax.swing.JButton Btn_ModFax;
    private javax.swing.JButton Btn_ModMail;
    private javax.swing.JButton Btn_ModMon;
    private javax.swing.JButton Btn_ModPais;
    private javax.swing.JButton Btn_ModTel;
    private javax.swing.JCheckBox Che_FechPago;
    protected javax.swing.JComboBox ComB_Celular;
    protected javax.swing.JComboBox ComB_CondIva;
    private javax.swing.JComboBox ComB_Dia;
    protected javax.swing.JComboBox ComB_Email;
    protected javax.swing.JComboBox ComB_Fax;
    private javax.swing.JComboBox ComB_Mes;
    private javax.swing.JComboBox ComB_Moneda;
    protected javax.swing.JComboBox ComB_Pais;
    protected javax.swing.JComboBox ComB_ProvDep;
    protected javax.swing.JComboBox ComB_Tel;
    private javax.swing.JComboBox ComB_TipFechPab;
    protected javax.swing.JComboBox ComB_TipoDocumento;
    private com.toedter.calendar.JDateChooser Dat_FechIniPago;
    private javax.swing.ButtonGroup GruRd_Saldo;
    private javax.swing.JLabel Lbl_Aviso;
    private javax.swing.JLabel Lbl_Dia;
    private javax.swing.JLabel Lbl_Intervalo;
    private javax.swing.JLabel Lbl_Intervalo1;
    private javax.swing.JLabel Lbl_Mes;
    private javax.swing.JLabel Lbl_Numero;
    private javax.swing.JLabel Lbl_TipFechPag;
    private javax.swing.JRadioButton Or_Acreedor;
    private javax.swing.JRadioButton Or_Deudor;
    protected javax.swing.JPanel Pan;
    private javax.swing.JPanel Pan_Slado;
    private javax.swing.JPanel Pan_Slado2;
    private javax.swing.JSpinner Spi_Aviso;
    private javax.swing.JSpinner Spi_Intervalo;
    private javax.swing.JTable Tab_Saldo;
    protected javax.swing.JFormattedTextField TxtF_LimAcree;
    protected javax.swing.JFormattedTextField TxtF_LimDeud;
    protected javax.swing.JFormattedTextField TxtF_NumDocumento;
    protected javax.swing.JFormattedTextField TxtF_Rut;
    protected javax.swing.JFormattedTextField TxtF_SaldoMonto;
    protected javax.swing.JTextField Txt_Dirreccion;
    protected javax.swing.JTextField Txt_Localidad;
    public javax.swing.JTextField Txt_RazonSocial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    protected abstract LogN_ClassAb_Persona getPersona ();

    // <editor-fold defaultstate="collapsed" desc="Metodos Pais">
    private void ModifPais (){
         // TODO add your handling code here:
        ArrayList ColPais = mObjFachada.listarPais();

       FrmDi_CreaPorNom FrmCreXNom = new FrmDi_CreaPorNom(mFrmCon, "Pais", ColPais) {

            @Override
            protected LogN_ClassAb_CrePorNom crearCrePorNom() throws InputException {
                Dom_Class_Pais mObjP = new Dom_Class_Pais (super.TxtF_Modificar.getText());
                mObjP.validar();
                return mObjP;
            }
        };
        FrmCreXNom.setVisible(true);

        if(FrmDi_CreaPorNom.RET_OK == FrmCreXNom.getReturnStatus()){
            for (LogN_Class_Accion<Dom_Class_Pais> ObjAcc  : FrmCreXNom.getAccion()){
                Dom_Class_Pais ObjAccPais = ObjAcc.getmAccionar();
                switch (ObjAcc.mAccionActual) {
                    case LogN_Class_Accion.Agreger:
                        try {
                            mObjFachada.altaPais(ObjAccPais);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }
                    break;
                    case LogN_Class_Accion.Modificar:

                        
                        Dom_Class_Pais ObjPaisAn = (Dom_Class_Pais)mObjModComB_Pais.getElementAt(ObjAcc.getmAccionar());
                        
                        try {
                            mObjFachada.modifPais(ObjPaisAn, ObjAccPais);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex);
                        }
                    break;
                    case LogN_Class_Accion.Eliminar:
                        try {
                            mObjFachada.bajaPais(ObjAccPais);
                        } catch (InputException ex) {
                           JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }

                    break;
                }// Fin switch
            }//Fin for

            cargarPais();
            
        } // Fin if
    }
    
    private void cargarPais (){
        ArrayList<Dom_Class_Pais> ColPais = mObjFachada.listarPais();
        try{
             mObjModComB_Pais = new PersonalComboBoxMedel<Dom_Class_Pais>
                    (ColPais, PersonalComboBoxMedel.Alfabet_Acendente, null, null) {

                @Override
                public boolean ComClassIn(Object o) {
                    return (o instanceof Dom_Class_Pais);
                }
            };
        }catch (InputException Ex){
            
        }
       
        mObjPaisSel = null;
        ComB_Pais.setModel(mObjModComB_Pais);
        if(ColPais.size() > 0 ){
            ComB_Pais.setSelectedIndex(0);
        }
    }
    
    // </editor-fold>    
    
    // <editor-fold defaultstate="collapsed" desc="Metodo ProvinciaDep">
    private void ModifProvDep (){
         // TODO add your handling code here:
        ArrayList ColProvD = mObjPaisSel.listarProvoDep();

       FrmDi_CreaPorNom FrmCreXNom = new FrmDi_CreaPorNom(mFrmCon, "provincia o departamento", ColProvD) {

            @Override
            protected LogN_ClassAb_CrePorNom crearCrePorNom() throws InputException {
                Dom_Class_ProvinDepar mObjP = new Dom_Class_ProvinDepar (super.TxtF_Modificar.getText());
                mObjP.validar();
                return mObjP;
            }
        };
        FrmCreXNom.setVisible(true);

        if(FrmDi_CreaPorNom.RET_OK == FrmCreXNom.getReturnStatus()){
            for (LogN_Class_Accion<Dom_Class_ProvinDepar> ObjAcc  : FrmCreXNom.getAccion()){
                Dom_Class_ProvinDepar ObjAccProvDep = ObjAcc.getmAccionar();
                
                switch (ObjAcc.mAccionActual) {
                    case LogN_Class_Accion.Agreger:
                        try {
                            mObjFachada.altaProvDep(mObjPaisSel, ObjAccProvDep);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }
                    break;
                    case LogN_Class_Accion.Modificar:

                        
                        Dom_Class_ProvinDepar ObjProvinDeparAn = (Dom_Class_ProvinDepar)mObjModComB_ProvDep.getElementAt(ObjAccProvDep);
                        
                        try {
                            mObjFachada.modiProvDep(ObjProvinDeparAn, ObjAccProvDep);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex);
                        }
                    break;
                    case LogN_Class_Accion.Eliminar:
                        try {
                            mObjFachada.bajaProvDep(mObjPaisSel, ObjAccProvDep);
                        } catch (InputException ex) {
                           JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }

                    break;
                }// Fin switch
            }//Fin for

            CargarProvDep();
            
        } // Fin if
    }
    
    private void CargarProvDep (){
        mObjPaisSel =(Dom_Class_Pais) mObjModComB_Pais.getSelectedItem();
        try {
             mObjModComB_ProvDep = new PersonalComboBoxMedel<Dom_Class_ProvinDepar>
                (mObjPaisSel.listarProvoDep(), PersonalComboBoxMedel.Alfabet_Acendente, null, null) {
                    @Override
                    public boolean ComClassIn(Object o) {
                        return (o instanceof Dom_Class_ProvinDepar);
                    }
                };
        }catch (InputException ex){}
       
        
        if (mObjModComB_ProvDep.getSize() > 0) mObjProvDepSel = (Dom_Class_ProvinDepar) mObjModComB_ProvDep.getElementAt(0);
        ComB_ProvDep.setModel(mObjModComB_ProvDep);
    }
    
// </editor-fold>   
    
    // <editor-fold defaultstate="collapsed" desc="Metodo Telefono">
    private void ModifTelefono (){
         // TODO add your handling code here:
        ArrayList ColTel = mColTel;
       FrmDi_Contacto FrmCreXNom = new FrmDi_Contacto(mFrmCon, "Telefono", ColTel) {

            @Override
            protected LogN_ClassAb_Contacto cargarContacto() throws InputException {
                Dom_Class_Tel ObjTel = new Dom_Class_Tel
                        (TxtF_Modificar.getText(), TxtA_Detalle.getText());
                ObjTel.validar();
                return ObjTel;
            }
        };
        FrmCreXNom.setVisible(true);

        if(FrmDi_CreaPorNom.RET_OK == FrmCreXNom.getReturnStatus()){
            for (LogN_Class_Accion<Dom_Class_Tel> ObjAcc  : FrmCreXNom.getAccion()){
                Dom_Class_Tel ObjTel = ObjAcc.getmAccionar();
                switch (ObjAcc.mAccionActual) {
                    case LogN_Class_Accion.Agreger:
                        
                            mColTel.add(ObjTel);
                            ObjTel.setNum(mNumTel++);

                    break;
                    case LogN_Class_Accion.Modificar:
                        
                        Dom_Class_Tel ObjTelAn = (Dom_Class_Tel) mObjModComB_ProvDep.getElementAt(ObjTel);
                        
                        try {
                            ObjTelAn.modificar(ObjTel);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }
                        
                    break;
                    case LogN_Class_Accion.Eliminar:

                            mColTel.remove(ObjTel);


                    break;
                }// Fin switch
            }//Fin for

            CargarTel();
            
        } // Fin if
        
    }
    
    private void CargarTel (){
        try {
            mObjModComB_Tel = new PersonalComboBoxMedel<Dom_Class_Tel>(mColTel, PersonalComboBoxMedel.Alfabet_Acendente, null, null) {
                @Override
                public boolean ComClassIn(Object o) {
                    throw new UnsupportedOperationException("Not supported yet.");
                }
            };
        }catch (InputException ex){}

        ComB_Tel.setModel(mObjModComB_Tel);
    }
    
    private void asiganrTel ( LogN_ClassAb_Persona xObjPer) throws InputException{
        String Error = "";
        for (Dom_Class_Tel ObjTel: mColTel){
            try {
                xObjPer.altaTel(ObjTel);
            } catch (InputException ex) {
                Error += ex.getLocalizedMessage() + "/n";
            }
        }
        if (!Error.equals("")) throw new InputException (Error);
        
    }
    
// </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Metodo Celular">
    private void ModifCelular (){
         // TODO add your handling code here:
        ArrayList ColCel = mColCel;
       FrmDi_Contacto FrmCreXNom = new FrmDi_Contacto(mFrmCon, "Celefono", ColCel) {

            @Override
            protected LogN_ClassAb_Contacto cargarContacto() throws InputException {
                Dom_Class_Cel ObjCel = new Dom_Class_Cel
                        (TxtF_Modificar.getText(), TxtA_Detalle.getText());
                ObjCel.validar();
                return ObjCel;
            }
        };
        FrmCreXNom.setVisible(true);

        if(FrmDi_CreaPorNom.RET_OK == FrmCreXNom.getReturnStatus()){
            for (LogN_Class_Accion<Dom_Class_Cel> ObjAcc  : FrmCreXNom.getAccion()){
                Dom_Class_Cel ObjCel = ObjAcc.getmAccionar();
                switch (ObjAcc.mAccionActual) {
                    case LogN_Class_Accion.Agreger:
                        
                            mColCel.add(ObjCel);
                            ObjCel.setNum(mNumCel++);

                    break;
                    case LogN_Class_Accion.Modificar:
                        
                        Dom_Class_Cel ObjCelAn = (Dom_Class_Cel) mObjModComB_ProvDep.getElementAt(ObjCel);
                        
                        try {
                            ObjCelAn.modificar(ObjCel);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }
                        
                    break;
                    case LogN_Class_Accion.Eliminar:

                            mColCel.remove(ObjCel);


                    break;
                }// Fin switch
            }//Fin for

            CargarCel();
            
        } // Fin if
    }
    
    
    
    private void CargarCel (){
        try {
             mObjModComB_Cel = new PersonalComboBoxMedel<Dom_Class_Cel>(mColCel, PersonalComboBoxMedel.Alfabet_Acendente, null, null) {

                @Override
                public boolean ComClassIn(Object o) {
                    return (o instanceof Dom_Class_Cel);
                }
            };
        }catch (InputException ex){
            
        }
       
        ComB_Celular.setModel(mObjModComB_Cel);
    }
    
    private void asiganrCel ( LogN_ClassAb_Persona xObjPer) throws InputException{
        String Error = "";
        for (Dom_Class_Cel ObjCel: mColCel){
            try {
                xObjPer.altaCel(ObjCel);
            } catch (InputException ex) {
                Error += ex.getLocalizedMessage() + "/n";
            }
        }
        if (!Error.equals("")) throw new InputException (Error);
        
    }
    
// </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Metodo Fax">
  
    private void ModifFax (){
         // TODO add your handling code here:
       ArrayList ColFax = mColFax;
       FrmDi_Contacto FrmCreXNom = new FrmDi_Contacto(mFrmCon, "Faxefono", ColFax) {

            @Override
            protected LogN_ClassAb_Contacto cargarContacto() throws InputException {
                Dom_Class_Fax ObjFax = new Dom_Class_Fax
                        (TxtF_Modificar.getText(), TxtA_Detalle.getText());
                ObjFax.validar();
                return ObjFax;
            }
        };
        FrmCreXNom.setVisible(true);

        if(FrmDi_CreaPorNom.RET_OK == FrmCreXNom.getReturnStatus()){
            for (LogN_Class_Accion<Dom_Class_Fax> ObjAcc  : FrmCreXNom.getAccion()){
                Dom_Class_Fax ObjFax = ObjAcc.getmAccionar();
                switch (ObjAcc.mAccionActual) {
                    case LogN_Class_Accion.Agreger:
                        
                            mColFax.add(ObjFax);
                            ObjFax.setNum(mNumFax++);

                    break;
                    case LogN_Class_Accion.Modificar:
                        
                        Dom_Class_Fax ObjFaxAn = (Dom_Class_Fax) mObjModComB_ProvDep.getElementAt(ObjFax);
                        
                        try {
                            ObjFaxAn.modificar(ObjFax);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }
                        
                    break;
                    case LogN_Class_Accion.Eliminar:

                            mColFax.remove(ObjFax);
                            
                    break;
                }// Fin switch
            }//Fin for

            CargarFax();
            
        } // Fin if
    }
    
    
    
    private void CargarFax (){
        try{
            mObjModComB_Fax = new PersonalComboBoxMedel<Dom_Class_Fax>(mColFax, PersonalComboBoxMedel.Alfabet_Acendente, null, null) {
                @Override
                public boolean ComClassIn(Object o) {
                    throw new UnsupportedOperationException("Not supported yet.");
                }
            };
        } catch (InputException ex){}

        ComB_Fax.setModel(mObjModComB_Fax);
    }
    
    private void asiganrFax ( LogN_ClassAb_Persona xObjPer) throws InputException{
        String Error = "";
        for (Dom_Class_Fax ObjFax: mColFax){
            try {
                xObjPer.altaFax(ObjFax);
            } catch (InputException ex) {
                Error += ex.getLocalizedMessage() + "/n";
            }
        }
        if (!Error.equals("")) throw new InputException (Error);
        
    }
    
// </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Metodo Mail">
  
    private void ModifMail (){
         // TODO add your handling code here:
       ArrayList ColMail = mColMail;
       FrmDi_Contacto FrmCreXNom = new FrmDi_Contacto(mFrmCon, "Mailefono", ColMail) {

            @Override
            protected LogN_ClassAb_Contacto cargarContacto() throws InputException {
                Dom_Class_Mail ObjMail = new Dom_Class_Mail
                        (TxtF_Modificar.getText(), TxtA_Detalle.getText());
                ObjMail.validar();
                return ObjMail;
            }
        };
        FrmCreXNom.setVisible(true);

        if(FrmDi_CreaPorNom.RET_OK == FrmCreXNom.getReturnStatus()){
            for (LogN_Class_Accion<Dom_Class_Mail> ObjAcc  : FrmCreXNom.getAccion()){
                Dom_Class_Mail ObjMail = ObjAcc.getmAccionar();
                switch (ObjAcc.mAccionActual) {
                    case LogN_Class_Accion.Agreger:
                        
                            mColMail.add(ObjMail);
                            ObjMail.setNum(mNumMail++);

                    break;
                    case LogN_Class_Accion.Modificar:
                        
                        Dom_Class_Mail ObjMailAn = (Dom_Class_Mail) mObjModComB_ProvDep.getElementAt(ObjMail);
                        
                        try {
                            ObjMailAn.modificar(ObjMail);
                        } catch (InputException ex) {
                            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
                        }
                        
                    break;
                    case LogN_Class_Accion.Eliminar:

                            mColMail.remove(ObjMail);
                            
                    break;
                }// Fin switch
            }//Fin for

            CargarMail();
            
        } // Fin if
    }
    
    
    
    private void CargarMail (){
        try {
            mObjModComB_Mail = new PersonalComboBoxMedel<Dom_Class_Mail>(mColMail, PersonalComboBoxMedel.Alfabet_Acendente, null, null) {

            @Override
            public boolean ComClassIn(Object o) {
                return (o instanceof Dom_Class_Mail);
            }
        } ;  
        }catch (InputException ex){}

        ComB_Email.setModel(mObjModComB_Mail);
    }
    
    private void asiganrMail ( LogN_ClassAb_Persona xObjPer) throws InputException{
        String Error = "";
        for (Dom_Class_Mail ObjMail: mColMail){
            try {
                xObjPer.altamMail(ObjMail);
            } catch (InputException ex) {
                Error += ex.getLocalizedMessage() + "/n";
            }
        }
        if (!Error.equals("")) throw new InputException (Error);
        
    }
    
// </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Metodo Moneda">
  
    private void ModifMoneda (){
         // TODO add your handling code here:
        FrmDi_Moneda ObjFrmDiMoneda = new FrmDi_Moneda(mFrmCon);
        ObjFrmDiMoneda.setVisible(true);
        if (ObjFrmDiMoneda.getReturnStatus() == FrmDi_Moneda.RET_OK){
            try{
                ComB_Moneda.setSelectedIndex(0);
            }catch (java.lang.IllegalArgumentException ex){
                
            }
            
        }
    }
    
    
    
    private void CargarMoneda (){
        ArrayList ColMoneda = mObjFachada.listarMondeda();
        try{
              mObjModComB_Moneda = new PersonalComboBoxMedel<Dom_Class_Moneda>(ColMoneda, PersonalComboBoxMedel.Alfabet_Acendente, null, null) {

                @Override
                public boolean ComClassIn(Object o) {
                    return (o instanceof Dom_Class_Moneda);
                }
            };
        }catch (InputException ex){}
      
        mObjFachada.addObservadorMoneda(mObjModComB_Moneda);
        ComB_Moneda.setModel(mObjModComB_Moneda);
        if (ColMoneda.size() > 0) mObjMonedaSelec = (Dom_Class_Moneda) ColMoneda.get(0);


    }
    

    
// </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Metodo Saldo">


    private void altaSaldo (){
        Dom_Class_Saldo ObjSaldo = crearSaldo();
        try {
            ObjSaldo.validar();
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
            return;
        }

        if (mColSaldo.contains(ObjSaldo)){
            JOptionPane.showMessageDialog(this, "El Saldo ya exisgte compruebe la moneda");
            return;
        
        }

        mColSaldo.add(ObjSaldo);

        mObjModelJTSaldo.addRow(ObjSaldo);

        limpiarMenSaldo();
    }
    
    private void bajaSaldo (){

        if (mColSaldo.remove(mObjSaldo)){
            mObjModelJTSaldo.deleteRow(mObjSaldo);
        }
    }

    public void limpiarMenSaldo (){
        TxtF_SaldoMonto.setValue(new Float (0.0));
        TxtF_LimAcree.setValue(new Float (0.0));
        TxtF_LimDeud.setValue(new Float (0.0));
        ComB_Moneda.requestFocus();
    }


    public Dom_Class_Saldo crearSaldo(){
        Number monto = (Number) TxtF_SaldoMonto.getValue();
        Number LimAcree = (Number) TxtF_LimAcree.getValue();
        Number LimDeudor = (Number) TxtF_LimDeud.getValue();
        boolean SalHacree = Or_Acreedor.isSelected();
        
        return new Dom_Class_Saldo(SalHacree, monto.floatValue(), mObjMonedaSelec, LimAcree.floatValue(), LimDeudor.floatValue());
    }
    
    private void CargarSaldo(){
        mColSaldo = new ArrayList<Dom_Class_Saldo>();
        mObjModelJTSaldo = new MedeljTabSaldo(new ArrayList<Dom_Class_Saldo>());
        Tab_Saldo.setModel(mObjModelJTSaldo);
        mObjSaldo = null;
    }
    
    private void asiganrSaldo (LogN_ClassAb_Persona xObjPer) throws InputException{
        String Error = "";
        for (Dom_Class_Saldo ObjSaldo: mColSaldo){
            try {
                xObjPer.altaSaldo(ObjSaldo);
            } catch (InputException ex) {
                Error += ex.getLocalizedMessage() + "/n";
            }
        }
        if (!Error.equals("")) throw new InputException (Error);
        
    }
// </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Metodo Observador Auliliar">
        public synchronized void deleteObserver(Observer o) {
            mObjObAux.deleteObserver(o);
        }

        public synchronized int countObservers() {
            return mObjObAux.countObservers();
        }

        public synchronized void addObserver(Observer o) {
            mObjObAux.addObserver(o);
        }

        public FrmIn_AgrPer getmObjObservado() {
            return mObjObAux.getmObjObservado();
        }

        public LogN_Class_Accion getmObjAccion() {
            return mObjObAux.getmObjAccion();
        }

        public void Notifiar(Object arg) {
            mObjObAux.Notifiar(arg);
        }
    // </editor-fold>
    
    
    
    

    private void Tab_SaldoValueChanged(ListSelectionEvent evt){
        mObjSaldo = mObjModelJTSaldo.getSaldo(Tab_Saldo.getSelectedRow());
    }
    
    private  void Limpiar (){
        Lbl_Numero.setText("" + this.getNumPer());
        Txt_RazonSocial.setText("");
        Txt_Dirreccion.setText("");
        TxtF_Rut.setText("");
        TxtF_NumDocumento.setText("");
        
        
        
        //Celular
        mNumCel = 0;
        mColCel = new ArrayList<Dom_Class_Cel>();
        CargarCel();
        
        //Telefono
        mNumTel = 0;
        mColTel = new ArrayList<Dom_Class_Tel>();
        CargarTel();
        
        //Fax
        mNumFax = 0;
        mColFax = new ArrayList<Dom_Class_Fax>();
        CargarFax();
        
        //Email
        mNumMail = 0;
        mColMail = new ArrayList<Dom_Class_Mail>();
        CargarMail();
        
        //Saldo
        mColSaldo = new ArrayList<Dom_Class_Saldo>();
        mObjModelJTSaldo = new MedeljTabSaldo(new ArrayList<Dom_Class_Saldo> ());
        Tab_Saldo.setModel(mObjModelJTSaldo);
        mObjSaldo = null;
        
        Che_FechPago.setSelected(false);
        
        this.setEnableFechPago('t');
        
        //FechaPago
        
        Spi_Intervalo.setValue(0);
        ComB_Mes.setSelectedIndex(0);
        ComB_Dia.setSelectedIndex(0);
        Spi_Aviso.setValue(0);
    } // Fin Limpiar
    
    protected abstract int getNumPer();
    
    public void altaPer (){
        LogN_ClassAb_Persona ObjPer = getPersona();
        try {
            
            asiganrTel(ObjPer);
            asiganrCel(ObjPer);
            asiganrFax(ObjPer);
            asiganrMail(ObjPer);
            asiganrSaldo(ObjPer);
            
            
            mObjFachada.altaPersonaEx((LogN_ClassAb_PerExterna)ObjPer);
        } catch (InputException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
            return;
        }
        Limpiar();
        this.Notifiar(ObjPer);
    }

    public void setWinCon(Window mFrmCon) {
        this.mFrmCon = mFrmCon;
    }
    
    
    public void setEnableFechPago (char xOpcion){
        switch (xOpcion){
            case 'D':// En caso de que se selecione por dia
                // Desablilita el seleccionador de dia 
                Lbl_Dia.setEnabled(false);
                ComB_Dia.setEnabled(false);
                
                // Desablilita el seleccionador de mes
                Lbl_Mes.setEnabled(false);
                ComB_Mes.setEnabled(false);
                
            break;
            case 'M': // En caso de que sea mes                 
                // Desablilita el seleccionador de dia 
                Lbl_Dia.setEnabled(true);
                ComB_Dia.setEnabled(true);
                
                // Desablilita el seleccionador de mes
                Lbl_Mes.setEnabled(false);
                ComB_Mes.setEnabled(false);

            break;
            case 'A':
                                // Desablilita el seleccionador de dia 
                Lbl_Dia.setEnabled(true);
                ComB_Dia.setEnabled(true);
                
                // Desablilita el seleccionador de mes
                Lbl_Mes.setEnabled(true);
                ComB_Mes.setEnabled(true);
            break;
            case 'T':
                Lbl_Intervalo.setEnabled(true);
                Spi_Intervalo.setEnabled(true);
                
                Lbl_Aviso.setEnabled(true);
                Spi_Aviso.setEnabled(true);
                
                
                Lbl_TipFechPag.setEnabled(true);
                ComB_TipFechPab.setEnabled(true);
                
                this.ComB_TipFechPabActionPerformed(null);
            break;
            case 't':
                // Desablilita el seleccionador de dia 
                Lbl_Dia.setEnabled(false);
                ComB_Dia.setEnabled(false);
                
                // Desablilita el seleccionador de mes
                Lbl_Mes.setEnabled(false);
                ComB_Mes.setEnabled(false);
                
                ComB_TipFechPab.setEnabled(false);
                Lbl_TipFechPag.setEnabled(false);
                
                Lbl_Intervalo.setEnabled(false);
                Spi_Intervalo.setEnabled(false);
                
                Lbl_Aviso.setEnabled(false);
                Spi_Aviso.setEnabled(false);
            break;
        } // Fin siwtch
    } // Fin setEnableFechPago
    
    protected LogN_ClassAb_FechPag getFechP (){
        LogN_ClassAb_FechPag ObjFp = null;
        Date FechInicio;
        
        if (Che_FechPago.isSelected()){
            int Intervalo , Aviso;
            Intervalo = ((Number) Spi_Intervalo.getValue()).intValue();
            Aviso = ((Number) Spi_Aviso.getValue()).intValue();
            FechInicio = Dat_FechIniPago.getDate();
            switch ("" + ComB_TipFechPab.getSelectedItem()){
                case "Diario":
                    ObjFp = new Dom_Class_FechPDiario(Intervalo, Aviso, FechInicio);
                break;
                case "Mensual":
                    ObjFp = new Dom_Class_FechPMensual
                            (Intervalo, Aviso, FechInicio, 
                            Integer.parseInt("" + ComB_Dia.getSelectedItem()));
                    break;
                case "Anual":
                    ObjFp = new Dom_Class_FechPAño
                            (Intervalo, Aviso, FechInicio, 
                            Integer.parseInt("" + ComB_Dia.getSelectedItem()),
                            Integer.parseInt("" + ComB_Mes.getSelectedItem())
                            );
                break;   
            }// Fin switch
        }// Fin If
        return ObjFp;
    }
    
}
